### ISSUE TITLE
Don't log individual test if it's a single passing anonymous test

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#10]
In a lot of my node modules I have a single test without a title. Would be nice if it only showed `1 test passed` and not ` ✔ [anonymous]` in that case.

**Comment by Qix-** [comment]
Doesn't AVA enumerate tests before running them?

**Comment by sindresorhus** [comment]
Yup, see the actual commit.

**Comment by Qix-** [comment]
:+1:
