### ISSUE TITLE
Time taken to run tests

### ISSUE THREAD

**Issue by portgasd666** [sindresorhus/ava#100]
Since the big win by running tests concurrently is the time gain is there anyway to actually find out how long tests took to run ? I remember always getting the time taken for tests with Mocha.

**Comment by vdemedes** [comment]
@sindresorhus should we leave this as a feature request? Or advise to use:

```
$ time ava
```

**Comment by kevva** [comment]
Don't we have this already?

**Comment by vdemedes** [comment]
@kevva No, we only report individual test time, when it reaches certain threshold. We don't display total test time atm.

**Comment by sindresorhus** [comment]
Users can just use `$ time ava`.
