### ISSUE TITLE
t.same() and sparse arrays

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/ava#104]
@twada I think this is an issue of `power-assert`, but I don't know which package is responsible for it.

```js
test(t => {
	const data = [];
	data[1] = 'unicorn';
	t.same(data, ['unicorn']);
	t.end();
});
```

Result:
```
  ✖ [anonymous]   
  t.same(data, ['unicorn'])
         |                 
         ["unicorn"]       
  

  1 test failed
```

What I expected:
```
  ✖ [anonymous]   
  t.same(data, ['unicorn'])
         |                 
         [ , 'unicorn']       
  

  1 test failed
```

**Comment by twada** [comment]
@schnittstabil Thank you for reporting! I'll fix it ASAP.

Feel free to submit issue to top the level project [power-assert](https://github.com/power-assert-js/power-assert/issues) when you are unsure where to report.

**Comment by twada** [comment]
Just released [stringifier 1.2.1](https://github.com/twada/stringifier/blob/master/CHANGELOG.md#121-2015-10-26) to fix this bug.
[stringifier](https://github.com/twada/stringifier) is a dependency of power-assert-formatter, which follows versionings to semver, so this bugfix is already applied to new installation of AVA.

```
ava@0.3.0
└──power-assert-formatter@1.1.0
   └──stringifier@1.2.1
```

@schnittstabil Would you check the fix?

**Comment by schnittstabil** [comment]
@twada Thanks a lot. Only the quotes does not match.

**Comment by twada** [comment]
@schnittstabil Unfortunately, string does not have any information of its raw literal value such as quotes (single-quoted, double-quoted and template literals), it won't match. I'm using double quotes as the default stringify strategy that as same as JSON.

**Comment by schnittstabil** [comment]
> stringify strategy that as same as JSON

That's reasonable. Thanks again.
