### ISSUE TITLE
after/before/afterEach/beforeEach hooks should not have a title

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#105]
It doesn't make sense for them to have a title as you're just hooks.

Should we just prevent it being set in the first place?

**Comment by vdemedes** [comment]
I'd handle this issue like this:

1. beforeEach/afterEach can't have titles, never display them
2. before/after can have titles and display them **only** when they exist. If before/after hook does not have a title, don't display it.

If any of the supported hook methods fail, display it like usual: `x [anonymous]: error`.

**Comment by sindresorhus** [comment]
> before/after can have titles and display them only when they exist. If before/after hook does not have a title, don't display it.

Why? In what cases is that needed or useful?

> If any of the supported hook methods fail, display it like usual: x [anonymous]: error.

If a beforeEach/afterEach hook fails, we could show something like: `beforeEach for 'test title' failed`

**Comment by vdemedes** [comment]
If a beforeEach/afterEach hook fails, we could show something like: beforeEach for 'test title' failed

👍

    Why? In what cases is that needed or useful?

I was thinking, that having titles for beforeEach/afterEach will pollute the output, but titles for before/after won't do much noise. That's the only reason ;)

**Comment by sindresorhus** [comment]
> I was thinking, that having titles for beforeEach/afterEach will pollute the output, but titles for before/after won't do much noise. That's the only reason ;)

I figured, but I'm more interested in use-cases for when titles would be useful in before/after? If there are good use-cases, we might want to document that too.

**Comment by schnittstabil** [comment]
Currently ava supports multiple before(Each)/after(Each) hooks.
It would be convenient to know which one failed (e.g. by its title).
(And also which test _triggered_ that hook.)

**Comment by vdemedes** [comment]
I can think only of one use-case: I have many before/after hooks and having a title helps me find quicker which one failed. We can't give them friendly titles, like for beforeEach: `beforeEach for "something" failed`.

**Comment by sindresorhus** [comment]
You could also look at the line number and just go to it in the test file, though.

**Comment by vdemedes** [comment]
hahaha, I know that, that's why I wrote "find quicker" :D

**Comment by sindresorhus** [comment]
How is not the line number the quickest way? With the line number you can just go directly to that line using your editor shortcut. With the title you have to search for the correct hook.

**Comment by vdemedes** [comment]
I'm fine with either options, you just asked for a use-case and here it is :) Let's see what else might come up in this thread.

**Comment by schnittstabil** [comment]
> How is not the line number the quickest way? With the line number you can just go directly to that line using your editor shortcut. With the title you have to search for the correct hook.

The same applies to titles of regular tests :smirk:, but I would vote for keeping them, at least in this case.

Considering the following, I think it would be absolutely sufficient to display the error stack, which includes the function names:

```js
test.before(function createFixtures() {…});
test.before(function createTestdir() {…} );
```

Displaying the error stack would also indicate that the test script itself is erroneous, and not the _system under test_.

The same holds for beforeEach/afterEach. However, it would be helpful to know the test title. Therefore, I would suggest to wrap the Error e.g. with [nested-error-stacks](https://github.com/mdlavin/nested-error-stacks):

```js
throw new NestedError(`beforeEach for '${test.title}' failed`, beforeEachError);
```

**Comment by vdemedes** [comment]
So what's the status on this?

**Comment by sindresorhus** [comment]
Keep title support for all hooks, but only show it on failure. I realized it can also be beneficial to have titles on them for code readability in the test files if you have many hooks. For the beforeEach/afterEach also show the connected test. (Note to self: This behavior also needs to be documented).

@schnittstabil Not a big fan of `nested-error-stacks`. It creates unparsable stack traces. We can still include the test title in the beforeEach/afterEach error.
