### ISSUE TITLE
Tests are stuck

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#107]
I was looking into getting pageres to 100% code coverage. With the new release, it's possible to use `nyc` to test the coverage.

But with 0.3.0, the tests get in a state where they are stuck and do not complete. Actually, all the tests are printed as completed, but AVA is not continuing to the next step.

It's related to specific tests in pageres
1) https://github.com/sindresorhus/pageres/blob/master/test/test.js#L41-L51
2) https://github.com/sindresorhus/pageres/blob/master/test/test.js#L75-L84
3) https://github.com/sindresorhus/pageres/blob/master/test/test.js#L101-L105

Is there a breaking change I missed?

**Comment by sindresorhus** [comment]
Pageres master with AVA 0.3.0 works fine for me on OS X and Ubuntu. Can you check whether you have frozen phantomjs processes? Can you try running with `$ ava --serial`?

**Comment by SamVerschueren** [comment]
`$ ava --serial` doesn't help. Will pull the latest changes in tomorrow and try to reinstall my dependencies.  Will keep this updated.

**Comment by SamVerschueren** [comment]
Couldn't resist... Pulled in the latest version, did `npm install`, ran the tests and it all works just fine. :+1:
