### ISSUE TITLE
Transpile dependencies of the test file

### ISSUE THREAD

**Issue by madbence** [sindresorhus/ava#111]
`ava@0.3` works smoothly on a clean project, but fails to run on [mine](https://github.com/madbence/spacegame) (tests broke when i've upgraded to from `ava@0.2`):

```
(function (exports, require, module, __filename, __dirname) { import {
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
```

I'm sure it's caused by some weird `babel` dependency, so it might be unrelated to `ava`. Last working state is [7d31571](https://github.com/madbence/spacegame/tree/7d31571d0dbdb27a24ba4e4d467d4b0842673081), if i try to upgrade to `ava@0.3`, tests are broken.
I will investigate it tomorrow...

**Comment by Qix-** [comment]
Did you try `rm -rf node_modules` and `npm i`?

**Comment by madbence** [comment]
yup, still the same, btw it might be the same as #108 ?

**Comment by Qix-** [comment]
Yep, that's my guess.

**Comment by madbence** [comment]
So right now there is no way to test modules directly? I mean, i have to transpile them first, and test the transpiled files?

**Comment by sindresorhus** [comment]
Implicitly transpiling dependencies in 0.2.0 was a bug that was later fixed 0.3.0. Transpiling dependencies by default is both surprising and slow. I'm open to considering an option for enabling this, but it will not be by default.

**Comment by madbence** [comment]
what about allowing something like `$ babel-node node_modules/.bin/ava` ? i'm not really familiar with `ava` internals, so that's just an idea.

**Comment by sindresorhus** [comment]
That won't work as we spawn the test files. Just use AVA 0.2.0 until we've figured out how to deal with this. Alternatively use a fork where you've removed [this line](https://github.com/sindresorhus/ava/blob/730bf53239371446aa88fb6c5199caf3d48935a3/lib/babel.js#L8).

**Comment by axross** [comment]
> I'm open to considering an option for enabling this, but it will not be by default.

I agree your consider. I want to run both tests and target codes for tests with Babel. I think that is proper and as it should be.

**Comment by sindresorhus** [comment]
What should the option be named?

**Comment by axross** [comment]
`babel-recursive`?

**Comment by sindresorhus** [comment]
@floatdrop Any thoughts as to how we should solve this now that #103 has landed?

**Comment by floatdrop** [comment]
@madbence you can require file with following code in tests as workaround:

```js
// app.es5.js
require('babel/register');
require('./app');
```

@sindresorhus besides this workaround, not really.

**Comment by sindresorhus** [comment]
We could set the `execPath`, when we fork a test file, to the `babel-node` executable instead of vanilla node.

**Comment by theaqua** [comment]
Hm, any progress on that? Still can't use external files.

**Comment by sindresorhus** [comment]
@theaqua This issue is still open, so no. @floatdrop has already provided a workaround if you can't wait.

To move this issue forward, come up with a good name for a CLI flag to enable it.

**Comment by theaqua** [comment]
[pm2 uses](http://pm2.keymetrics.io/docs/usage/specifics/#babeljs) `execInterpreter` option. I think it's ok because most users will install custom interpreter (`coffeescript` or `babel`) as dependency and `ava` can search in local `node_modules` automagically.

**Comment by alexbooker** [comment]
@theaqua If I understand correctly, that is what Mocha does [too](https://babeljs.io/docs/setup/#mocha).

**Comment by madbence** [comment]
@sindresorhus 

- `--transpile-all -a`
- `--compile-all -a`
- or to be more flexible, do something like `--compilers js:babel/register` (like in mocha, istanbul, etc)

**Comment by alexbooker** [comment]
@madbence I like `--transpile-all`. 

I think `--transpile-transitive` is more descriptive/accurate, though.

**Comment by Qix-** [comment]
`--transpile-transitive` would be the longest command line flag I've seen in a while.

**Comment by alexbooker** [comment]
@Qix- `-tt` for short

**Comment by Qix-** [comment]
Per GNU specs on arguments, `-tt` would be supplying the short-form argument `-t` twice. Doesn't make sense. `--transpile-all` would make the most sense whilst still being correct. `--compile-all` isn't *technically* correct but would still probably be easier for people to type.

**Comment by madbence** [comment]
btw what's the rationale behind this behavior (ava transpiles tests only)? it's just slow?

**Comment by alexbooker** [comment]
@madbence https://github.com/sindresorhus/ava/issues/50

**Comment by jamestalmage** [comment]
It is more than just "ava transpiles tests only".

It is that ava allows you to write tests in ES2015 with zero impact on your production environment.
By zero impact, I mean no transpilation an **no polyfills**. (IMO polyfills are the sneakier harder to control bug).

For example, we make sure `Promise` is available inside your tests, without impacting it's availability in production code.

```js
// Always works in tests. Only works in production in Node >= 0.12
new Promise(...)
```

Trickier still is a prototype polyfill. Something like `String.prototype.includes()`. If Babel actually modifies the prototype, your test suite no longer protects you against mistakenly using it in production. Users of your lib will report errors in Node 0.12 that you can't possibly write a failing test case for (because it has been polyfilled even in your production environment).

AVA uses the runtime plugin to provide polyfill aliasing. An example of how that works [is here](https://github.com/babel/babel.github.io/blob/862b43db93e48762671267034a50c30c00e433e2/docs/usage/runtime.md#core-js-aliasing). This means that:

```js
// works in tests across platforms, throws in production code on platforms that do not support includes
".... some string ....".includes()
```

**Comment by Qix-** [comment]
@jamestalmage very good points. However, one of the things to consider is the viability of backwards compatibility in Node. NPM thrives under the idea of progressive code reform. Node proper is no exception. I think one of the motivations behind AVA is that it is, indeed, very progressive and puts into low-priority the considerations it makes towards older versions of Node.

**Comment by madbence** [comment]
hmm, i still don't get the point... why should i write my tests in es2015 if i can't write my lib in es2015? if i want to support some older node versions, i know that i *have* to publish a transpiled version of my lib (so i should test the transpiled code, which is not the default behavior right now). but maybe i'm just missing something about how one should develop modules in es2015...

**Comment by alexbooker** [comment]
Good  points, @jamestalmage.

My situation is this: I am writing an Express application and using the [require hook](https://babeljs.io/docs/setup/#babel_register) in an entry-point to transpile my entire app ([example](https://github.com/alexbooker/communitycasts.co/blob/master/source/server/index.js).)

I have seen @floatdrop's [solution](https://github.com/sindresorhus/ava/issues/111#issuecomment-152921900) but it would be tedious for me to use, as I require many test files.

@Whoaa512 had the same problem. He actually sent a submit a [pull request](https://github.com/sindresorhus/ava/pull/88) that I would like to see merged!

**Comment by Qix-** [comment]
@madbence you don't have to write your lib in ES2015. The fact AVA allows you to write your tests in ES2015 is just a functional gain.

**Comment by jamestalmage** [comment]
Because your tests are not used in the wild. Your production code might be. The idea is to let you use ES2015 for test code, even if you are not allowed to use it for production (because you wan't to support old Node without transpilation).

Another big issue with providing transpiled dependencies is, again, polyfills. For your code to run standalone, babel needs to include the polyfills in the output. This is not good if you want a small reusable library (you don't want Node loading up 10 copies of a `string.includes()` polyfill)

**Comment by alexbooker** [comment]
By the way, I really like how Mocha allows you to plugin transpilers like Babel:

    mocha ./test --recursive --compilers js:babel-core/register

**Comment by jamestalmage** [comment]
I don't think a cli-hook has been ruled out.

In the mean-time, `require('babel-core/register')` at the top of every test file should work.

**Comment by codyhatch** [comment]
It doesn't seem to work for me.  I added `require('babel-core/register')` to the top of a test file, then ran `ava ./example/test-file.js`, and it spat out:

```
(function (exports, require, module, __filename, __dirname) { import fetch from 'isomorphic-fetch';
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
```

Am I missing something?  For reference I'm writing my entire browser-based app in ES2015, and I just want a solution that'll efficiently transpile *everything*.  Mocha handles this really smoothly as @alexbooker noted.  I wouldn't *mind* adding the babel registration to the top of my tests if it would work, although it wouldn't be optimal.

**Comment by Whoaa512** [comment]
@codyhatch, adding `require('babel-core/register')` at the top of the file will enabled it for further requires but not for the file in which it was required.

**Comment by codyhatch** [comment]
So let's assume I have a project like:

```
src/
  app.js
  modules/
    module1.js
    module2.js
    ...
test/
  app.spec.js
  module1.spec.js
  module2.spec.js
  ...
```

So the workaround is to create a new `module2.wrapper.js` for every single test, which does nothing but register babel and then import the actual test?  That...seems to work.  But wow, that's a really ugly solution for a large project.  :(

Thanks though.

**Comment by BarryThePenguin** [comment]
Should we expect different behavior for those writing tests for a library (used in many unknown environments) and those writing tests for an application (used in a single known environment e.g. electron)?

I'm just thinking of my scenario where I want to write tests for an application that is run in electron. I'm using `electron-compile` and I have full control over the environment my es6 application is running in.

**Comment by jamestalmage** [comment]
A repo is worth a thousand comments: 

https://github.com/jamestalmage/__ava_with_babel_for_production

// @codyhatch @BarryThePenguin @alexbooker @madbence @theaqua

**Comment by BarryThePenguin** [comment]
@jamestalmage welp! I'm sold

Reading back through, it wasn't clear to me that you can

```
import test from 'ava';
import 'babel/register';

// now import ES6 
import app from '../src/app';

test('test app', t => {
	t.ok(app);
	t.end();
});
```

I'm happy with this as a solution

**Comment by billyjanitsch** [comment]
+1 for a `--compilers` (or perhaps `--preprocessors`) flag that lets you use custom register hooks, like mocha does (as @alexbooker alluded to) with a pretty clean syntax. Other test runners (Karma, babel-tape-runner) do similar things.

Including `import babel-core/register` at the top of every test file is clunky enough, and gets much worse if you want to write a custom compiler (e.g. [like this](https://gist.github.com/daviferreira/1503ce0532abca270b86), which is necessary to test JS that uses CSS modules). You should be able to specify this when invoking AVA.

**Comment by sparty02** [comment]
```import babel-core/register``` is a really good, simple workaround until this feature lands.  @sindresorhus what do you think about putting this in the README until it's officially addressed?

**Comment by sindresorhus** [comment]
@sparty02 Sure, PR welcome.

**Comment by franleplant** [comment]
Hi!
`import 'babel-core/register'` and `import 'babel-register'` are not working for me.

**Comment by jamestalmage** [comment]
You need to install as dependencies of your own project to use outside of tests

**Comment by franleplant** [comment]
Already done that @jamestalmage

**Comment by franleplant** [comment]
It was purely a problem with babel presets/plugins/config settings, nvm, thanks a lot

**Comment by ariporad** [comment]
@franleplant: Ok, then I'm going to close this (let me know if you want it re-opened). Have a nice day!

**Comment by franleplant** [comment]
:)

**Comment by Hurtak** [comment]
for anybody trying to make `import 'babel-core/register';` work in AVA, try installing babel-core 5.x.x, that did the trick for me, 6 doesn't work for some reason (you probably need have properly configured .babelrc in your directory or something)

**Comment by ariporad** [comment]
@Hurtak: Yes. Babel 6 doesn't do anything by default.

**Comment by kentcdodds** [comment]
This issue is solved for me by adding `--require 'babel-register'` (Babel 6) with a `.babelrc` file:

```javascript
{
  "presets": ["es2015", "stage-2"]
}
```

**Comment by kentcdodds** [comment]
If you're interested, here's a migration from Mocha to AVA in a small library: https://github.com/kentcdodds/starwars-names/pull/12/files?w=1

**Comment by jamestalmage** [comment]
Cool!

Your use of the `--require` flag is spot on for what we intended. #407 should make the experience even better.

We would value any feedback on pain points you encountered during the transition.

**Comment by kentcdodds** [comment]
Cool, I added a comment about that. I prefer to use `config` to avoid polluting the `package.json` keyspace :-) (It's also technically the recommended way to do what is being done).

Not really any pain points. The only thing that I would say is the assertions are pretty limiting. I prefer the declarative syntax of something like Chai. But I expect that the small surface area of the API is intentional. I ended up bringing in another utility library to make testing a little more declarative though.

**Comment by azhang** [comment]
This is what I use in my package.json file:

```
  "scripts": {
    "test": "ava --require babel-register --require babel-polyfill '**/*.test.js'"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ],
  },
```

**Comment by ruyadorno** [comment]
Had to dig around this issue this morning to get it working with babel@6.5.2 in order to run on travis with node@0.12.10 and npm@2.14.9

I had to use the `ignore` [babel config property](https://babeljs.io/docs/usage/require/) that somehow went unmentioned in this whole thread, here is the actual snippet of code that I dropped at the top of my test file:

```js
require('babel-core/register')({
	ignore: false
});
```

_TIP: `ignore` can also be a function that receives a filename and returns `false`, this way you can filter only the files that need the transpiling, I ended up using it and test times were a lot better_

**Comment by novemberborn** [comment]
@sindresorhus @vdemedes @jamestalmage is there anything we want to improve here beyond the existing `--require` support? If not I'll close and remove the [link to this issue from the README](https://github.com/sindresorhus/ava/blob/f77ded959a0e7de6e9bf65d8c2fd6625bc59ba47/readme.md#transpiling-imported-modules).

**Comment by sindresorhus** [comment]
Not that I'm aware of.

**Comment by vdemedes** [comment]
Sure, we can close it for now.

**Comment by z-vr** [comment]
@Whoaa512 dude you rule
