### ISSUE TITLE
power-assert output fails when using async/await

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#113]
test.js
```js
import test from 'ava';

function foo() {
	return Promise.resolve(true);
}

test('foo', async t => {
	t.plan(1);
	t.ok(await foo() === false);
});
```

output
```
  Error: Line 1: Unexpected identifier
    at Test.<anonymous> (/.../test.js:9:4)
    at step (/.../test.js:5:273)
```

**Comment by jamestalmage** [comment]
I have cross-posted here: https://github.com/power-assert-js/babel-plugin-espower/issues/6

I can't tell which library is causing the error. Please close if you are confident it is the power-assert plugin.

**Comment by twada** [comment]
@jamestalmage Thank you for reporting.
And yes, this is caused by power-assert (Thank you for cross-posting this).

**Comment by twada** [comment]
For now, please avoid using await expression __INSIDE__ assertions.

Doesn't work:
```js
test('foo', async t => {
    t.plan(1);
    t.ok(await foo() === false);
});
```

Would work:
```js
test('foo', async t => {
    t.plan(1);
    const result = await foo();
    t.ok(result === false);
});
```

Sorry for inconvenience, I'll fix it ASAP.

**Comment by jamestalmage** [comment]
Closing since the issue is in power-assert
