### ISSUE TITLE
Upgrade to Babel 6

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#117]
https://babeljs.io/blog/2015/10/29/6.0.0/

We need to enforce Babel 6 (for devs wanting to use local version) as it's incompatible with 5.

**Comment by sindresorhus** [comment]
I think we should defer this for a couple of weeks until Babel 6 settles a bit. I see a lot of issues on the Babel issue tracker that might affect us.

**Comment by twada** [comment]
Just released [babel-plugin-espower 2.0.0](https://github.com/power-assert-js/babel-plugin-espower/blob/master/CHANGELOG.md#200-2015-11-13). Now power-assert works with Babel6!

**Comment by sindresorhus** [comment]
This was resolved in v0.9.0.
