### ISSUE TITLE
Babel caching

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#118]
Should be done after #117.

See: https://github.com/sindresorhus/ava/pull/103#issuecomment-152853138

> Compilation is a lot larger overhead than just reading in a cached file from disk. I do think we can do caching better than Babel itself, though. Mainly using separate cache files for each test file (Babel uses one large file) and a [LRU cache](https://github.com/isaacs/node-lru-cache).

**Comment by sebmck** [comment]
Would be happy to have this in Babel core. Everything is fairly modularised internally so the only file you should need to touch is [here](https://github.com/babel/babel/blob/master/packages/babel-core/src/api/register/cache.js).

**Comment by sindresorhus** [comment]
@sebmck Oh cool. Are you ok with exposing the cache functionality? We're not using the require hook, so we need to be able to access the cache functionality from the Babel API.

**Comment by jamestalmage** [comment]
Caching is in master.
