### ISSUE TITLE
feat: Provide per test "context" that is shared with "beforeEach"

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#122]
Right now `beforeEach` has limited utility in concurrent tests. The following won't work because both tests manipulate a shared variable and run concurrently:

```js  
var obj;

test.beforeEach(t => {
  obj = // ... some verbose setup code.  
  t.end();
});

test('test1', t => {
  // tests with side-affects  on `obj` 

  // sometime later
  t.end();
});

test('test2', t => {
  // tests with side-affects  on `obj` 

  // sometime later
  t.end();
});
```

To address this, I think it would be good to provide a `this` reference that is shared between `beforeEach` and the individual test:

```js  
var globalCount = 1;

test.beforeEach(t => {
  this.count = globalCount;
  globalCount++;
  t.end();
});

test('test1', t => {
  t.plan(1);
  var self = this;
  setTimeout(() => t.is(self.count, 1));
});

test('test2', t => {
  t.plan(1);
  var self = this;
  setTimeout(() => t.is(self.count, 2));
});
```

*The above is maybe not the best example and might fail since I doubt we are guaranteeing test instantiation order in a concurrent testing framework.*

Another alternative might be to pass the context as an optional second arg:

```js
var globalCount = 1;

test.beforeEach((t, ctx) => {
  ctx.count = globalCount;
  globalCount++;
  t.end();
});

test('test1', (t, ctx) => {
  t.plan(1);
  setTimeout(() => t.is(ctx.count, 1));
});

test('test2', (t, ctx) => {
  t.plan(1);
  setTimeout(() => t.is(ctx.count, 2));
});
```

This has the advantage of avoiding `self` reference verbosity.

**Comment by schnittstabil** [comment]
I like the current approach: [t.context](https://github.com/sindresorhus/ava/#before--after-hooks) :smile:

**Comment by jamestalmage** [comment]
CRAP!
How did I miss that?!
