### ISSUE TITLE
Time is not calculated correctly when using a fake clock

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#128]
I use [sinonjs](http://sinonjs.org/) for stubbing and stuff. But also to use a [fake timer](http://sinonjs.org/docs/#clock) that I can manipulate.

When doing this, times are not calculated correctly.

![screen shot 2015-11-04 at 14 51 42](https://cloud.githubusercontent.com/assets/1913805/10939674/96377ab8-8303-11e5-8a87-a1973dfbf7ff.png)

Will have a look at it myself, not sure when though.

**Comment by sindresorhus** [comment]
Everything can be overridden, though. We'll have to save references to every single global with properties if we're going to be able to totally fix this. Crazy idea, maybe we should?

**Comment by vdemedes** [comment]
@SamVerschueren Could you please create a minimal reproducible example and publish it as a gist?

**Comment by SamVerschueren** [comment]
Sure, here you go.

https://gist.github.com/SamVerschueren/ec24a03117021ed561fb

This results in the following output

![screen shot 2015-11-05 at 13 29 53](https://cloud.githubusercontent.com/assets/1913805/10968422/53d0f7f8-83c1-11e5-83ef-6b65ec3cce8b.png)

**Comment by vdemedes** [comment]
Awesome, thank you.

**Comment by SamVerschueren** [comment]
Awesome!
