### ISSUE TITLE
Add test.only()

### ISSUE THREAD

**Issue by unlight** [sindresorhus/ava#132]
I could not find `test.only` in api documentation. Similar to [tape's test.only](https://github.com/substack/tape#testonlyname-cb) or mocha's `it.only`.
Is it exists?

**Comment by vdemedes** [comment]
`test.only` does not exist at the moment. We're having a long discussion on test modifiers at the moment - #9.

**Comment by lijunle** [comment]
+1 on this feature.

I am considering to migrate from mocha to AVA. However, keep easy test failure debug experience is one of my concerns - `test.only` is the key to do so.

**Comment by sindresorhus** [comment]
:+1: We plan to add this. Help welcome as we have a lot of other things to deal with right now.

**Comment by vdemedes** [comment]
Closing via #204.
