### ISSUE TITLE
Feature request: Shorthand for synchronous tests

### ISSUE THREAD

**Issue by af** [sindresorhus/ava#133]
Ava looks great, and I'm tempted to switch some projects from `tape` to it. There's one thing that really bugs me though, and it's the same with `tape`:

```
test(t => {
    t.same([1, 2], [1, 2]);
    t.end();
});
```

In purely synchronous tests like this, the `t.end()` is boilerplate that really serves no purpose. `t.plan(n)` is even worse for sync tests because you have to constantly update it when you add more assertions. I'd love to see a sync shorthand form like this supported:

```
test.sync(t => {
    t.same([1, 2], [1, 2]);
});
```

Are you open to adding something like that?

**Comment by sindresorhus** [comment]
Not sure about this. You only save 3 characters. I'll think about it.

-

In hindsight `test()` should have been purely sync and async would be activated by using an async function. That would have been so much cleaner.

**Comment by SamVerschueren** [comment]
Actually, this is possible by "abusing" `async` :).

```js
test(async t => {
    t.same([1, 2], [1, 2]);
});
```

**Comment by af** [comment]
It's a young project, pre-1.0, so it's not too late :)

IMO it helps for readability/comprehension to show that the test should be fully synchronous. It's not so much about saving characters (although that's nice), more to display the intent of the code more clearly, without any unnecessary elements.

**Comment by SamVerschueren** [comment]
If all tests where written in ES2015, `t.end` could be dropped entirely. Either they are sync

```js
test(t => {
    t.same([1, 2], [1, 2]);
});
```

or they are async

```js
test(async t => {
    t.same([1, 2], [1, 2]);
});
```

But I guess lot's of people are still using callbacks which makes `t.end` necessary. We can't force them to use promises, right? :)

**Comment by vdemedes** [comment]
I think this will introduce more garbage in the `lib/test.js` and confusion about what to do (`test.sync` or `t.plan` or `t.end`) among AVA starters.

`.sync` is 5 characters, `t.end();` is 7 characters. So it's not really a shorthand, imo.

**Comment by sindresorhus** [comment]
@vdemedes Actually, a benefit with it is that it has clearer intent, and I've many times forgotten the `t.end()`...

**Comment by af** [comment]
100%. This is not about saving characters (the initial issue description overemphasized this, I think). It's about signalling intent.

**Comment by taylorhakes** [comment]
I definitely prefer `test.sync` because of intent (with named export), but I feel I will be using `test.sync` on 90% of my tests. As @sindresorhus said, for me, it would have been really nice if sync was the default. 

Any chance sync by default could happen with `test.async` for async tests? I know that would be a huge breaking change, but I plan to use this library for a while and it will save so many keystrokes over time.

If not, it would be great to be used like this.
```
import { sync } from 'ava';

sync('foo', t => {
  t.same(['a', 'b'], ['a', 'b']);
});
```

**Comment by af** [comment]
Agreed @taylorhakes, that would be the idea solution from my perspective as well. Obviously a big breaking change though!

**Comment by jamestalmage** [comment]
We have consensus in #244, and a proposed implementation in #253.
I will leave #244 open until we merge a solution. Closing this now.
