### ISSUE TITLE
Properly handle forked processes that exit without any tests / sending results.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#137]
This is a tracking issue for the discussion started in #136.

The relevant comment:

> Does `ava` already warn if a test file has no tests? (i.e. passCount === 0)?
>
>I would think that should be a failure, otherwise putting:
>
>```js
>process.exit(0); 
>```
>at the top of your test makes it pass. (contrived I know).
>
>Should we be warning if the process exits with code `0`, but never sends a result message?

**Comment by vdemedes** [comment]
In my opinion, AVA shouldn't exit with failure, if there were no tests in a file. There was no failure, so why indicate the failure?

**Comment by vdemedes** [comment]
I think just a friendly warning message, that there were no tests defined would be good.

**Comment by jamestalmage** [comment]
The child process should always send a `results` message though right? Even if it had zero tests?

My point is that if the process exits without sending the `results` message, then something happened that prevented `ava` from sending it. That is out of the ordinary and should be an error.

If there are no tests in a file, and ava sends a result `testCount: 0`, that's fine (give the friendly warning and be done).

**Comment by vdemedes** [comment]
> The child process should always send a results message though right? Even if it had zero tests?

Yes, and according to `index.js` it should work now that way. Need to confirm this.

> My point is that if the process exits without sending the results message, then something happened that prevented ava from sending it. That is out of the ordinary and should be an error.

That is correct, an error should be displayed in that case. But this issue is about files with zero tests, so it's unrelated here.

**Comment by jamestalmage** [comment]
Closed via: https://github.com/sindresorhus/ava/commit/97409864e2f2f3ed103b13ae6602cad4744a6815
