### ISSUE TITLE
Looking to help out

### ISSUE THREAD

**Issue by markthethomas** [sindresorhus/ava#138]
Would love to help out with this project; are there any major areas of need or places I should get started? Was looking through some of the open issues but wanted to check here, too. Thanks! :+1:

**Comment by sindresorhus** [comment]
We could definitely use some help! At the moment, what we could really use are good opinions on the various open issues. We're trying to figure out the fundamentals as fast as possible and more opinions help us make the right choices.

As for code contributions, I've added a [`good for beginner`](https://github.com/sindresorhus/ava/labels/good%20for%20beginner) label, but we don't really have many issues yet that are very easy. If you're ready to dig in, we do have some that are not too hard: #128 #102 #84.

I'm gonna keep this issue open for a while as this applies to anyone looking to contribute. Feel free to ask here about anything. We would be happy to tutor anyone and answer questions about the code base. No contribution is too minor. Documentation improvements are the best contributions we get, as we all know, docs can always be better → https://github.com/sindresorhus/ava/issues/160.

We have a [Gitter chat](https://gitter.im/sindresorhus/ava). Come and lurk! ;)

-

*Sorry about the late answer. Had to deal with a lot of urgent issues and I'm currently traveling.*

**Comment by markthethomas** [comment]
@sindresorhus thanks so much for getting back to me! You've given me a great base for starting out. I'll check out some of those issues you mentioned and ask any questions I have here! Thanks, too, for the thorough response — I'm looking to get more and better involved with OSS and the best way I can do that I think is by learning and contributing to one project well first :+1:

**Comment by sindresorhus** [comment]
@vdemedes I'd like to keep this open for visibility for anyone looking to contribute.

**Comment by sindresorhus** [comment]
Closing this now that we have comprehensive contributing guidelines :)
