### ISSUE TITLE
Context set in beforeEach is not available in tests

### ISSUE THREAD

**Issue by ArtemGovorov** [sindresorhus/ava#139]
Test file:
``` JavaScript
import test from 'ava';

test.beforeEach(t => {
  t.context = 'unicorn';
  t.end();
});

test(t => {
  t.is(t.context, 'unicorn');
  t.end();
});
```

Result:
```
 ✔ [anonymous]
  ✖ [anonymous] undefined === 'unicorn'
```

**Comment by vdemedes** [comment]
Copy-pasted your code and ran with ava#master:

<img width="202" alt="screen shot 2015-11-06 at 10 36 44 am" src="https://cloud.githubusercontent.com/assets/697676/10993832/4d3174fc-8472-11e5-9984-c0c20b93c119.png">

Are you using master branch or installing via npm?

**Comment by ArtemGovorov** [comment]
npm

**Comment by vdemedes** [comment]
There were some changes in the way we set context after the release (I think), so as I see, this issue is resolved in master.

**Comment by ArtemGovorov** [comment]
Ok, thanks for the update!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ava/releases/tag/v0.4.0
