### ISSUE TITLE
assert API design

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/ava#142]
I've just found out that the `error` argument of `.throws` is not optional
> .throws(function|promise, error, [message])

and that `.regexTest` is not consistent with the rest of the assertions:
> .regexTest(regex, contents, [message])

because of its parameter order (all other assertions follow the basic scheme `(actual, expected, message)`).

I'm not sure if these were intended…

**Comment by vdemedes** [comment]
Could you please attach some code to both of these?

I just tested the first one and it works as expected, even when I don't set `error` argument:

```js
import test from '.';

test(t => {
		t.throws(function () {
			throw new Error('damn it');
		});

		t.throws(Promise.reject(new Error('damn it')));

		t.end();
});
```

**Comment by schnittstabil** [comment]
@vdemedes That is true, it works but:
1. it is not documented, so the behavior might change 
2. `.throws(function|promise [, error][, message])` currently does not work as expected with #125:

```js
test(t => {
	t.throws(()=>{}, 'some message');
	t.end();
});
```

Before #125:
```
  ✖ [anonymous] Missing expected exception. some message

  1 test failed

  1. [anonymous]
  AssertionError: Missing expected exception. some message
    at Test.fn (/home/patrick/Projekte/github/merge-options/t.js:4:4)
```

After:
```
  ✖ [anonymous] Missing expected exception..

  1 test failed
```

About `.regexTest`:
```js
t.is('actual', 'expected');
t.regexTest(/expected/, 'actual');
```

**Comment by SamVerschueren** [comment]
Then the notation should be something like this

`.throws(function|promise [, error [, message]])`

**Comment by schnittstabil** [comment]
@SamVerschueren That is possible and I would recommend that, even though switching from [assert.throws](https://nodejs.org/api/assert.html#assert_assert_throws_block_error_message)  is no longer so simple.

**Comment by SamVerschueren** [comment]
This is mentioned by @sindresorhus a couple of times, as well in #125.

> We only use the core assert so not to duplicate code. If anything can be done better, we'll do it. Also the core Node.js people have said assert is done and won't change anymore.

That assertion module is not a binding contract. That's also the reason why AVA isn't using the same names as the `assert` library, to abstract away the implementation.

**Comment by schnittstabil** [comment]
@SamVerschueren I knew that and I like #125, the problem is, in contrast to most assertions in AVA, the name (`throws`) is the same and developers who switch to AVA may experience unexpected hard to grasp behavior.

Maybe we should introduce our own *throws* assertions with a different name, in particular, because nodes `throws` and `doesNotThrow` suffer from many problems:

```js
try {
	assert.throws(()=>{ throw new Error('abc')}, TypeError);
} catch (err) {
	console.log(err instanceof assert.AssertionError);
	//=> false
	console.log(err.message);
	//=> 'abc'

	// I would expect something like: 
	console.log(err.message);
	//=>'Missing expected TypeError. Got unwanted exception Error('abc').'
}
```

**Comment by SamVerschueren** [comment]
Not sure about a name change, `throws` seems the shortest and most explanatory name for this. Something like `t.exception` doesn't feels right.

IMO people should read the docs, and I understand that some of them might think it has the same syntax, but then again, `RTFM?` ;).

I guess @sindresorhus would be happy to give his thoughts on this.

**Comment by schnittstabil** [comment]
I think of more powerful assertions, maybe with different parameters. As this would also support Promises, `rejects` seem reasonable.

**Comment by SamVerschueren** [comment]
`raises` seems more appropriate.

If we go for a name change, I would not keep `throws`. It will confuse people because it has two methods that are almost identical, just to be consistent with `assert`. Again, that is not the intention of AVA (but I guess you already know :)).

It's certainly not up to me to make this decisions.

**Comment by vdemedes** [comment]
Oh no, let's not change the name of `throws()`. `rejects` looks like it supports only promises and `raises` is from Ruby.

All we have to do, is to fix & stabilize issues pointed out in the first comment.

**Comment by sindresorhus** [comment]
I would prefer not to change the name of `.throws`. A lot of things will differ from the core `assert` module. Even more when we evolve further. I think we should rather fix the issues mentioned here and document clearly that the API is not core `assert` compatible.

As for `regexTest`, that unfortunate, but honestly, do we even need it now that we have `power-assert`? `t.true(/foobar/.test(foo));` would be just as good with the excellent output of `power-assert`.

**Comment by sindresorhus** [comment]
> As for regexTest, that unfortunate, but honestly, do we even need it now that we have power-assert?

Thoughts on deprecating `regexTest`?

**Comment by sindresorhus** [comment]
@jamestalmage

**Comment by vdemedes** [comment]
@sindresorhus I'd leave it, but rename to just `t.regex`. To me it looks a bit more convenient (less nesting of statements):

```js
t.regex(/ok/, 'oh ok');
t.true(/ok/.test('oh ok'));
```

**Comment by SamVerschueren** [comment]
I'm with @vdemedes on this one. Would leave it as well.

**Comment by sindresorhus** [comment]
@vdemedes But the current one has the wrong argument order. I suggest we deprecate `regexTest` and add `regex` with the correct argument order then. Unless anyone has a better idea.

```js
t.regex('oh ok', /ok/);
```

**Comment by vdemedes** [comment]
@sindresorhus oh, in that case, definitely, `regexTest` should be deprecated and correct `regex` should be implemented.

**Comment by twada** [comment]
In my opinion, reducing APIs that are easy to make mistakes is the most valuable point of power-assert.

So I'm :+1:  on
`t.true(/ok/.test('oh ok'));`

(But for this purpose I must [improve output depth of SuccinctRenderer](https://github.com/twada/power-assert-renderers/issues/3)! )

**Comment by kasperlewau** [comment]
Is `t.regex` still on the table or do we resort to using `t.true` with an explicit regex.test? I'd love to contribute to the cause, got the necessary changes stashed and ready for tomorrows commute!

Oh and do excuse the potential necro. Just scouring through the `help wanted` issues.

**Comment by jamestalmage** [comment]
It is still on the table. Go for it!

**Comment by kasperlewau** [comment]
> It is still on the table. Go for it!

Commuting tomorrow morning is gon' be fun, cheers! : )
