### ISSUE TITLE
gulp-ava error: process.send is not a function

### ISSUE THREAD

**Issue by Ivan-Feofanov** [sindresorhus/ava#143]
When using gulp-ava get error:

[14:54:30] Using gulpfile ~/work/ctx-ava/gulpfile.js
[14:54:30] Starting 'test-ava'...
[14:54:31] 'test-ava' errored after 875 ms
[14:54:31] Error in plugin 'gulp-ava'
Message:
    Command failed: /home/feofanov/work/ctx-ava/node_modules/gulp-ava/node_modules/.bin/ava /home/feofanov/work/ctx-ava/test/test/ava/test.js --color
TypeError: process.send is not a function

From CLI ava works fine

**Comment by vdemedes** [comment]
What gulp-ava version are you using?

**Comment by Ivan-Feofanov** [comment]
0.2.0

**Comment by vdemedes** [comment]
Just tried gulp-ava@0.2.0 with an official example (https://github.com/sindresorhus/gulp-ava) and it works. I assume you linked some future version of AVA into your directory.

**Comment by Ivan-Feofanov** [comment]
I use ava 0.3.0

**Comment by vdemedes** [comment]
I just realized we are in ava repository, not gulp-ava. So, this is unclear why it's failing now. Could you please prepare a set of steps to reproduce your error and open this issue over at https://github.com/sindresorhus/gulp-ava? Thanks.
