### ISSUE TITLE
FAQ misconceptions

### ISSUE THREAD

**Issue by boneskull** [sindresorhus/ava#145]
1. Mocha does not require `describe`, etc to be in the global namespace; the default interface (`bdd`) does, however. It is one interface amongst several. 

2. Mocha provides TAP output as an available reporter but is not otherwise tightly bound to TAP. 

1) is a common misconception, but I'm not sure where 2) came from. 

Addressing bloat and performance are two issues on Mocha's radar. Would appreciate any suggestions or assistance!

Thanks. Looks pretty cool :+1:

**Comment by boneskull** [comment]
3. Is not supposed to be in the list and instead refers to point 1. Sorry on mobile

**Comment by boneskull** [comment]
3) dammit

**Comment by sindresorhus** [comment]
Ok, I've clarified it in the readme, but the reality is that most people just use the default interface. The TAP part is regarding node-tap/tape, not Mocha. Feel free to do a PR if you think anything else could be said better or something. I'm not trying to bash on Mocha. Just my opinion on it. I was a happy user for a long time.

**Comment by boneskull** [comment]
Thanks.  I don't expect everyone to be in love with Mocha; it has some fundamental flaws that need addressing.  If we end up stealing some of your ideas, please consider it flattery. :smile:

**Comment by sindresorhus** [comment]
Please do. I would like to see Mocha improve too. AVA is not for everyone. Most will continue using Mocha. I'm just trying to move testing forward for everyone :)
