### ISSUE TITLE
Can't upgrade to Babel 6 

### ISSUE THREAD

**Issue by FuzzOli87** [sindresorhus/ava#149]
I tried to install the latest Babel 6 since I'm starting a new project. When I installed the latest Babel to my devDependencies the two simple test kept failing. So I removed them from my devDependencies and it worked. I wrote my actual tests now and well, I need Babel to run my code. 

Is it normal behavior to break AVA if I install the the updated Babel to my devDependencies?

**Comment by sindresorhus** [comment]
We don't support Babel 6 yet: https://github.com/sindresorhus/ava/issues/117
