### ISSUE TITLE
Emit error when there are more assertions than planned

### ISSUE THREAD

**Issue by kevva** [sindresorhus/ava#15]
Currently we aren't keeping track of all the pending assertions. `tape` is using this https://github.com/substack/tape/blob/master/lib/test.js#L174-L181.

**Comment by mdibaiee** [comment]
We do emit an error when the assertion count doesn't match planned. Why do we need the `_pendingAsserts` in the first place?

I have probably misunderstood this bug, can you please clarify? @kevva

**Comment by sindresorhus** [comment]
@mdibaiee I think it's related to this: https://github.com/sindresorhus/ava/blob/ff5eebba5d06ea22a1ed1ca5f76f33386bee8381/test/test.js#L245-L247

**Comment by mdibaiee** [comment]
@sindresorhus: I see, I'll take a look to see if I can fix this when I get some free time.

**Comment by Qix-** [comment]
If I'm understanding this correctly, the way I've seen it done before is even if `t.end()` has been called and the test passed, an assertion called after that point will re-show the test as failed. You don't need to know the point of last assertion, and you will *never* know thanks to the halting problem.

**Comment by sindresorhus** [comment]
@mdibaiee Did you have a chance to look into it? No worries if not :)

**Comment by mdibaiee** [comment]
@sindresorhus: Hey, sorry I had forgot about this, busy on a few projects.

I took a look, couldn't find a solution, it *might* be possible if we have a timeout, but then, we can't just wait for the timeout to pass for every test only because it might be doing something wrong.

A funny idea hit my head! Inspecting the test body's code, searching for `<first-argument>.assert` and similar method calls :laughing:

**Comment by Qix-** [comment]
> A funny idea hit my head! Inspecting the test body's code, searching for <first-argument>.assert and similar method calls :laughing:

Going to assume that was a joke :sos: 

---

If things are blocking and async functions are still at play, node won't terminate. You don't have to wait for anything unless it's a faulty test.

**Comment by mdibaiee** [comment]
@Qix- yeah that was a joke.

How can we know if there are async functions still in progress? I tried calling `process._getActiveHandles()` and `process._getActiveRequests()` but these functions seem to only work for IO handles/requests.

**Comment by Qix-** [comment]
Because node won't terminate unless they're done executing.
