### ISSUE TITLE
No longer working on Node.js 0.10

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#154]
Not sure why the tests didn't catch this.

```js
// test.js
import test from 'ava';

test(t => {
	t.pass();
	t.end();
});
```

```
❯ node -v
v0.10.40

❯ ava test.js

TypeError: Cannot read property 'stack' of undefined
    at error (/usr/local/lib/node_modules/ava/cli.js:51:19)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/ava/cli.js:218:34)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

// @floatdrop

**Comment by floatdrop** [comment]
@sindresorhus most likely, because [this line](https://github.com/sindresorhus/ava/blob/master/lib/fork.js#L36) rejects to `undefined` and `cli` trys to get `stack` from `undefined`.

**Comment by sindresorhus** [comment]
Yup, but I'm unsure why. That test should pass, but it's rejecting somehow.

**Comment by floatdrop** [comment]
@sindresorhus probably because we [kill](https://github.com/sindresorhus/ava/blob/master/lib/fork.js#L29) process after all tests are done - and sometimes Node.js 0.10 will return `SIGTERM` exit code (143) which is trigger `error` handler.

**Comment by jamestalmage** [comment]
Should we be sending a different kill signal?

https://nodejs.org/api/process.html#process_signal_events

> * SIGTERM and SIGINT have default handlers on non-Windows platforms that resets the terminal mode before exiting with code 128 + signal number. If one of these signals has a listener installed, its default behaviour will be removed (node will no longer exit).
> * SIGPIPE is ignored by default, it can have a listener installed.
> * SIGHUP is generated on Windows when the console window is closed, and on other platforms under various similar conditions, see signal(7). It can have a listener installed, however node will be unconditionally terminated by Windows about 10 seconds later. On non-Windows platforms, the default behaviour of SIGHUP is to terminate node, but once a listener has been installed its default behaviour will be removed.
> * SIGTERM is not supported on Windows, it can be listened on.
> * SIGINT from the terminal is supported on all platforms, and can usually be generated with CTRL+C (though this may be configurable). It is not generated when terminal raw mode is enabled.
> * SIGBREAK is delivered on Windows when CTRL+BREAK is pressed, on non-Windows platforms it can be listened on, but there is no way to send or generate it.


Maybe the forks should just be in charge of terminating themselves.
