### ISSUE TITLE
Allow babel transpilation of test helper files.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#156]
We are doing all this work to ensure babel does not leak into any file but the test file, but there is a downside for "helper" files, etc.

The other option would be to hook require and make them provide some sort of `include` / `exclude` glob.

**Comment by sindresorhus** [comment]
Why did you close?

**Comment by jamestalmage** [comment]
Didn't mean to.

**Comment by sindresorhus** [comment]
I'm open to it, as it would be very nice to be able to use ES2015 stuff in test helper files too. I think a `whitelist` would be better so we could still make use of the ES2015 `import` semantics.

**Comment by SamVerschueren** [comment]
Would be very nice indeed! Maybe use something like `.es6.js` as extension? This way you don't need to update the whitelist.

**Comment by jamestalmage** [comment]
Or just default the whitelist to include `test/_*`, since the underscore prefix is already set aside to denote helpers. 

Or just everything in the `test` directory? Event `test/fixtures/**`?

**Comment by sindresorhus** [comment]
@jamestalmage I think defaulting the whitelist to `test/_*` is a good idea, not so sure about the whole test directory, though. I would definitely not want my fixtures implicitly transpiled.

**Comment by jamestalmage** [comment]
Thats my feeling as well.

**Comment by just-boris** [comment]
+1, I want this thing too. But why do you need all that stuff around `require-from-string`?

Why not just add babel hook using `require("babel-core/register");`?

**Comment by jamestalmage** [comment]
Because, one goal of this library is not to pollute any of your production code with babel transforms/polyfills (unless you specifically ask it to).

**Comment by just-boris** [comment]
But all my source code is written for babel too. Will there an option to transpile files from my `src/` folder in addition to `test/`?

**Comment by sparty02** [comment]
> Because, one goal of this library is not to pollute any of your production code with babel transforms/polyfills (unless you specifically ask it to).

I actually want my source code (non-test) to be transpiled by babel as well..... i.e. I want to be able to ```import``` a module that is written in ES6 into my ava test module.  Is there a suggested technique for this today?  Or is this a pending enhancement?

**Comment by sindresorhus** [comment]
@sparty02 Pending enhancement. Definitely something we want to support, but haven't had the chance yet. See https://github.com/sindresorhus/ava/issues/111. Any thoughts there much appreciated.

**Comment by sparty02** [comment]
@sindresorhus  ahh.... thanks for the reference to #111.  I'll take a look!

**Comment by vdemedes** [comment]
Closing this issue as it's already implemented.
