### ISSUE TITLE
SyntaxErorr When Module Contains Import Statement

### ISSUE THREAD

**Issue by alexbooker** [sindresorhus/ava#170]
### Problem

When a module contains an ES2015 [import statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) I get a `SyntaxError`:

```bash
ava test.js 

/home/booker/Code/ava-test/index.js:1
(function (exports, require, module, __filename, __dirname) { import _ from "lodash";
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
```

### How to reproduce
```
nvm use 5.0.0
npm install -g ava
npm install ava
npm install lodash
```

`index.js`:

```
import _ from "lodash";
```

`test.js`

```
import test from 'ava';
import sut from "./";
```

```
ava
```

**Comment by sindresorhus** [comment]
AVA doesn't transpile your code, only your test file.

You probably want https://github.com/sindresorhus/ava/issues/111.

**Comment by alexbooker** [comment]
Thanks, @sindresorhus. I'll look into that now.
