### ISSUE TITLE
Problems with Relative Paths and Tests

### ISSUE THREAD

**Issue by alexbooker** [sindresorhus/ava#175]
I am using the [config](https://github.com/lorenwest/node-config) module to load configuration files in my Node app.

config looks for a dir called `./config` relative to the _current working dir_. 

When running tests via AVA, the current working directory is the location of the tests. This causes _config_ to look in the wrong place for the `./config` dir. (I think this is due to the way AVA spawns processes. )

To work around this I use an environment variable recognized by _config_ to change the `./config` dir location when running tests:

    NODE_ENV=test NODE_CONFIG_DIR=../../config ava test/**/*.js

This is pretty teampramental, though - some test files are nested differently to others. What's more, some modules look for files relative to `process.cwd()` by default. In some cases, I can configure that but I think it is going to be very tedious to do.

How should I work around this if I want to use AVA?

**Comment by vdemedes** [comment]
Could you please post a few lines of your code?

Related: #32

**Comment by MarkHerhold** [comment]
I hit the exact same issue with AVA.

**Comment by sindresorhus** [comment]
@MarkHerhold Read #32 for context of why it's like it is. I'm surprised the `config` module doesn't just find the upwards closest config file.

**Comment by MarkHerhold** [comment]
@sindresorhus OK, that is fine. This is a major turn-off in terms of adoption of AVA. (https://github.com/sindresorhus/ava/issues/222 does not help either). I looks like the config module lets me define an environment variable called `NODE_CONFIG_DIR` which should solve the problem. I don't like the idea that my application runs from a different working directory during test as compared to development and production though as it could cause some really nasty and hard to detect bugs.

**Comment by jamestalmage** [comment]
@MarkHerhold 

Currently, the best workaround for achieving the behavior you desire is:

```
NODE_ENV=test NODE_CONFIG_DIR=$(pwd) ava test/**/*.js
```

At the top of every test:

```js
process.cwd(process.env.NODE_CONFIG_DIR);
```

@sindresorhus @vdemedes  - Do we want to add a flag or environment variable to address this?

**Comment by novemberborn** [comment]
@jamestalmage,

> Do we want to add a flag or environment variable to address this?

You mean to change the effective working directory of the test files?

I think generally code should walk up the directory tree looking for the file it wants, or otherwise resolve relative to the `package.json` (which it needs to find by walking up the tree…). I don't think AVA should change it's behavior.

Closing this now given the lack of discussion over the past three months.

**Comment by KidkArolis** [comment]
I ran into this same issue just now. In my mocha tests I always have a mocha.opts `--require test/setup` config, where in the `test/setup.js` I could set things such as my NODE_ENV and NODE_CONFIG_DIR. I can't do the same in `ava` using the `ava.require` pkg.json config because those get required relatively to each test file...

I wish there was a way to solve this, so that I could just run `ava` to run my tests without an additional `npm script` or `makefile` wrapper. Hmm.

**Comment by KidkArolis** [comment]
I suppose in the spirit of being able to just run `node foo/test.js`, each test file could do a `require('../_setup')`.

On the other hand, that already doesn't work cause babel and `ava` settings in package.json such as `ava.require`. So if there was a way of prerequiring a module for each test that is local to the project, that'd be great.

**Comment by KidkArolis** [comment]
Made this for now if anyone else runs into this issue.. https://www.npmjs.com/package/ava-config

I can also rename the pkg if `ava` folk think the name is too confusing.

**Comment by sindresorhus** [comment]
`config-ava` would have been clearer. Now it sounds like it's a config package used internally by AVA, not a AVA version of the `config` package.

**Comment by jamestalmage** [comment]
It might be good to make the same request of the community that other projects do. Save the `ava-` prefix for AVA internal packages (and maybe plugins down the road) and instead use an `-ava` suffix.

**Comment by sindresorhus** [comment]
Yup. Maybe mention it somewhere in the readme.
