### ISSUE TITLE
How does this compare to Magellan?

### ISSUE THREAD

**Issue by mattfysh** [sindresorhus/ava#176]
How would you compare ava to https://github.com/testarmada/magellan - is ava for paralellizing unit tests versus magellan for functional, selenium-powered tests? Are there any plans (or how easy would it be) to extend ava to support port management, https://github.com/FormidableLabs/rowdy, etc..?
thanks!!

**Comment by markthethomas** [comment]
Not sure if I'm fully understanding the question, but ava is a library more akin to tape/mocha and is built for unit testing, while magellan looks like it's more of an integration suite for browser testing. Is that what you're getting at? If so, these are different libs for different testing types and at least as far as I know there aren't plans to move ava in the integration direction :) happy for anyone else to chime in though, I'm pretty new to watching/helping w/ava

**Comment by mattfysh** [comment]
I see... it sounds like this is a test framework with parallelization built-in as a feature, as opposed to a parallelization framework that works to parallelize test suites written in other frameworks (mocha, jasmine, etc)?

**Comment by markthethomas** [comment]
@mattfysh pretty much, yeah — parallelization is *a* feature, not *the* feature. I suppose you *could* use the runner to run other tests, but really then you're creating a modified version of the gorilla-banana problem with no extra inherent benefit :)

![cdijaprwmaawk3i](https://cloud.githubusercontent.com/assets/4926721/11044841/166de6f8-86d9-11e5-8dcd-6a8c0e0644eb.png)

**Comment by vdemedes** [comment]
@markthethomas gave a good answer on this one, I think it's safe to close.

@mattfysh If you have some questions regarding AVA, feel free to chat in our [gitter room](https://gitter.im/sindresorhus/ava?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
