### ISSUE TITLE
Default reporter

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#18]
I think the default reporter should be super minimal one. It should only log out detailed test info if a test fails, otherwise just `1 test passed`.

It could have a live counter, so while tests are running the line is dynamically updated with `3/12 tests passed`, and when done rewritten to be `12 tests passed`. That way it can be live, but also minimal.

Can use [log-update](https://github.com/sindresorhus/log-update).

**Comment by SamVerschueren** [comment]
Agree on this one, but should be implemented after https://github.com/sindresorhus/ava/issues/27 I guess. If people want the full blown output, they can then enable another reporter.

**Comment by vdemedes** [comment]
Yeah, reporters are an important feature to implement. But I think we're not "there" yet, there are some issues that have a much higher priority.

But once those are resolved, I am 100% on board with implementing custom reporters.

**Comment by vdemedes** [comment]
@sindresorhus do you still want to work on this? I'd like to assign this to myself :)

**Comment by sindresorhus** [comment]
Go ahead ;)

**Comment by alubbe** [comment]
Just some quick feedback from an early user that it would be awesome to have custom reporters :)

**Comment by sindresorhus** [comment]
@alubbe That will come when we add TAP support #27. You can then use any [TAP-reporter](https://github.com/substack/tape#pretty-reporters).

**Comment by alubbe** [comment]
Awesome, I just hope that the concurrency doesn't end up posing a problem for TAP.

**Comment by jamestalmage** [comment]
We likely will have to buffer and output one whole test at a time.

**Comment by vdemedes** [comment]
What do you think about this?

![demo](https://cloud.githubusercontent.com/assets/697676/11963521/30e79bb2-a8f0-11e5-851a-a54f195aba9b.gif)

**Comment by sindresorhus** [comment]
@vdemedes :heart: Exactly what I was thinking.

**Comment by jamestalmage** [comment]
:+1:

**Comment by SamVerschueren** [comment]
:+1:

**Comment by ariporad** [comment]
:+1:
