### ISSUE TITLE
Avoid loading babel in forked processes.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#182]
We are paying a hefty penalty to load Babel once per forked process.

I have played around with a way to share one Babel instances across every forked process (though it does not necessarily need to be limited to a single instance).

https://github.com/jamestalmage/__share_transpile_across_process

With some very naive benchmarks I am seeing < 3 seconds using this method compared to > 16 loading up a Babel instance per fork.

**Comment by floatdrop** [comment]
@jamestalmage thought of this too. We can transpile files with babel in master process and load transpiled code from cache (as soon as I deal with #118).

**Comment by sindresorhus** [comment]
That's a cool idea. I like it.

**Comment by jamestalmage** [comment]
What is your plan for the cache? Write it all to disk before launching forks?

I'm actually firing up an http server and then using `child_process.execSync('cur', ...)` to fetch the transpiled code.

**Comment by jamestalmage** [comment]
The major problem there is that it requires actually forking an entirely new process for every fetch, which is not free. Using a direct execution of `curl` vs forking another node process is way better, but still not great.

For the initial test file, we could use IPC (maybe even do static analysis of the Babel AST to find additional require calls).

Dynamic requires will be a problem. That is where I think my strategy will help. If somebody does a lot of dynamic calls there is even a chance my strategy may hurt, so we probably need a way for people to turn it off.

**Comment by floatdrop** [comment]
@jamestalmage yes, but do it step by step (transpile one test and launch it), not all at once.

**Comment by jamestalmage** [comment]
Gotcha.
Seems reasonable.

**Comment by jamestalmage** [comment]
@sindresorhus We need a good real-world library to performance test this against. I know pageres is mentioned in the readme, but given the nature of that project (I am just guessing), that a lot of time is spent on I/O. Is there one with a high test-file count where I/O is minimal (where improvements to the load time of AVA forks would be most noticeable).

**Comment by sindresorhus** [comment]
@jamestalmage https://github.com/sindresorhus/got has a lot of tests and uses a local server for most, so the tests are pretty fast.

**Comment by vdemedes** [comment]
Really good idea! Well done @jamestalmage

**Comment by jamestalmage** [comment]
This was fixed in ~`0.10.0`
