### ISSUE TITLE
Why not write `lib` in ES6 and transpile in a post install script?

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#184]
A lot of libraries ship a `dist` folder of transpiled files to avoid having `babel-core` as a dependency (keeping it only as a dev dependency). I have never liked that, since it makes linking to hot-fixes troublesome (you need to to create an additional commit that includes the transpiled `dist` folder, which messes with your PR).

In our case, we are already downloading `babel-core` as a dependency. It would be fairly trivial to transpile our stuff with a postinstall script or on first run.

**Comment by vdemedes** [comment]
Babel changes constantly, we can't publish source code and hope that after `npm install` code will be successfully transpiled and work fine. Also, when we want to test AVA on 0.10 and 0.12, we'll need to transpile that code before running the tests.

The most important concern is: what benefits could writing the code in ES6 bring to AVA?

**Comment by sindresorhus** [comment]
Hah, no way ;P Transpiling on `postinstall` is so bad. Lots of CoffeeScript projects do that and I absolutely hate it. I'm not totally against writing AVA in ES2015, but it should be `prepublish` step, and I don't think we should use our resources on that right now. We can rewrite in ES2015 at a later time when AVA is more stable. Rewriting something when it's actively developed is a very popular doom fallacy.

> you need to to create an additional commit that includes the transpiled dist folder

Only if you commit `dist`. The common pattern is to transpile in the `prepublish` npm run script hook. Like: https://github.com/sindresorhus/pageres/blob/28dd9b3004c05470202f02e0ac0d0ee148a63768/package.json#L17

**Comment by jamestalmage** [comment]
You do need to commit the transpiled dist if you want to temporarily rely on your hotfix:

```
  $ npm install -S jamestalmage/somerepo#somebranch
```

You would need to have `dist` published in `somebranch`.

The brittle install is sufficient argument against.

**Comment by sindresorhus** [comment]
> You do need to commit the transpiled dist if you want to temporarily rely on your hotfix

Not really. You can just publish it as a scoped package under your username namespace.

https://docs.npmjs.com/getting-started/scoped-packages

**Comment by jamestalmage** [comment]
yeah, I thought of that.

It would be cool if `npm publish` had a `--scoped` that allowed you to do that without modifying package.json

**Comment by kentcdodds** [comment]
Sorry to chime in here, but I'm looking around at issues looking for something else and noticed this. Another solution to address:

> You do need to commit the transpiled dist if you want to temporarily rely on your hotfix

Is there any reason you couldn't just publish a temporary release with `npm publish --tag beta`? [docs](https://docs.npmjs.com/cli/publish)

**Comment by jamestalmage** [comment]
That requires ownership of the module being deployed. I have been added as a collaborator since making that comment, so it's moot for me in the AVA context, but still applicable to any module you don't own.

I filed [this proposal with npm](https://github.com/npm/npm/issues/11001). The gist is that I think there should be an easy way to deploy hot fixes for projects you don't own (under your own namespace).

**Comment by kentcdodds** [comment]
Ah, missed your use case there. Makes sense. And The scoped package is a good work around until your proposal is dealt with. :+1:

**Comment by jedwards1211** [comment]
The one thing that disappoints me about transpiling in `prepublish` is I have to transpile for the lowest common denominator, i.e. `babel-preset-es2015`.  If you transpile in a `postinstall` you could use `babel-preset-es2015-node` to get the most optimized transpilation for the user's version of node.  But I agree there are to many other problems with transpiling during `postinstall`.

But I guess I could publish transpilations for node 4, 5, and 6 though and have a bit of extra code to automatically select the right version based on the node version.
