### ISSUE TITLE
Consider a way to support/add equalJSX method

### ISSUE THREAD

**Issue by MoOx** [sindresorhus/ava#186]
I am currently using tape and I am considering switching to AVA.
There is just one piece missing atm: https://github.com/atabel/tape-jsx-equals
As you can see `tape-jsx-equals` use `extend-tape` to extends tape.
Are you open to add support of equalJSX in the core? If not will it be possible to provide a way to easily extends AVA?

**Comment by MoOx** [comment]
Note: this is assertion is doable using https://github.com/algolia/react-element-to-jsx-string

**Comment by MoOx** [comment]
Also please note that another method is really handy when testing react component: `includeJSX`. This one ignore whitespace differences which can be very handy.

**Comment by jamestalmage** [comment]
@MoOx The ability to add custom assertions is on the roadmap.

**Comment by sindresorhus** [comment]
You can already use any custom assertion. The only minus is that assertion counting doesn't work. We plan to add support for adding custom assertions, see #49.

**Comment by MoOx** [comment]
FYI, here is how I do for now

```js
import "babel-core/register"
import test from "ava"

import React, { Component } from "react"
import { createRenderer } from "react-addons-test-utils"
// import ReactDOMServer from "react-dom/server"
import expect from "expect"
import expectJSX from "expect-jsx"
expect.extend(expectJSX)

import MyComponent from ".."

test("MyComponent default render", (t) => {
  const renderer = createRenderer()

  renderer.render(
    <MyComponent />
  )
  expect(
    renderer.getRenderOutput()
  )
  .toEqualJSX(
    <div />
  )
})
```

**Comment by novemberborn** [comment]
Let's continue discussion in #446. Any future improvements will benefit from our solution to #25.
