### ISSUE TITLE
`npm run test-win` should use a verbose tap-reporter

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#188]
If it helps me avoid launching a VM whenever an AppVeyor builds fail, it's worth a few extra seconds of wading through verbose test output.

**Comment by sindresorhus** [comment]
:+1: Agreed. Anything to make debugging easier. Just pick whichever reporter you like.

**Comment by vdemedes** [comment]
It'd also be good to do the same for `npm test` too, those dots don't really give an idea of what's going on.
