### ISSUE TITLE
Built-in ES2015 support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#20]
Would be nice to support ES6 built-in at runtime by using the [Babel require hook](https://babeljs.io/docs/using-babel/#babel_register).

That way you can just write your tests in ES6 and have it run in any node version.

This is so nice:

```js
test(t => {
  t.ok();
  t.end();
});
```

**Comment by andrepolischuk** [comment]
May be use flag --esnext?

```json
{
    "scripts": {
        "test": "ava --esnext"
    }
}
```

**Comment by sindresorhus** [comment]
I was thinking ES2015 support by default. Can't think of any reason not to want ES2015 when there's no setup cost.

**Comment by andrepolischuk** [comment]
It would be better then with flag.
