### ISSUE TITLE
Load Babel config from .babelrc, for each path

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/ava#202]
Under [ES2015 support](https://github.com/sindresorhus/ava#es2015-support), the readme says "You can also use your own local Babel version" by specifying it in the package.json.

But this doesn't seem much use if we can't also provide our own Babel config. From the code [here](https://github.com/sindresorhus/ava/blob/186fd78009aebe9bf2cb3b487f60dcb5a9215085/lib/babel.js#L17-L27) it looks like AVA decides its own Babel options. It would be more useful if it could determine the appropriate options for each file, based on the closest `.babelrc` (or `package.json` containing a `babelConfig` field) to each file.

**Comment by jokeyrhyme** [comment]
Apparently it's just `babel` in package.json now, not `babelConfig`: https://babeljs.io/docs/usage/babelrc/#use-via-package-json

**Comment by novemberborn** [comment]
Please see #448.
