### ISSUE TITLE
Error context

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#22]
Tape has this nice output on errors:

```
at: Test.<anonymous> (/Users/sindresorhus/dev/hypot/test.js:9:4)
```

Currently we output the full stack trace or none.

-

This might be something `claim` should handle.

https://github.com/substack/tape/blob/ccfcf4f76581abc3842163dfe065198764247c85/lib/test.js#L207

**Comment by mdibaiee** [comment]
Hey, I'd like to work on this. I opened a pull-request and I want your feedback on that. #29
