### ISSUE TITLE
Add source-map-support

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/ava#223]
<https://www.npmjs.com/package/source-map-support> could be added to `babel.js`. Configured properly this would work with any source maps in the files under test, as well as the transformed test file.

**Comment by jamestalmage** [comment]
@novemberborn 

What issue are you trying to address here? Correct line numbers in stack trace output of transpiled test files? Consuming source-maps? Give us an example of how AVA is not doing what you expect.

**Comment by novemberborn** [comment]
Correcting line numbers in stack trace output, yes. Sorry didn't make that clear.

Though it's not just the test files. If the code you're testing was previously transpiled and contains the source map pragma then errors coming from that code will also be presented correctly. This will help debugging your code and tests.

**Comment by jamestalmage** [comment]
#254 fixes this for your test file.

Getting it completely right will not be trivial. See #254 for discussion.

**Comment by niftylettuce** [comment]
Can we please document how to do this with nyc + transpiled code in the README for Ava?

It's super frustrating to not have proper source map support, and it's nearly been a year and there's still no solution to the source map issue with transpiled code and/or using nyc.

**Comment by novemberborn** [comment]
@niftylettuce bugs aside, a PR to update documentation is always welcome 👍
