### ISSUE TITLE
Automatically ignore test files in node_modules folder

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#226]
See #224 

The glob string was picking up a test file that was deployed with a dependency. (Unclear if they were using the default glob string or not - that should be looked into as well).

Should we automatically ignore `basedir/node_modules`? I can't see why a user would ever want that.

**Comment by sindresorhus** [comment]
Yes, definitely.

**Comment by sotojuan** [comment]
I'll submit my PR later for this, but I "fixed" it doing two things:

* Add `node_modules/` to the array [here](https://github.com/sindresorhus/ava/blob/master/cli.js#L203)

* Add:

```javascript
	files = files.filter(function (file) {
		return (file.indexOf('node_modules') === -1);
	});
```

Below the `if` statement in the same place as above. This makes sure all paths that have `node_modules` in them are gone in case the user did something like `ava **`.

I am not sure if this is the most efficient way to do it, but it works.
