### ISSUE TITLE
Unhandled rejection on node 0.10

### ISSUE THREAD

**Issue by TrySound** [sindresorhus/ava#232]
All catched rejections still throw on node 0.10
https://github.com/davidtheclark/cosmiconfig/pull/17

**Comment by jamestalmage** [comment]
Do you know what promise library you are using?

**Comment by TrySound** [comment]
@jamestalmage pinkie-promise

**Comment by jamestalmage** [comment]
Try switching to bluebird and see if it fixes it.
We just added `unhandledRejection` to `pinkie` earlier this week, and there could be a bug in the implementation.

**Comment by jamestalmage** [comment]
In fact, I'm pretty sure I see the bug already

**Comment by TrySound** [comment]
Thanks :) We willl wait for your fix

**Comment by jamestalmage** [comment]
it's the chaining that is the problem.

promise.catch() <- marks this as handled

promise.then().catch() <- only marks the last one as handled.

// @floatdrop - I'm working up a PR.

**Comment by jamestalmage** [comment]
https://github.com/floatdrop/pinkie/pull/11

```
npm install jamestalmage/pinkie#fix-chained-rejection
```

Let me know if it works for you. (note that is still an open branch, and might get some changes before the PR is done - don't use it IRL).

**Comment by TrySound** [comment]
@jamestalmage Yep, works fine. Thank you
