### ISSUE TITLE
Only run babel over the test code

### ISSUE THREAD

**Issue by JakeChampion** [sindresorhus/ava#238]
### Issue:
Application code doesn't use a preprocessor and uses a feature that is not implemented in their production JS engine of choice. The tests will pass because they precompile the application code, upon deployment the application will fail as the engine doesn't support the feature being used.

### Steps to reproduce:
Write a function which uses a feature not implemented by the engine but is precompiled, default arguments is currently one such feature.
Write a test for the function, it will pass, it _should_ fail.

**Comment by sindresorhus** [comment]
Are you using latest AVA version? We fixed that some time ago.

**Comment by JakeChampion** [comment]
Was 3 minor versions behind.
