### ISSUE TITLE
Proposal to make test() behavior more explicit and optimize for the future

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#244]
Continued from https://github.com/sindresorhus/ava/issues/133.

-

I've been thinking a lot about sync vs. async tests and I really would like to make it more explicit and optimize for the future. Currently when using `test()` it's ambiguous whether the test is sync or async. The reality is also that most tests are sync and it's annoying and easy to forget the `t.end()` in every test (even I forget it all the time).

I propose we change the interface:

#### Before

- `test(t => {})` - async/sync depending of whether you do any async operation
- `test(async t => {})` - promise async

#### After

- `test(t => {})` - sync (no longer required to use `t.end()`)
- `test(async t => {})` - promise async (what you really should be using)
- `test.async(t => {})` - callback async (legacy)

The main change here is that `test()` goes from being async to being sync with async support through async functions.

I know it's a breaking change, but isn't now the time to do that?

This will make AVA more future friendly as we'll eventually just use async functions for async operations. We'll support `test.async()` for legacy, but have a nice main interface for the main use-cases.

-

// @vdemedes @jamestalmage @kevva @arthurvr @SamVerschueren @af @taylorhakes and anyone else with opinions.

**Comment by ben-eb** [comment]
:+1:

**Comment by SamVerschueren** [comment]
I'm ok with changing this. In `one-line` modules, most of the time you only have one test. But it still forces you to write `t.end` or `t.plan`.

```js
test('result', t => {
    t.is(fn('foo'), 'bar');
    t.end();
});
```

With these changes, this can be written to

```js
test('result', t =>  t.is(fn('foo'), 'bar'));
```

I never use `t.end` in a callback, because promises (await/async) all-the-way! Maybe sometimes when using streams if it's not possible to use `get-stream`.

So in general, good for me!

**Comment by Qix-** [comment]
I approve, but I would drop the legacy support and release as a major. Why not go all-the-way?

The use of the `async` keyword keeps things clean and seems much more natural to me, personally. `test()` now remains an all-in-one method (of sorts) that can still show explicit sync/async tests.

:+1:

**Comment by SamVerschueren** [comment]
@Qix- I guess the legacy can't be dropped. How would one test something like [this](https://github.com/sindresorhus/pageres-cli/blob/master/test/test.js#L15-L25) without `t.plan` or `t.end` support?

**Comment by sindresorhus** [comment]
@Qix- `test.async()` is there for callback-based APIs which isn't going away anytime soon...

**Comment by Qix-** [comment]
Oh I see, nevermind. :+1:

**Comment by taylorhakes** [comment]
Does `t.end()` exist in the sync version? Might be easier to upgrade, but add confusion later.

Maybe `test.callback` might be a better name? I seems like async is still possible in the regular version.

**Comment by sindresorhus** [comment]
> Does t.end() exist in the sync version? Might be easier to upgrade, but add confusion later.

We can expose it there as a noop function.

> Maybe test.callback might be a better name?

Even though the main use-case is for callback-style APIs doesn't mean that's the only. I'd rather name it for what it is.

> I seems like async is still possible in the regular version.

No, it will finish at the end of the tick. So async operations will be ignored.

**Comment by taylorhakes** [comment]
Makes sense. I would be a little confused by `t.end` being a noop. I'd rather have it not exist to make sure I didn't make a mistake.

I guess we disagree on what is async. I consider this async.
```
test(async () => {
...
})
```

**Comment by af** [comment]
This looks great!

**Comment by sindresorhus** [comment]
> I would be a little confused by t.end being a noop. I'd rather have it not exist to make sure I didn't make a mistake.

Yeah, good point. I agree that's better.

> I guess we disagree on what is async. I consider this async.

Oh, I misunderstood you. Yes, async is possible with `test()` by using an async function.

**Comment by jamestalmage** [comment]
:+1: 
This is the problem I was trying to communicate with #199, and I think this change provides a great solution.

> I'd rather have it not exist to make sure I didn't make a mistake.

Let's take that further:

```js
Object.defineProperty(test, 'end', {
  get: function () {
    throw new Error("t.end is not supported in this context. To use t.end as a callback, you must explicitly declare the test asynchronous via `test.async(testName, fn)` ")
  }
);
```

**Comment by sindresorhus** [comment]
> Let's take that further:

@jamestalmage :+1:!

**Comment by jamestalmage** [comment]
In the case of an a function that has not been explicitly declared `async`, what becomes of `t.plan()`?

I thoroughly dislike the use of `t.plan` as a shortcut for automatically ending tests, but a lot of people are used to that.

If we have an **implied** async function, I say `t.plan` is only used as another form of assertion ("this is how many assertions we had"). We do not shortcut the end of the test until the generator/promise/observable/whatever is resolved.

If we have a **declared** async function, my preference would be to behave the same (just another assertion validation how many assertions we had). However, I think there is room for debate given that declared async tests closely follow existing frameworks like `tap`, so mimicking `t.plan` behavior might be the least surprising thing to do.

I have made up some terms here:

 - **declared** async => 

  `test.async('title', fn)`

 - **implied** async => 

  `test('tiltle', generatorFn)` / `test('title', promiseFn)` / `test('title', async t => {})`

**Comment by Qix-** [comment]
For the record, `t.plan()` is useful to catch loop bound errors, such as when you expect a loop to run X amount of times with Y amount of assertions (`t.plan(X + Y)`), and the loop runs too long/short.

Another, probably more relevant use of planned assertions are double-callback invocations. If a callback is called multiple times, the easiest and cleanest way to detect multiple assertions is with `t.plan()`.

It's not "useless", it's just high maintenance.

**Comment by jamestalmage** [comment]
@Qix- 
I never said plan was useless. Just that I do not like using it as a means of auto ending your test.
It certainly has value for all the things you just described. With auto-ending, you can do this:

```
t.plan(3);
for (var i = 0; i < 3; i++) {
  t.pass();
}
```

With my proposed modification to `plan`, you would be required to do this:

```js
t.plan(3);
for (var i = 0; i < 3; i++) {
  t.pass();
}
t.end(); // this is no longer assumed for you, just because you made it to 3 assertions.
```

The issue that arises is this:

```js
t.plan(3);
for (var i = 0; i < 3; i++) { // oops - I'm only expecting this to execute twice
  t.pass();
}
setTimeout(() => t.end(), bigNumber); // I expect this to be my third and final assertion
```

In this case, we may "auto-end" the test because you reached your plan and kill the process before your assertion inside the `setTimeout` ever fires. This produces a false pass for you - and some really painful debugging when you place confidence in what you think this test is telling you and search elsewhere.

**Comment by jamestalmage** [comment]
OK,
I took an initial stab at this in #253. 

It depends on PR #243 - so it is best to [focus on the commit](https://github.com/jamestalmage/ava/commit/40045b81e9ac43843ebf0af66feff15118e087d9) where I actually implement this proposal.

**Comment by sindresorhus** [comment]
@jamestalmage I agree `t.plan` in "implied async" should not auto-end the test. I already decided that, but forgot to write it down. With those we actually have the opportunity to catch "more than planned assertions async", which we previously couldn't (can you add a test for that in your commit?).

As for "declared async" (test.async), I'm not sure. I would like to change it, both because it's better and for consistency with "implied async", but not sure if it's worth it seeing as it's legacy anyways and lots of people would assume that's how it works. Happy to discuss it, though (hint hint, people express your thoughts). Would be a nice change.

**Comment by Qix-** [comment]
If you're referring to `test.async(() =>` vs `test(async t =>`, why not `test.callback(t =>`?

**Comment by sindresorhus** [comment]
@Qix- Already answered in https://github.com/sindresorhus/ava/issues/244#issuecomment-158411625.

**Comment by jamestalmage** [comment]
OK, next question:

What should happen if they are using "declared async" (test.async), and they return a Promise?

The current behavior is to auto-end with the Promise, but it seems to me that once you have declared `test.async`, you have bought into the legacy API, and should be **required** to call `t.end()` at that point.

Consider this scenario that might arise when you are forced to deal with a mix of both promisified and nodeback API's:

```js
test.async('mixed api example', async t => {
  var a = await promiseReturningFuncA();
  var b = await promiseReturningFuncB();
  
  // the async function will fall through and return a resolved Promise
  // possibly before this callback is done.
  callbackFunction(a, b, (err, result) => {
    t.ifError(err);
    t.is(result, ...);
    t.end();
  });
});
```

*I am aware that this contrived example is easy to promisify. But what if it wasn't*

**Comment by SamVerschueren** [comment]
In that case, you have to call `t.end` because you explicitly "subscribed" for that behaviour.

**Comment by jamestalmage** [comment]
OK, so when using callbacks, auto-ending with plan does have a use. Coordinating ending after two or more callbacks who will be called in indeterminate order:

```js
t.plan(2);

setTimeout(function () {
  t.pass();
}, randomTime());

setTimeout(function () {
  t.pass();
}, randomTime());
```

That is pretty niche though. So what about an opt-in (or opt-out) auto-ending behavior:

```js
t.plan(2, true); // automatically end after two tests
```

**Comment by ben-eb** [comment]
@jamestalmage I find optional boolean parameters to be an anti-pattern, would either prefer a string literal or an options object. :smile:

http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html

**Comment by jamestalmage** [comment]
Good call!

String literal sounds less verbose, and I guess I don't see needing to shove a lot of options in there.

```js
t.plan(2, 'auto-end');
```

Optionally, the `plan` function could return a chainable object:

```js
t.plan(2).autoEnd();
```

**Comment by sindresorhus** [comment]
> What should happen if they are using "declared async" (test.async), and they return a Promise?

That should not be allowed. They should instead use `test()`. We should detect it and throw an helpful error message.

> OK, so when using callbacks, auto-ending with plan does have a use. Coordinating ending after two or more callbacks who will be called in indeterminate order:

I think we should drop auto-ending. Not even an option for it. I want to keep AVA simple and consistent. Instead, we should document how to count callbacks and `t.end()` when reached and recommend instead just splitting up the test into multiple, which is better anyways.

**Comment by vdemedes** [comment]
@sindresorhus +1!

**Comment by dbkaplun** [comment]
+1
