### ISSUE TITLE
Use released 'destory-circular' dep from npm

### ISSUE THREAD

**Issue by sparty02** [sindresorhus/ava#246]
```package.json``` has a github-linked dep for ```destroy-circular```, as:

```"destroy-circular": "jamestalmage/destroy-circular#feeb7d1",```

That seems to look like it's in line with the 1.1.0 release of ```destroy-circular``` out on npm.  Can this leverage the npm 1.1.0 release instead?  I'm in an environment that doesn't have direct access to github; we use a proxied npm repo.

cc/ @jamestalmage

**Comment by sindresorhus** [comment]
It's not the same. We depend on https://github.com/jonpacker/destroy-circular/pull/1

We plan to fix it here instead: https://github.com/sindresorhus/serialize-error/issues/2

**Comment by jamestalmage** [comment]
@sparty02 - as of `0.6.1` we no longer have a git dependency.

**Comment by sparty02** [comment]
@jamestalmage thanks for the update!
