### ISSUE TITLE
Show stack trace of uncaught exceptions.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#248]
See this comment: https://github.com/sindresorhus/ava/issues/245#issuecomment-158339191

@sindresorhus - Can you start assigning me tasks you want me to own so I don't forget about them? I read some of this stuff on mobile, and it can be a pain trying to remember everything I'm supposed to follow up on when I get back to a keyboard. It would be really nice if Github allowed some sort of "Pinning" / "Todo".

**Comment by jamestalmage** [comment]
Duplicate of #255, Closed by #257

**Comment by sindresorhus** [comment]
> Can you start assigning me tasks you want me to own so I don't forget about them?

Will do from now on. You can also self-assign yourself tasks, on the right-hand side (Assignee).

**Comment by jamestalmage** [comment]
Yep - I asked that before you added me.
