### ISSUE TITLE
If specifying a directory, tests in subdirectories should be run too

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/ava#249]
If I do `ava test` where test is a directory, it only runs the files directly under `test`. But if I had subdirectories under it, those don't get run. I think it should run all tests in that directory recursively. Or at least there should be a command line flag like `-r` to get this behavior.

**Comment by sindresorhus** [comment]
It's intentionally not recursive, as a good default and simplicity. If you need it to be recursive just specify the appropriate glob pattern. Like: `$ ava test/**`.

**Comment by rightaway** [comment]
Ok. Now if I have a file `test/test1.js` and `test/subtest/test2.js` (each with one test called `runTest` in it) and run `ava test/**/*.js` (glob pattern in ZSH) on the command line, the output looks like this

```
test2 > runTest
test > test1 > runTest
```

But it should look more like

```
test1 > runTest
subtest > test2 > runTest
```

At least while nested groups aren't available (https://github.com/sindresorhus/ava/issues/222) using directories is a good way to organize structure, so the output should be in line with that.

The beginning `test` doesn't appear above since that's the 'root' test folder, but if there's no option to specify a directory and a recursive flag then I don't see how it would know that test shouldn't be printed there.

That's why I think allowing to specify a directory with a recursive flag (so it's not the default and not a breaking change) would be useful, because then ava can format the results appropriately. Because using glob patterns ava just receives a list of filenames to test and isn't aware of a 'root'.

**Comment by sindresorhus** [comment]
We don't add options lightly and we try very hard to keep AVA simple. You can solve this with a glob pattern. We'll fix the output somehow.

**Comment by rightaway** [comment]
A suggestion of how it could look. After seeing all the files passed in with the glob pattern it should strip the leading directories that are all in common. The way if someone passes in a pattern like `some/sub/directory/**/*.js`, and the only files that appear are `some/sub/directory/sub/path/test1.js` and `some/sub/directory/sub/path/test2.js`, then the part in common `some/sub/directory/sub/path` should not appear in the output.

**Comment by sindresorhus** [comment]
Agreed, that's what I was thinking too.

**Comment by Qix-** [comment]
I think it should be recursive by default.

In my case, I want to mimic my `lib/` folder with test files in order to yield more [succinct output](https://github.com/sindresorhus/ava/issues/53#issuecomment-141339499) with nested files.

Further, this is how other languages' test systems work and is analogous to those for me, personally - hence my decision to structure my tests like this.

As of now, I have to do `ava test/**/*.js` which is just fine, but it wasn't what I was expecting at first.

**Comment by sindresorhus** [comment]
@jamestalmage @vdemedes Thoughts on making it recursive by default? I'm warming up to the idea.

**Comment by Qix-** [comment]
All AVA really needs to do is include the file in question and ignore it if it doesn't import the test function.

**Comment by jamestalmage** [comment]
> All AVA really needs to do is include the file in question and ignore it if it doesn't import the test function.

I'd prefer to have it throw an error. We fork for each of those and that is expensive. We automatically ignore files with a `_` prefix, so use that for test helpers.

> Nested files, to me, should have their file prefixes (in my opinion). Right now it's flat. Not sure if this is because I'm specifying files on the command line, or what.

I'm not sure what you mean. Their directory as part of the prefix? Right now we only prefix with the filename (and just the filename) if there is more than one test file. I think it makes sense to prefix directories (find the common base directory of all test files and prefix from there).

**Comment by vdemedes** [comment]
I like this suggestion, we could simplify paths and remove the need for globs.

**Comment by sindresorhus** [comment]
Alright. Let's go for this.

**Comment by brandon93s** [comment]
+1 on making AVA recursive by default. It's the behavior I was expecting initially and doesn't force the user to conform to a standard structure.

**Comment by ariporad** [comment]
@sindresorhus: Do you want it to be recursive by default, or just to display directories up to a common root?

**Comment by sindresorhus** [comment]
@ariporad Both

**Comment by ariporad** [comment]
@sindresorhus: Ok, I'll take care of it. Can you assign this to me (or give me perms to do that if you prefer)?

**Comment by Qix-** [comment]
@Ariporad just submit a pull request :)
