### ISSUE TITLE
PowerAssert shows incorrect line

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/ava#250]
I assume it's a mapping issue since we're transpiling things with babel.

<img width="138" alt="screen shot 2015-11-21 at 06 28 14" src="https://cloud.githubusercontent.com/assets/885648/11318672/12a429e4-9019-11e5-85ce-9bb75c0988ac.png">
<img width="433" alt="screen shot 2015-11-21 at 06 28 28" src="https://cloud.githubusercontent.com/assets/885648/11318675/1a841250-9019-11e5-8e53-0bc2b6297a66.png">

As you can see the source file in question only goes to line 120, but the error message shows 299.

**Comment by jamestalmage** [comment]
Duplicate of #223.

PR for Fix: #254

**Comment by Qix-** [comment]
:+1: couldn't find it in the issue search for some reason. Thanks.
