### ISSUE TITLE
proposal: Hide `Test` internals. Expose a delegate object instead.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#252]
We expose instances of `Test` to the user. It's the `t` in the following code:

```js
test('title', t => {
  t.is(foo, bar);
});
```

That has all kinds of internal information on it, including

 - `assertCount`
 - `planCount`
 - `duration`
 - `_timeStart`
 - `planStack`
 - etc, etc, etc.

We are already looping over all the public methods and binding them to the test [here](https://github.com/sindresorhus/ava/blob/0caf0cf7b29615ca3da94812d91c4fc288d6a7b3/lib/test.js#L43-L45) so users can pass around methods without worrying about `this` bindings.

I suggest we copy those values (perhaps being a bit more careful to select only that which we truly want public), to a secondary object that we expose.

**Comment by sindresorhus** [comment]
:+1: from me. @vdemedes ?

**Comment by vdemedes** [comment]
What if we just made them non-enumerable? So that we won't need to use `this.options.assertCount` instead of `this.assertCount` inside `lib/test.js` itself.

**Comment by jamestalmage** [comment]
We would not need to do that. We would create a different object, and put methods on it that were bound to the test instance test:

```js
Test.prototype._createPublicAPI = function () {
  var api = {};
  var self = this;
  listOfPublicMethods.forEach(function (methodName) {
    api[methodName] = self[methodName].bind(self);
  });
};
```

Or we could use [`delegates`](https://www.npmjs.com/package/delegates).

The problem with non-enumerable is that they can still be clobbered. I am working on #25 (registering custom assertion methods) - and we don't want to have to force them to avoid our internals as they name their method.

**Comment by vdemedes** [comment]
Oh, I get it now. `delegates` usage would be really good, love this module.
