### ISSUE TITLE
start using `tap.match` in unit tests

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#256]
We have lots of assertions on regular expressions, but we are using `tap.true(regex.test(...))` and similar. When these fail, the reporter outputs really terrible info ("expected true got false" is the gist).
Using `tap.match` provides more information.

There are a number of PR's open right now, so let's wait to do that cleanup until some of the big ones have been merged.

**Comment by sindresorhus** [comment]
Sure, since we don't have `power-assert` with `tap`.

**Comment by vdemedes** [comment]
Fixed by #331.
