### ISSUE TITLE
Why no semantic versioning?

### ISSUE THREAD

**Issue by dralletje** [sindresorhus/ava#268]
This is not really an issue, but more a curious question.
Not sure if it belongs here or would fit better on twitter, haha!

Why doesn't the project use 'hardcore' semantic versioning? Why is it still 0.X.X?

**Comment by sindresorhus** [comment]
It follows semver, but it's unstable, hence not being v1 yet. No idea what you mean by "hardcore semantic"? Can you elaborate on why you think it doesn't follow semver?

**Comment by jamestalmage** [comment]
Related: http://semver.org/

>
 4 - Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.  

>...  

> FAQ

> **How should I deal with revisions in the 0.y.z initial development phase?**

>The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

--

Use [Caret Ranges](https://www.npmjs.com/package/semver#caret-ranges-1-2-3-0-2-5-0-0-4) in `package.json` when it comes to `pre-1.0.0` projects.
(I personally use caret ranges just about everywhere)

> **Caret Ranges** `^1.2.3`   `^0.2.5`  `^0.0.4`
Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions `1.0.0` and above, patch updates for versions `0.X` >= `0.1.0`, and no updates for versions `0.0.X`.

> Many authors treat a `0.x` version as if the `x` were the major "breaking-change" indicator.

**Comment by jamestalmage** [comment]
@dralletje 
I think we answered your question. If not, please reopen this.
