### ISSUE TITLE
Hide our own error stack on IPC messaged errors

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#269]
From: https://github.com/sindresorhus/ava/issues/245#issuecomment-158339191

-

Our error stack is pretty useless when an error comes from the forked process.

**Comment by jamestalmage** [comment]
Agreed.

I think the best solution is to stop rejecting the promise in that case. Rejection has the side affect of bailing out of `Promise.all` early, so other test files may not finish. We should resolve with an failure result, that will simply be summarized in the output. We should save rejection for unexpected/unrecoverable problems.

**Comment by sindresorhus** [comment]
> We should resolve with an failure result, that will simply be summarized in the output. We should save rejection for unexpected/unrecoverable problems.

:+1:

**Comment by novemberborn** [comment]
Pretty sure this has been addressed in various ways. Closing.
