### ISSUE TITLE
TAP support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#27]
Should be a flag, like `$ ava --tap`, to get TAP output. This would be a good way to enable reporters without actually supporting reporters. Can just refer people to all the available TAP reporters instead of reinventing the wheel.

**Comment by scottcorgan** [comment]
I know that a PR is better than this question, BUT, is this still a priority?

**Comment by jprichardson** [comment]
:+1:

**Comment by jamestalmage** [comment]
From my reading of the TAP spec, I it does not seem very well suited to concurrency. You would need to buffer individual tests and then log them all at once so they don't walk all over each-other.

**Comment by vdemedes** [comment]
Coming Soon!

<img width="378" alt="screen shot 2015-11-29 at 7 18 50 pm" src="https://cloud.githubusercontent.com/assets/697676/11459052/179e680e-96ce-11e5-8a87-b092db191964.png">

**Comment by vdemedes** [comment]
TAP support is ready, waiting for #279.

**Comment by jprichardson** [comment]
After I saw this closed by @vdemedes I assumed it was part of `0.7.0`. But didn't see it listed https://github.com/sindresorhus/ava/releases/tag/v0.7.0. Since this issue is still part of `0.7.0`, does that mean that it's in `0.7.0` and hence forgotten about in the release announcement or that a new milestone should be associated with this issue?

**Comment by jamestalmage** [comment]
@jprichardson - We decided to push #279 to [the next milestone](https://github.com/sindresorhus/ava/pull/279#issuecomment-160478598).

**Comment by sindresorhus** [comment]
It was closed by a mistake.

**Comment by jonathanKingston** [comment]
> @jamestalmage From my reading of the TAP spec, I it does not seem very well suited to concurrency.

That is the case certainly, I am happy to discuss some of my suggestions that have been aired on TAP specification discussions however likely won't be adopted very quickly at all (Having a different output might be simpler)
