### ISSUE TITLE
t.endIf(boolean) to replace removed auto-ending behavior.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#278]
API would be simple:

```js
t.endIf(t.assertCount === 4);
```

This would also require we formally document and lock `t.assertCount` as part of the API.

**Comment by vdemedes** [comment]
To be honest, I am not a fan of this kind of API. As for me, I'd rather write `t.end()` in every non-promise test instead of `t.endIf(condition)`.

**Comment by jamestalmage** [comment]
how about just formally exposing `assertCount` in the test object.

**Comment by jamestalmage** [comment]
I think you're right. Closing.

**Comment by sindresorhus** [comment]
:-1: from me too. I also don't think we should spend much energy on the legacy `cb` mode. And really, if you need multiple async assertions, you should probably just split up into multiple tests anyways.
