### ISSUE TITLE
Handle SIGSEGV

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/ava#28]
SIGSEGV occurs when a program performs a native memory operation that isn't valid (i.e. referencing/writing to a piece of unallocated memory).

This is important for native module programming, as if it segfaults it'd be nice to gracefully handle it as a test failure instead of terminating the offending process - especially when there are lots of tests.

However, there should be discussion on it as I believe it requires you use `fork` (thought not entirely sure). I'd have to do more research.

Not entirely sure this is relevant to windows, either (with windows, there isn't a great way to recover from an access violation) - you'd probably need to write a native module with `/EHsc` in the flags and wrap *something* in a try/catch statement (though that's considered icky and probably wouldn't work with V8).

**Comment by sindresorhus** [comment]
This will probably be easier when #1 is implemented. AVA will then run tests in separate sub-processes.

**Comment by Qix-** [comment]
That'll prevent coverage tests from working.

**Comment by sindresorhus** [comment]
No: https://github.com/bcoe/nyc

**Comment by Qix-** [comment]
:+1: Starred. Istanbul is what I use and it doesn't; figured that was a global thing.

**Comment by SamVerschueren** [comment]
Should AVA already work with nyc? Trying it out right now but it reports no coverage at all which is quite odd.

**Comment by sindresorhus** [comment]
We want AVA to work with it, but I haven't tested. Not a top priority right now as we're focusing on finishing the API and performance. Happy to receive some help debugging/PR/etc, though.

**Comment by sindresorhus** [comment]
@Qix- We're now forking each test file. Any recommendation on how we should handle this?

**Comment by Qix-** [comment]
No idea how signals work with threads. Id have to do some research.

**Comment by sindresorhus** [comment]
@Qix- We're not using threads (there are no threads in JS), but subprocesses.

**Comment by Qix-** [comment]
Well right. I'd assume each fork would have to register its own signals. I've never done that before, but I'm pretty sure it's analogous to how it works on the native level. And then there's windows...

**Comment by sindresorhus** [comment]
`fork` in the Node.js sense is just a spawned Node.js process with an IPC channel. So it's just a normal child process with normal process signals. I think the best solution here is to just do nothing. If a test file has a SIGSEGV it will just fail the test file, not all the test files.

**Comment by Qix-** [comment]
Fair enough. It's an edge case but maybe when the core is a little more stable in terms of the other forking issues that are open, perhaps we can reconsider this. :+1:
