### ISSUE TITLE
Test programmatic API

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#285]
From: https://github.com/sindresorhus/ava/pull/279

Should be done before the next minor release.

We should also convert many of the CLI tests to API tests instead.

**Comment by sotojuan** [comment]
I got this 👍🏼, will look into it today. For the CLI tests, it's just a matter of changing the `child_process` stuff to `new Api...` with the correct arguments and then `api.run()...` right?

**Comment by vdemedes** [comment]
@sotojuan Converting 'child_process stuff to api' - right, but with a new API we can and should test more cases and have more precise tests.

**Comment by sotojuan** [comment]
I see. Well, I'll begin with converting some over the weekend, but can you give some examples of more precise tests?

**Comment by vdemedes** [comment]
@sohamkamani I don't have them in my mind at the moment (1am), but I'm sure you will get some ideas during CLI -> API conversion :) Anyway, let's start with what we have right now. Sounds good?

**Comment by sotojuan** [comment]
👍 even if you mentioned the wrong person : )

**Comment by sotojuan** [comment]
@vdemedes so I am working on converting the CLI tests to use the API, but I am just wondering if this makes sense.

For example, for the first CLI test (ES2015 support):

```javascript
test('ES2015 support', function (t) {
  t.plan(1);

  var api = new Api([path.join(__dirname, 'fixture/es2015.js')]);

  api.run()
    .then(function () {
      t.ok(true);
    });
});
```

The test passes, but I am not sure if this is the best way to test. The original CLI test just checked that it did not return an error, so perhaps doing `t.ok(true)` has the same effect. I tried doing `t.doesNotThrow` but then it said it was pending.

Thanks and sorry for any silly questions!

**Comment by vdemedes** [comment]
@sotojuan replied to your PR there ;)
