### ISSUE TITLE
Review where we forward child stdio streams.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#291]
Currently we forward both `stdout` and `stderr` of each forked child process to `stdout` on the main process. In my mind that makes the *least* sense of the the available options. I think we should either:

1. pipe `child.stdout` to `process.stdout`, and `child.stderr` to `process.stderr`.
2. pipe both to `process.stderr`. This keeps `process.stdout` pristine and will not interfere with the pending TAP output.

**Comment by vdemedes** [comment]
> This keeps process.stdout pristine and will not interfere with the pending TAP output.

I like this one, although option 1 seems "more correct".

**Comment by jamestalmage** [comment]
I certainly think option 2 is the way to go. I can't really think of a scenario where it would cause a problem. If you want to test what is written to stdout you are likely forking inside your test, or mocking.

**Comment by sindresorhus** [comment]
Let's go with option 2.
