### ISSUE TITLE
Stacktrace for syntax errors incorrectly points to the test file

### ISSUE THREAD

**Issue by ecowden** [sindresorhus/ava#308]
If I have a function under test with a syntax error like:

```
// demo.js
module.exports = function () { // missing closing brace
```

...and a test like:

```
// demoTest.js
const test = require('ava')
const demo = require('./demo')

test(async function (t) {
  t.ok(true)
})
```

Then the syntax error is reported pointing to the `require` statement in the test file instead of the file with the error:

```
Uncaught Exception:  /Users/cowdene/src/avaIssue/demoTest.js
  SyntaxError: Unexpected token )
    at Object.<anonymous> (/Users/cowdene/src/avaIssue/demoTest.js:2:14)
```

This is pretty confusing and is especially tricky for newer Node developers.

**Comment by novemberborn** [comment]
Either of these report the error:

```js
// requireDemo.js
const demo = require('./demo')
```

```js
// requireDemoFromString.js
var requireFromString = require('require-from-string');
requireFromString("const demo = require('./demo')", "hi.js")
```

However `lib/babel` uses `process.on('uncaughtException')` to catch the error, serialize it, and send it to the cli. Here's where the information gets lost.

I think Node runs [this code](https://github.com/nodejs/node/blob/322b36c0a163bc723a6d612d740f98775e0750f6/src/node.cc#L1382:L1388) when writing the error to `stderr` if a process crashes. This can somehow access the original source file and whatnot. Not sure how to get access that from JS.

**Comment by jamestalmage** [comment]
Related: https://github.com/nodejs/node-v0.x-archive/issues/3452

**Comment by jamestalmage** [comment]
It's impossible to fix this in a clean way in JS, the V8 related issues are here: 

https://code.google.com/p/v8/issues/detail?id=1914
https://code.google.com/p/v8/issues/detail?id=1281

The only workaround I can see is to wrap `Module.prototype._compile` to temporarily disable our `uncaughtException` handler. Here is a quick prototype of what I am thinking:

```js
var compileDepth = 0;
process.on('uncaughtException', function (e) {
  if (compileDepth !== 0) {
    throw e;
  } else {
    console.log('error swallowed this will not work');
  }
});

var Module = module.constructor;

var oldCompile = Module.prototype._compile;

Module.prototype._compile = function (code, filename) {
  compileDepth ++;
  oldCompile.apply(this, arguments);
  compileDepth --;
};

var requireFromString = require('require-from-string');

var badUserCode = 'function () {';

requireFromString(badUserCode, 'bar.js');
```

This means any errors thrown synchronously when a module is `require`d are just going to crash the whole test. This will be true even inside tests:

```js
import test from 'ava';

test('test A', t => t.pass());
test('test B', t => t.pass());
test('test C', t => require('./moduleThatThrowsSynchronously'));
```

This change would also make AVA a less than ideal place to test any code that attempts to wrap / manipulate `Module._compile`. (It would have given me headaches while developing `capture-require` for instance).

**Comment by jamestalmage** [comment]
sourcemap-support adds an `unhandledException` listener as well (disabling the helpful output). That can be fixed using the `handleUncaughtExceptions` option and setting it to false:

```js
var sourceMapSupport = require('source-map-support');
sourceMapSupport.install({
	handleUncaughtExceptions: false,
        ...
```

not sure what problems additional problems that will cause.

**Comment by jamestalmage** [comment]
OK, 
I think a much simpler solution would be to move [this](https://github.com/sindresorhus/ava/blob/6f8e2c4127409271fcdb26c87211931b5054fe9b/lib/babel.js#L74-L76), down to [here](https://github.com/sindresorhus/ava/blob/6f8e2c4127409271fcdb26c87211931b5054fe9b/lib/babel.js#L93) as well as setting the `handleUncaughtExceptions` flag I mentioned in the previous comment(set it [here](https://github.com/sindresorhus/ava/blob/6f8e2c4127409271fcdb26c87211931b5054fe9b/lib/babel.js#L28)).

This is going to cause a few of our current `api` tests to fail.

I can work on this later tonight unless someone else wants to take it up. @sotojuan - You are already familiar with those tests. You wanna give it a go? You could start with https://github.com/jamestalmage/ava/commit/b1986249b6b59efba05413be3a7b746c4f2bc27d (or just emulate what I have done there). I think it might mean moving the syntax error test back to `cli` territory.

**Comment by sotojuan** [comment]
I'll give it a shot—probably later today or tomorrow.

**Comment by novemberborn** [comment]
:+1: on the approach outlined by @jamestalmage. The main process will notice the test dying and log the error, and we get to use Node's error logging which includes the actual file.

**Comment by ecowden** [comment]
Just checked out the fix and it's giving the stack trace I'd expect. Thanks! :+1:
