### ISSUE TITLE
Testing on a web browser

### ISSUE THREAD

**Issue by raisen** [sindresorhus/ava#314]
Should I be able to write tests that run on a browser (Chrome)? I'm writing an application that uses chrome.* and some Web APIs like DOMParser, so mocking all these methods would be kind troublesome.
If it's possible to run on a browser, do I have to run `browserify` every time I need to run the tests in order for the `require` statements to work?

**Comment by vdemedes** [comment]
At the moment, AVA can not be run in browser by default. We are definitely looking to support that in future, so I think I can surely say we should expect this feature to land by 1.0.

Closing it in favor (and as a duplicate) of #24.
