### ISSUE TITLE
Change weird `false fail false` message.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#315]
See here: https://github.com/sindresorhus/ava/pull/313#discussion_r46928584

Calling `t.fail()` gives a really odd message `false fail false`. It should be better.

**Comment by sotojuan** [comment]
What would be better? Also I'm trying to look where that message is generated, but can't seem to find it. Seems like this would be an easy fix!

**Comment by jamestalmage** [comment]
```js
import test from 'ava';

test(t => t.fail())
```

**Comment by sotojuan** [comment]
Ah so it's an internal thing.

Is something like this better? Got it working.

```javascript
import test from 'ava';

test(t => t.fail('I failed fast!'));
```

**Comment by jamestalmage** [comment]
> Ah so it's an internal thing.

Not sure what you mean. `false fail false` is the message AVA generates if you use `t.fail()`

> Is something like this better?

I believe `t.fail(message)` should already show the custom user-provided message. The problem is the default message becomes `false fail false` which is really useless.

I think the solution is simply defining a default message [here](https://github.com/sindresorhus/ava/blob/master/lib/assert.js#L33)

```js
x.fail = function (msg) {
    msg = msg || 'some better message';
    test(false, create(false, false, 'fail', msg, x.fail));
};
```

**Comment by sotojuan** [comment]
> false fail false is the message AVA generates if you use t.fail()

That's what I meant! I thought "false fail false" was something someone wrote, not something AVA generated. 

So I guess a better message would just be "Test failed" or "Assertion failed"? Let me know!

**Comment by jamestalmage** [comment]
Maybe: `Test failed via t.fail()` ?

I think it's best the message includes a hint that `t.fail()` was used. A simple "Assertion failed" would be confusing if the test contained multiple other assertions in addition to `t.fail()`

**Comment by sotojuan** [comment]
That sounds good. I'll send the PR in a few minutes.
