### ISSUE TITLE
Improve passing data to forked processes

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#318]
From: https://github.com/sindresorhus/ava/pull/296#discussion_r47034570

Currently we just proxy the CLI args [manually](https://github.com/sindresorhus/ava/blob/ff5b8dfa5cc9c49a0919c9cad0896cb9c3e971ee/api.js#L45-L57). We should instead just JSON.stringify all the data we want to pass and pass it as the only argument.

**Comment by vdemedes** [comment]
Or we could just pass `process.argv.slice(2)` to the fork process?

**Comment by sindresorhus** [comment]
@vdemedes Sure, but now all the places we use those things have to do an additional argument parsing. Even worse when we want to send arrays and more complex data structures down to the child process, like with the `--require` PR. Would be much nicer if anywhere we wanted to use the info from the parent process we could just `JSON.parse(process.argv.slice[2])`.

**Comment by vdemedes** [comment]
Either way is good for me ;)
