### ISSUE TITLE
Fix flaky AppVeyor test

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#335]
We still have [one test](https://github.com/sindresorhus/ava/blob/f03e4ba2ee2f2f4477ccf7a186d018e09edf0123/test/cli.js#L23-L65) that remains [flaky on AppVeyor](https://ci.appveyor.com/project/sindresorhus/ava/build/547/job/hhivjx4grpxlchnh#L1226).

@sotojuan - Is there any reason we can't turn this into a API test?

That one test accounts for something like 9 out of 10 false negatives on AppVeyor.

**Comment by jamestalmage** [comment]
Now it is even failing on Travis: https://travis-ci.org/sindresorhus/ava/jobs/96899493#L996

**Comment by sotojuan** [comment]
Should be trivial to make it an API test since the output it's testing is also inside the `api` object. I'm watching a film right now but I'll give it a go afterwards unless someone wants to fix it now.

**Comment by jamestalmage** [comment]
All you.

**Comment by sotojuan** [comment]
@jamestalmage Do you know if this is fixed? Guess we have to wait and see if people's tests pass.

**Comment by novemberborn** [comment]
Can't recall any recent AppVeyor flakiness. Closing.
