### ISSUE TITLE
Missing test fixture

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#339]
Occurs in latest master.

<img width="960" alt="screen shot 2015-12-15 at 4 47 16 pm" src="https://cloud.githubusercontent.com/assets/697676/11815368/9d0393a0-a34b-11e5-9611-11e9f55e39d3.png">

**Comment by sotojuan** [comment]
Actually that's just output from the `rejects on error and streams output` test in `fork.js`, which tests the error output when given a nonexistent file. While we test for the correct message in the `err` object, the `fork` function logs the `ENOENT` error to the console. It's expected and not a "real" error! That said if you know of a way to suppress that output, I'd be happy to implement it. Maybe with [hook-std](https://github.com/sindresorhus/hook-std)?

**Comment by sindresorhus** [comment]
>  the fork function logs the ENOENT error to the console.

It definitely shouldn't do that. Might be an exception leak somewhere that don't catch in any promises.

**Comment by sotojuan** [comment]
Makes sense. I'll look into it.

**Comment by jamestalmage** [comment]
This is a byproduct of https://github.com/sindresorhus/ava/issues/308. We are intentionally delaying the installation of our own `uncaughtException` handler so that the correct location for the SyntaxError will be printed. That has the unfortunate side effect of meaning we lose control of when those errors print.

I think @sotojuan's first instinct was correct. Use `hook-std` to mask the error for that particular test.

**Comment by ariporad** [comment]
I'll look into this.

**Comment by jamestalmage** [comment]
Please read #308. There is no "fixing" this beyond suppressing stderr/stdout for this one test fixture using `hook-std`. Our options are:

1. catch and display the error yourself (i.e. maintain control)
2. See the correct source/line number for syntax errors.

2 is more important. We are choosing the lesser of two evils

**Comment by ariporad** [comment]
@jamestalmage: I know.

After some debugging, I found out that somehow the child process bypasses the parents stderr, as I've tried hook-std, several other npm packages, and several implementations that I've done myself, and none have worked.

**Comment by jamestalmage** [comment]
Extend `fork.js` to allow us to pass custom options to `child_process.fork`.
Then use `stdio` option and provide a stream we can inspect. `[null, stdout, stderr]`

**Comment by ariporad** [comment]
@jamestalmage: Tried that. Didn't work. Tried just manually passing in 'ignore'. Didn't work. My theory is that `fs` overrides the options passed to `fork`, in an evil fashion.
