### ISSUE TITLE
How should the test interface be configured?

### ISSUE THREAD

**Issue by mdibaiee** [sindresorhus/ava#34]
Currently we don't have any options, no configuration, but we will need such thing as we go further.

As @sindresorhus said in [this comment](https://github.com/sindresorhus/ava/issues/31#issuecomment-136953972) we can read CLI arguments using `process.argv`, but there should be a real API for configuring test interface, like this:

```javascript
var test = require('ava');
test.config({ fullTrace: true });
```
If we have this, we can extend the config with CLI arguments. Individual tests' configurations should override CLI arguments.

Blocks #29 #31 

@sindresorhus Please label as question.

**Comment by sindresorhus** [comment]
I don't think I made myself clear enough in that thread. The `debug` flag is something we will handle internally, not every user. It will be passed to the [`Runner`](https://github.com/sindresorhus/ava/blob/61cbdbe92d9b8ad0904317736a9672c15dfe7b55/lib/runner.js#L8) which will handle the changes, like making everything serial. The public interface should be as simple and config-less a possible.

**Comment by mdibaiee** [comment]
@sindresorhus Then how should we check for flags inside test interface? Probably a helper function like this?

```javascript
function hasFlag(key) {
  return process.argv.indexOf(`--${key}`) > -1 || process.argv.indexOf(`-${key}`) > -1;
}
```

**Comment by sindresorhus** [comment]
Yes, we can just use something like [`has-flag`](https://github.com/sindresorhus/has-flag).
