### ISSUE TITLE
--require shouldn't be relative to the test.

### ISSUE THREAD

**Issue by ariporad** [sindresorhus/ava#343]
Hi All, I'm back!

I just wanted to mention that the `--require` argument is relative to the directory of the test, not the directory you're calling it from. This is different from basically everything else, so you might want to change it. (Or not).

If someone could point me in the right direction, I'd be happy to make a PR.

Thanks!

**Comment by jamestalmage** [comment]
Yep, sounds like a bug.

We do change `process.cwd` to match that of the test file, but that should not affect the `--require` flag. The solution would be to resolve them to absolute paths in `api.js`.

PR welcome. Please make sure to include a test that fails before / passes after your changes.

**Comment by ariporad** [comment]
Closed by #346.
