### ISSUE TITLE
JSX + Babel support

### ISSUE THREAD

**Issue by sporto** [sindresorhus/ava#35]
Would love to use ava with React, JSX and babel

I don't see any option to provide a custom compiler like Mocha, is there one?

**Comment by sindresorhus** [comment]
Built-in Babel support is about to land in https://github.com/sindresorhus/ava/pull/23. You'll then be able to use ES2015 and JSX without doing anything extra. You can of course supply your own Babel version if wanted.

However, I'm not interested in providing support for custom compilers. AVA is opinionated.

**Comment by sindresorhus** [comment]
Babel support landed in AVA 0.2.0.
