### ISSUE TITLE
Performance issues after Babel 6 upgrade

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#351]
Since babel 6 upgrade the performance is seriously ****ed up. Using master branch and the following test file:

```js
var test = require('./');

test('wow', t => {
	t.true(true);
});
```

```
$ time ava example.js
ava example.js  4.04s user 0.39s system 101% cpu 4.344 total
```

Running it for like 10th time and getting the same results.

Would be great if someone else confirmed this.

**Comment by sindresorhus** [comment]
Confirmed.

```
~/dev/ava master*
❯ time ava example.js

  ✔ wow

  1 test passed


real	3.46s
user	3.21s
sys	0.32s
```

**Comment by sindresorhus** [comment]
If I run `npm dedupe` and then try again it's faster.

```
❯ time ava example.js

  ✔ wow

  1 test passed


real	1.40s
user	1.30s
sys	0.14s
````

**Comment by sindresorhus** [comment]
Babel 6 is a lot more modular, so that might be where all the overhead comes from. Using npm@3 would also be faster (since it dedupes by default).

**Comment by vdemedes** [comment]
Then we are stuck with initial delay on every test run. Not good.

**Comment by vdemedes** [comment]
I think the solution to this is to cache babel's output. There already was some development in that direction in #189, but left incomplete.

My proposal is to cache transformed code based by md5 of original source code. That way, we don't even need to `require('babel')`, when test files don't change. When md5 changes, load babel and re-transpile source code.

This should improve performance.

**Comment by jamestalmage** [comment]
> using npm 3

That is basically a requirement of Babel 6. `npm dedupe` is the only other option.

> caching

 I just finished implementing much the same for `nyc` with very good results.  It's part of my plan after I land #349

**Comment by vdemedes** [comment]
Seems like #349 will take good amount of time. I can implement cache now and send a quick PR, so that we can do a release with babel 6 within next few days.

**Comment by sindresorhus** [comment]
This can be closed now, right?

**Comment by vdemedes** [comment]
Yep, #352 got it covered.
