### ISSUE TITLE
Ignore fixtures and helpers

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#355]
How about ignoring by default `fixtures` and `helpers` directories, so that we don't force `_` prefixes on people?

**Comment by sindresorhus** [comment]
:+1:

**Comment by sotojuan** [comment]
Would this just mean adding something related to those directories [here](https://github.com/sindresorhus/ava/blob/master/api.js#L197)? If so I can work on this during my flight.

**Comment by sindresorhus** [comment]
@sotojuan Yes, and needs to be documented.

**Comment by gajus** [comment]
How to make an exception? (disable this behaviour)

**Comment by vadimdemedes** [comment]
@gajus Why would you want to disable it?

**Comment by gajus** [comment]
Because I want to structure my test folder hierarchy to mirror the project hierarchy. My project has folder `helpers` that I want to test.

**Comment by novemberborn** [comment]
@gajus we need some changes to our globbing to make this happen. See #736 and https://github.com/avajs/ava/issues/736#issuecomment-228608287.

**Comment by gajus** [comment]
It is a bit arrogant of "ava" to assume that "helpers" is a folder that will be used exclusively by the test runner. Instead of changing the globbing pattern, change the folder name to "avahelpers".

**Comment by novemberborn** [comment]
One could argue the same for assuming `test/*.js` folders contain AVA tests. We think it's a good default, and there is an open issue that would make it possible for the `test/helpers` folder to *not* be treated as containing helpers.
