### ISSUE TITLE
Still getting babel error : (

### ISSUE THREAD

**Issue by jenius** [sindresorhus/ava#358]
I am probably doing something dumb here so apologies for taking your time, but I simply cannot figure out what it is.

Fresh project, Babel 6, es2015 preset, and ava installed as dev dependencies:

```json
"devDependencies": {
    "ava": "^0.8.0",
    "babel-core": "^6.3.26",
    "babel-preset-es2015-node5": "^1.1.1"
  },
```

Get the `.babelrc` in order, load up the right preset.

Make a new test file, nice and simple to see if it works:

```js
import test from 'ava'

test('wow', (t) => {
  t.same('foo', 'foo')
})
```

Get this error, which seems like it was happening before `v0.8.0` landed, triple checked `package.json` and I have the latest versions of both babel and ava installed.

```
ReferenceError: [BABEL] xxx/test/index.js: Unknown option: xxx/.babelrc.presets
```

Any idea what I'm missing?

**Comment by jamestalmage** [comment]
It is finally fixed here: https://github.com/sindresorhus/ava/commit/94797b10386e8d638a9efd09a9b8d08dc9481ac6

... 

for real this time.

...

I think! :smile:

- 
Note that if you want to use `master`, it's upgraded to Babel 6. You absolutely should (darn near must) upgrade to `npm@3` to use Babel 6. Your only other choice is `npm install && npm dedupe` every time you want to change dependencies.

**Comment by jenius** [comment]
Ok, I'll use master for now. Ping this issue and close when it's released so I know? I am on `3.x` for npm :grinning:

**Comment by jenius** [comment]
Just for the record, everything worked fine using master. Thanks! :tada:

**Comment by portgasd666** [comment]
I didnt get how I'm supposed to fix this. Can someone help ? Thanks.

**Comment by krasimir** [comment]
@portgasd666 Instead of setting the following in your `package.json` file:
```
"ava": "0.8.0"
```
you may use:
```
"ava": "git+https://github.com/sindresorhus/ava.git#master",
```

However, that's not really a good idea since you are going to get the very latest thing every time when you run `npm i`. So I hope (@jamestalmage) that the change which is now in master will go in the next released version.

**Comment by portgasd666** [comment]
Oh okay, thanks mate !

**Comment by sindresorhus** [comment]
You should not depend on `master` as it's a moving target. Instead depend on the latest commit:

```
"ava": "sindresorhus/ava#65ae07c",
````

**Comment by krasimir** [comment]
@sindresorhus good point!

**Comment by vdemedes** [comment]
I assume it's safe to close this?

**Comment by jenius** [comment]
Has the issue been resolved on a stable release of `ava`? If not I might keep it open until that point :grinning:

**Comment by sindresorhus** [comment]
@vdemedes Lets just keep it open until we have a new release so we don't get a bunch of duplicate issues when people encounter this.

**Comment by maboiteaspam** [comment]
side note, using `"ava": "sindresorhus/ava#65ae07c"` as a dependency, i can work using the local bin, ie : `node node_modules/.bin/ava` instead of `ava`. 
As secondary side node, same sentence for `xo`. The global bin would not work properly.

**Comment by jamestalmage** [comment]
make sure you have a recent version of AVA installed globally. The global CLI commands actually default to the local installs. With a current global install, you should see no difference between `ava` and `node_modules/.bin/ava`.

**Comment by sindresorhus** [comment]
Closing as a new release is out. https://github.com/sindresorhus/ava/releases/tag/v0.9.0

**Comment by jenius** [comment]
Thanks for the awesome work guys. You are the best :tada:
