### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dfcreative** [sindresorhus/ava#367]
Hello!
Thanks for the wonderful runner. Mocha really seems to be a pain when it comes to running tests in browser.
But there are UX issues with ava, which made my friend upset.
1. _Installing time_. For mocha, it takes about 4-5 times less to install than ava. Is there a sense in _prepublish_ script, which just compiles all the thing and publishes the bundle? What are the reasons not to?
2. _Launching time_. It feels 2-3 times slower than mocha to run `ava` via `npm test`, on the latest node (5.3.0). That UX is really to the contrary of the described in readme, I really anticipated the opposite.
3. _Default formatter_. The third great frustration is that mocha by default writes the essence of debugging info - code lines, if tests failed. Ava just soaks up all the debugging juice, leaving with the fact that there is a mistake, making itself useless in debugging. Installing and testing various reporters is not really an option, the default behavior is expected to be at least not worse than mocha.
4. _It crashes beefy_. It does not seem to be ava’s issue ([beefy started dong so a while ago](https://github.com/chrisdickinson/beefy/issues/99)), it is just unmet expectation. The killer-feature, I thought, for ava, would be able to launch tests in browser like `beefy test.js`, which is super-awesome comparing to the way mocha does browser tests. But it crashes beefy, mocha does not...

Sorry for that, thank you for understanding and hope you will find use in these complaints.

**Comment by jamestalmage** [comment]
> browsers... 

AVA does not (yet) support browser side testing.

> install time

Mocha doesn't ship with Babel or power-assert, we do.

> Launching time.

Make sure you use `npm@3` to install. Babel loads slow on `npm@2`. Transform caching is coming - major speed bump. Babel is always going to introduce extra startup delay.

> Default formatter.

I need more details before responding. Got a sample program and stack trace?

**Comment by sindresorhus** [comment]
1. The biggest overhead in installing is installing Babel, but that's also AVA's greatest strength. The ability to use ES2015+ syntax and features while still supporting old Node.js versions. Bundling everything into one file would make startup a LOT slower as the whole file would have to be parsed on startup.
2. I would like to see some numbers on that claim, but the gain on AVA is not for tiny test files, but larger ones. Tests doing a lot of IO will have the biggest gain. Although, we have worked hard on performance lately and the next AVA version has caching, which will help a lot on the startup time. Version after that will improve even more. The launch overhead is mostly caused my transpiling the test files with Babel.
3. Unclear what you're missing here? We output detailed failing assertions and the stack. We don't yet do diffing, but you can achieve that by using a 3-party reporter using the new `$ ava --tap` option (in the next version).
4. Not browser support yet.

**Comment by dfcreative** [comment]
I wanted to switch to ava in [audio-buffer-utils](https://github.com/audio-lab/audio-buffer-utils), but will wait for a moment. `var test = it`. found it way for now :)
3. Example test.js:
```js
var test = require('ava');

function f () {
	xxx
}

test('xxx', function () {
	f()
});
```
Running ava:
![image](https://cloud.githubusercontent.com/assets/300067/12004585/a31fa172-ab32-11e5-81b7-6c35194009f7.
It is git bash in windows 7, that may be an issue, IDK. Mocha goes like 
![image](https://cloud.githubusercontent.com/assets/300067/12004588/d7f8e3b8-ab32-11e5-946d-8152b3c62254.png)

**Comment by jamestalmage** [comment]
I think that is an AVA bug. We don't print stack traces if it's not an assertion error. The fix for that is already in development.

**Comment by vdemedes** [comment]
The fix for stack traces is already in master ;)

**Comment by ariporad** [comment]
@dfcreative, can this be closed?

**Comment by dfcreative** [comment]
Sure, if each notice is known. Thank you.

**Comment by jamestalmage** [comment]
@dfcreative `0.10.0` is out and should improve on issues `2` (startup time) and `3` (output formatting)
