### ISSUE TITLE
Create error class for internal errors

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#368]
From https://github.com/sindresorhus/ava/pull/359#issuecomment-167261434.

So we can disable the stack output for them.

Should checked for here: https://github.com/sindresorhus/ava/blob/e52db69261d9b15dd1b69c76d82875b66d024e6b/cli.js#L99

**Comment by ariporad** [comment]
@sindresorhus: Why not just do `delete error.stack`?

**Comment by sindresorhus** [comment]
@ariporad Seems cleaner to use an error subclass as it can be detected as such. Normal errors are expected to have a `.stack` property.
