### ISSUE TITLE
Generators support

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#37]
Would be very useful and insanely cool, if AVA supported generators by default. I am ready to implement this right away. What does everyone think of that?

**Comment by sindresorhus** [comment]
What does that entail? Can you show an example test of how it would look? What changes would need to be made in AVA?

**Comment by vdemedes** [comment]
Sorry, should've clarified things more. No major changes are required to make this work and the API would remain exactly the same.

Example test with generators:

```js
const test = require('ava');
const fs = require('mz/fs'); // promisified fs

test('generator support', function * (t) {
  let content = yield fs.readFile('/path/to/some/file', 'utf-8');

  t.same(content, 'expected content of the file');
});
```

To support generators, [co](https://npmjs.org/package/co) module would be used, because it's the most mature and simple. I've been using it for almost a year now and never encountered any issues.

Also, because Ava already supports promises, I expect generator support to be very easy to add, because `co` returns a simple promise to run a generator function:

```js
const co = require('co');

function * exampleTest () {
  // body of generator function
}

// to run a generator, simply pass it to co
co(exampleTest).then(function () {
 // generator function completed execution
}).catch(function (err) {
  // generator function threw an error
});
```

**Comment by vdemedes** [comment]
I believe I will have some free time to build a PR today

**Comment by vdemedes** [comment]
As a workaround, I currently do the following:

```js
const ava = require('ava');
const co = require('co');

test ('generator fn', function * (t) {
  // wow
});

function test (title, fn) {
  ava(function () {
    return co(fn.apply(null, arguments));
  });
}
```

**Comment by tunnckoCore** [comment]
It would be easy if use `async-done` + `co` combo under the hood. But if it's done, we should forget "sync" test - in which i dont see value and dont see problem. But also with that it comes other problem - assertion, it cant stay as it is now (passing `t` to the test) - in which, again, i dont see problem, because this would be possible

```js
var test = require('ava');

// which would be just `claim`
var assert = test.assert;

// or you can just use any other assertion library
// by requiring it.

test('foo bar', function (done) {
  assert.true(true, true)
  done() // like `t.end()`
})
```

Or default (builtin) assertion can be in the context of the test function - i chose that way and built `benz` - which is thin layer on top of `async-done` and `now-and-later` (tools behind `undertaker`) with passing custom context.

**Comment by sindresorhus** [comment]
@vdemedes Still not sure what's needed to do in AVA. Would AVA have to have `co` as a dependency? With the recent builtin ES2015 support, wouldn't generators just work out of the box? AVA already support promises, which is what `co` returns.

**Comment by vdemedes** [comment]
@sindresorhus 

    What's needed to do in AVA?

AVA would need to detect if a test is a generator function using [is-generator-function](https://www.npmjs.com/package/is-generator-function) and if it is, convert it to a promise using `co`. And that's it, since AVA already supports promises.

    Would AVA have to have co as a dependency? 

Yes, `co` would need to be added as a dependency.

    With the recent builtin ES2015 support, wouldn't generators just work out of the box?

Nope, they wouldn't and here's why ;) Generators are just functions that can be run step-by-step:

```js
function * generator () {
  yield 1; // blocks until .next() is called
  yield 2; // blocks until .next() is called
  yield 3; // blocks until .next() is called

  // all done
}

let fn = generator();

fn.next().value; // 1
fn.next().value; // 2
fn.next().value; // 3
fn.next().value; // undefined, function completed
```

This functionality in its "plain" form does not give us many benefits, but the brilliant `co` library uses generators to allow writing **asynchronous code in a synchronous style**. Normally, you would pass generators to `co`, but it can also accept promises:

```js
const co = require('co');

function * generatorFn () {
  return 'some value';
}

function promiseFn () {
  return Promise.resolve('some value');
}

// yield does not work outside of generators
co(function * () {
  let first = yield generatorFn(); // 'some value'
  let second = yield promiseFn(); // 'some value'
});
```

In practice, generators allow me to avoid code like this:

```js
User.findOne({ email: 'test@test.com' })
  .then(function (user) {
    let name = user.get('name');

    console.log('My name is', name);
  })
  .catch(function (err) {
    // error
  });
```

and write code like this:

```js
try {
  let user = yield User.findOne({ email: 'test@test.com' });
  let name = user.get('name');

  console.log('My name is', name);
} catch (err) {
  // error
}
```

**Comment by sindresorhus** [comment]
Hmm, wouldn't it be better to enable the [async/await](https://github.com/lukehoban/ecmascript-asyncawait) Babel [transformer](https://babeljs.io/docs/advanced/transformers/)? `async/await` is the future of async programming, not hacked up generators.

**Comment by vdemedes** [comment]
The thing is, nobody uses async/await yet and god knows when it will land in node.js. But generators are widely used today and there are many packages for them. There is also a wonderful [Koa](http://koajs.com) framework, specifically for apps that use generators.

Also, it will not add any overhead to AVA, because the implementation would be fairly trivial. I will send a PR later today to demonstrate this, so you can see the end result ;)

**Comment by sindresorhus** [comment]
Alright. PR welcome :)

**Comment by tunnckoCore** [comment]
> The thing is, nobody uses async/await yet and god knows when it will land in node.js.

:+1: 

One fairly simple and built in seconds test runner, built on `benz`, showing its power and flexibility.

```js
'use strict'

var Benz = require('benz')
var util = require('util')

function Runner (options) {
  if (!(this instanceof Runner)) {
    return new Runner(options)
  }
  Benz.call(this, options)
  this.tests = {}
}

util.inherits(Runner, Benz)

Runner.prototype.test = function (name, fn) {
  this.tests[name] = fn
  return this
}
Runner.prototype.start = function(done) {
  // series by defaul,
  // pass `.enable('parallel')` for parallel execution
  this.run(this.tests)(done)
};

var count = 0
var contents = ''
var fs = require('mz/fs')
var foobar = new Runner()

foobar
.option('context', require('claim'))
.option('generatorify', require('co').wrap)
// .enable('parallel')
.test('foo bar', function (next) {
  this.same(count, 0)
  console.log('foo bar')
  count++
  next()
})
.test('baz qux', function (next) {
  this.same(count, 1) // try change it and it will throw
  console.log('baz qux')
  count++
  next()
})
.test('generators', function * (next) {
  this.same(count, 2)
  contents = yield fs.readFile(__filename, 'utf-8')

  // little tweak,
  // will fix it in core
  yield function () {
    next()
  }
})
.test('test content', function (next) {
  this.true(contents.indexOf('Runner') !== -1)
  console.log('test content')
  next()
})
.start(function (err, res) {
  if (err) return console.log(err)
  console.log(res)
  console.log('end')
})
```

**Comment by vdemedes** [comment]
@tunnckoCore I am not completely sure what is all this complexity for, if generator support could be added in a few lines:

```js
if (isGenerator(fn)) {
  fn = co(fn);
}
```

**Comment by MadcapJake** [comment]
Generators don't have good stack traces though.  Also, `async/await` is cleaner looking and is easier to read.  @vdemedes how are you thinking they would be used in a test?

**Comment by vdemedes** [comment]
@MadcapJake yield with `co` is basically the same as async/await:

```js
function promiseFn () {
  return Promise.resolve('some value');
}

async function asyncFn () {
  return Promise.resolve('some value');
}

yield promiseFn(); // 'some value'
await asyncFn(); // 'some value'
```

You would use generators in a test just like you are using promises or anything else now, nothing is changing really:

```js
test ('content of the file', function * (t) {
  let content = yield fs.readFile('/path/to/file', 'utf-8');

  t.same(content, 'expected file content');
});
```

**Comment by tunnckoCore** [comment]
> @vdemedes: added in a few lines

yes it can. im just showing how can be done one simple runner with absolute flexibility, low dependencies and working out of the box with all kind of things - generators, promises, callbacks, series and parallel flow, pluggable assertion library and context (which context can be used for sharing contents and/or hooks and timeout as in mocha for example) and sweet controling options, with can be driven by cli.

**Comment by Qix-** [comment]
[![enhanced-25942-1427414324-7](https://cloud.githubusercontent.com/assets/885648/9796235/57dc4126-57b2-11e5-8e1f-3af91a98425e.jpg)](https://www.youtube.com/watch?v=NuEIsqeRR1o)
---

If we're going to add support for this, we should definitely include `async`/`await`. If we want to be realistic about it, can't we **also** support coroutines? I would personally prefer the standard way, and we're already depending on babel.

---

[![vfzso](https://cloud.githubusercontent.com/assets/885648/9796263/80062c7a-57b2-11e5-9399-ca6f55d90b68.gif)](https://www.youtube.com/watch?v=NuEIsqeRR1o)

**Comment by sindresorhus** [comment]
@Qix- See: https://github.com/sindresorhus/ava/issues/45#issuecomment-139216416

**Comment by Qix-** [comment]
:+1:

**Comment by vdemedes** [comment]
And we also need to disable `regenerator` transform in `babel` to not convert generators into some ES5 crap.
