### ISSUE TITLE
A quick question about the issue tracker.

### ISSUE THREAD

**Issue by ariporad** [sindresorhus/ava#377]
Hi All,

I'm not sure if I'm allowed to do this (since I'm new and not an official contributor), so let me know and I'll shut up.

Would it be possible to get a `blocked` label (or maybe a milestone)? And maybe a `taken` one (Or just use the assign feature)? That would make it more immediately obvious which issues to try and tackle and which to ignore (via searching "is:open is:issue -label:blocked no:assignee").

Thanks!

**Comment by sindresorhus** [comment]
> I'm not sure if I'm allowed to do this

You're allowed to ask about anything. That applies to anyone reading this issue tracker.

> Or just use the assign feature

I added you to the repo so you can assign yourself stuff and handle issues, but don't commit directly to master ;) We should be better at using the assign feature. Feel free to go through the issue tracker and add labels where appropriate.

> Would it be possible to get a blocked label

Just added it https://github.com/sindresorhus/ava/labels/blocked.

**Comment by sindresorhus** [comment]
Any other feedback to our process welcome :)

**Comment by ariporad** [comment]
Thanks @sindresourhus!

And no one should **_ever_** commit on master. GITHUB FLOW FTW!!!!!

**Comment by sindresorhus** [comment]
> Also, should do you prefer internal branches or forks?

Use your fork for now.

**Comment by ariporad** [comment]
Sounds great. Thanks again!
