### ISSUE TITLE
Support for global variables

### ISSUE THREAD

**Issue by juanpr2** [sindresorhus/ava#382]
I'm trying to test a component that is based on leaflet, but I get the following error:
```
xxx/app/node_modules/leaflet/dist/leaflet-src.js:9168
}(window, document));
  ^

ReferenceError: window is not defined
...
```
All other tests that don't require leaflet pass.
I suppose AVA doesn't support browser global variables; will there be support for these in the future?
Is there currently a workaround?

**Comment by ariporad** [comment]
@juanpr2: It looks like your tests are for browser code, (leaflet is for the browser too). AVA currently doesn't support browsers, it currently runs in node. It's not really that we don't support browser globals, _per se_, it's just that we don't yet support running in a browser.

In the future, we're planning to add support for running in the browser, but if you want to test in the browser today, you'll have to use a diffrent test framework.

(The following might be full of stuff you already know, so feel free to ignore it if that's the case.)

I personally like [`mocha`][mocha], but be warned, it's a little different from ava. If you're looking for something similar to AVA,  [`tape`][tape] looks nice. Both of those support browsers. If you want to run code in the browser that uses modules (`require` or `import`), you'll need something like [`browserify`][browserify] or [`webpack`][webpack] (browserify is going to be a lot easier getting started). Then to actually load all this into the browser, you're going to want something like [`karma`][karma] (formerly `testacular`), which takes your tests and lets your easily run them in a bunch of browsers.

Sorry about that, and let me know if you have any other questions

[mocha]: https://mochajs.org/ "Mocha"
[tape]: http://npm.im/tape "tape"
[browserify]: http://browserify.org/ "Browserify"
[webpack]: http://webpack.github.io/ "Webpack"
[karma]: http://karma-runner.github.io/ "Karma (Formerly Testacular)"

**Comment by sindresorhus** [comment]
You can follow https://github.com/sindresorhus/ava/issues/24 regarding browser support.
