### ISSUE TITLE
Regression: 0.9.0 Not marking tests as failed

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#386]
Output on `0.8.0`

<img width="811" alt="screenshot 2015-12-29 07 17 28" src="https://cloud.githubusercontent.com/assets/4082216/12034261/9d0b8d2e-adfc-11e5-88a0-4cb65b352849.png">

`0.9.0` with `--verbose` flag

<img width="650" alt="screenshot 2015-12-29 07 18 42" src="https://cloud.githubusercontent.com/assets/4082216/12034266/b1536680-adfc-11e5-8b34-7feff593836a.png">

`0.9.0` with minimal reporter

<img width="608" alt="screenshot 2015-12-29 07 19 04" src="https://cloud.githubusercontent.com/assets/4082216/12034267/bd7b9766-adfc-11e5-9067-f43103eae03f.png">

In all cases, the test exits correctly with a non-zero error code.

All the above output is generated from this commit: https://github.com/jamestalmage/loud-rejection/commit/432b4fb3657ec4af407f4098ee80ff727e1c0d13

It uses `ava@0.8.0` by default, you will need to install `ava@0.9.0` to monitor the other outputs.

**Comment by vdemedes** [comment]
The bug is related to regenerator. Try surrounding https://github.com/jamestalmage/loud-rejection/commit/432b4fb3657ec4af407f4098ee80ff727e1c0d13#diff-1dd241c4cd3fd1dd89c570cee98b79ddR176 with try..catch and `console.log(err)`. It outputs `1` (number).

**Comment by vdemedes** [comment]
And it outputs `1`, because of this -> https://github.com/jamestalmage/loud-rejection/blob/432b4fb3657ec4af407f4098ee80ff727e1c0d13/test.js#L17. It rejects/resolves with exit code, not with `Error`.

**Comment by vdemedes** [comment]
Actually, this thing was caused by https://github.com/sindresorhus/ava/commit/945dbea40a6a500a24d54ebcc7e10dcd75647fc7#diff-dd2e881af3311f834199c7b515cff0c7L128.

So, promises need to reject with `Error`s.
