### ISSUE TITLE
await t.throws is not waiting

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#391]
Hi

The latest tests of the [delay](https://github.com/sindresorhus/delay) module are not working as you can see in this [travis](https://travis-ci.org/sindresorhus/delay/jobs/99394818) report.

I investigated it and I noticed some weird stuff was going on with the [`x.throws`](https://github.com/sindresorhus/ava/blob/master/lib/assert.js#L69) method.

```js
test('returns a rejected promise', async t => {
	console.log('start');
	await t.throws(fn.reject(50, new Error('foo')), 'foo');
	console.log('done');
});
```

I added an extra log in the [`setTimeout`](https://github.com/sindresorhus/delay/blob/master/index.js#L25-L27) method of the delay module. This is the output:

```
start
done
setTimeout
```

Does anyone has an idea how this is possible? I will try to add a failing test with the `delay` module.

**Comment by SamVerschueren** [comment]
It's actually hard, or maybe impossible, to write a failing test for this as it might be `Babel` related.

So here is a small code snippet

```js
import test from 'ava';

function delay() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            reject(new Error('foo'));
        }, 500);
    });
}

test('await', async t => {
    const start = Date.now();
    await t.throws(delay, 'foo');

    t.true(Date.now() - start > 500);
});
```

which results in

```
  1. await
  Missing expected exception..
  AssertionError: Missing expected exception..
```

**Comment by sindresorhus** [comment]
Probably related to https://github.com/sindresorhus/ava/pull/360. You no longer need to `await` `t.throws`.

**Comment by SamVerschueren** [comment]
That indeed solves the issue in my first post. Refactored the tests and now they are working correctly. My second post actually looks like another issue. Closing this one and will create a new issue. Have to investigate first.

**Comment by SamVerschueren** [comment]
The code snippet of my second post is wrong, that's why it wasn't working. It had to be `t.throws(delay(), 'foo')`.
