### ISSUE TITLE
ES2015 / babel-core through options only

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/ava#40]
It's too big to be in the core of AVA and think it should be available only through option like `--esnext` or something like that. Then user just will install it only if they write in ES2015.

```js
if (cli.flags.esnext) {
	try {
		require(resolveFrom('.', 'babel-core/register') || resolveFrom('.', 'babel/register'));
	} catch (err) {
		require('babel-core/register');
	}
}
```

**Comment by sindresorhus** [comment]
The thinking is that you should only write your tests in ES2015. It's time. We finally have a good transpiler (Babel). You can of course write your tests in ES5, but I want to optimize for the future, not the past. Providing this out of the box without requiring the user to do anything is one of the things that is going to set AVA apart.

I agree Babel is a large dependency, but that's less of an issue for devDependencies. I'm also going to work on getting down the size of the Babel package. Help welcome there ;)

I see that the Babel package currently includes a lot of junk you don't need in Node. The package is 13.6 MB. I think with some tweaks we could get it down many MBs. Removing browser specific stuff brings it down to 9.8 MB (Maybe Babel should have a Node specific package without those?). There's also some potential for better deduping. I'll open a Babel issue about that when I have some more time to look into it.

**Comment by tunnckoCore** [comment]
Actually yes, maybe you have right and it looks that installing it one time globally is the way. But I think it's not cool, when someone want to do PR and must install it (if he dont use ava).

**Comment by sindresorhus** [comment]
Babel 6 is out and it's smaller, and it will be even smaller with https://github.com/babel/babel/pull/2659/files and https://github.com/babel/babel/issues/2635. Closing this, but I'm going to continue working on bringing down the dependency size.
