### ISSUE TITLE
Add a config file.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#405]
Probably just an `ava` section in `package.json`.

The available options are getting complex enough that I think we are close to needing this (if we aren't there already).

```json
{
  "serial": true,
  "verbose": true,
  "cache": false
}
```

These would need to be merged with whatever is specified on the command line (command line taking precedence).

The goal is to be able to specify the default way you want it to behave when you simply type `ava` on the command line.

**Comment by sindresorhus** [comment]
:+1: I do that with [XO](https://github.com/sindresorhus/xo#config) too. I would prefer only a section in package.json. Makes things simple.

https://github.com/sindresorhus/pkg-conf

**Comment by ariporad** [comment]
Agreed. I'd also like to add a "files" section, and have it be "config.ava", vs. "ava "

**Comment by sindresorhus** [comment]
> I'd also like to add a "files" section

:+1: 

> and have it be "config.ava", vs. "ava "

:-1: That's a convention nobody uses. Top-level is simpler and it will never conflict with anything anyways.

**Comment by jamestalmage** [comment]
> That's a convention nobody uses

Except for https://github.com/bcoe/nyc/issues/131  :smile:

**Comment by jamestalmage** [comment]
> I'd also like to add a "files" section

Yeah, I think basically any config value is fair game. I can't think of one we *shouldn't* allow them to configure this way.

**Comment by vdemedes** [comment]
Great suggestion, I'm on board!

**Comment by ariporad** [comment]
@sindresorhus: Except `nyc` and `comitizen` (off the top of my head).

**Comment by jamestalmage** [comment]
`nyc` is falling off that list very soon: https://github.com/bcoe/nyc/pull/132

**Comment by kentcdodds** [comment]
Add [`ghooks`](npm.im/ghooks) to the list of modules that use the config convention :-) But meh, it'll never conflict.
