### ISSUE TITLE
Builtin reporters should show skipped test count in the result

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#408]
`21   passed   3 failed` => `21 passed   2 skipped   3 failed`

**Comment by sotojuan** [comment]
What color should it be?

**Comment by kevva** [comment]
No color or yellow imo.

**Comment by sotojuan** [comment]
Sorry I deleted my comment asking about the color because in the tests for the mini reporter it [uses cyan](https://github.com/sindresorhus/ava/blob/master/lib/reporters/mini.js#L29) for skipped.. Though I think for the actual reporting it should be yellow or no color as you say!

**Comment by jamestalmage** [comment]
@sotojuan - are you working up a PR for this?

**Comment by kevva** [comment]
Sorry I deleted my comment asking about the color because in the tests for the mini reporter it uses cyan for skipped.. Though I think for the actual reporting it should be yellow or no color as you say!

Yup,  but I think yellow makes more sense depending on how we want to treat skipped tests as.

**Comment by sotojuan** [comment]
@jamestalmage Yep, working on it now.

**Comment by jamestalmage** [comment]
OK, I've updated the labels so people know someone is working on it.
