### ISSUE TITLE
Testing websockets

### ISSUE THREAD

**Issue by mattkrick** [sindresorhus/ava#411]
I've got some code that looks like this:
```
test(async t => {
  require('./testServer.babel.js'); // set up socket server
  await delay(); // hacky solution for now
  const socket = socketCluster.connect({hostname: 'localhost', port: 40000}); // set up client connection
  await delay(1000); // wait for connection
  socket.emit('foo', 'data', err => {
    t.fail()
  })
});
```

The output is:
```
  1 test passed
  1 unhandled rejection
```
I'm guessing this is because I'm not calling `t.end()` and I'm not in callback mode. But, if I use `test.cb`, then I can't use async/await because promises throw an error, so I'm forced to enter callback hell. Any ideas on the right way to do this? Any clever ways of getting the `delay`s out would be great, too!

**Comment by jamestalmage** [comment]
What is the stack trace of the `unhandledRejection`?

Links to real repos work best :smile:

**Comment by mattkrick** [comment]
Ah, I found a better way to do it. It uses the nice factory function you introduced me to, but now I use it for a server that creates a worker (and a worker has an HTTP server + WS server in it). Still not foolproof, with 3+ tests I occasionally get really strange `EADDRINUSE` errors that point to a temp file in `~/var/folders` (there's a race condition somewhere, but I dunno where).  For the googlers at home: 

```
test.cb('pass through props to container', t => {
  t.plan(1);
  const port = parseInt(Math.random() * 65536);
  const socketOptions = {hostname: 'localhost', port};
  makeServer(() => {
    const socket = socketCluster.connect(socketOptions);
    socket.emit('foo', 'fooData', () => {
      t.pass();
      // close event calls `close` on the websocket in the test server. `t.end()` must come after the worker is closed, otherwise the server can stay open
      socket.emit('close', null , () => {
        t.end();
      });
    })
  }, port);
});
```

I'll leave it open in case someone comes up with a cleaner solution, feel free to close if you want to clean up your issues.

**Comment by novemberborn** [comment]
@mattkrick would be great to have a [recipe](https://github.com/sindresorhus/ava/search?q=recipe&type=Issues&utf8=%E2%9C%93) for testing servers like this.

Closing though as I'm cleaning up the issues :smile:

**Comment by RichardWright** [comment]
As test.cb has been depreciated, is there a new way of doing this now?
