### ISSUE TITLE
False passed runs for the suite

### ISSUE THREAD

**Issue by tusharmath** [sindresorhus/ava#417]
I took the test from the documentation —

```javascript

test.cb('YANKIE', t => {
  t.plan(3)
  setTimeout(() => {
    // t.pass()
    // t.end()
  }, 100)
})

```

Apparently this test is just skipped amidst other tests and thus returns a false passed for the suite. This could be an issue, if the developer forgets to write the `t.end()` in his code.

Or is there something that I am missing?

**Comment by jamestalmage** [comment]
I just tried your test code, and it just hangs indefinitely (which makes sense - AVA is waiting for you to call end). What output are you getting?

**Comment by tusharmath** [comment]
I guess you are right. Its not skipping, instead its waiting for it to complete till eternity. I guess there should be a default timeout for async tests.

**Comment by sindresorhus** [comment]
We decided in https://github.com/sindresorhus/ava/issues/171 not to do a default timeout as there's no good default that fits all, instead we're going to add ability to set timeout.
