### ISSUE TITLE
TAP: Skip count reports `undefined`

### ISSUE THREAD

**Issue by therealklanni** [sindresorhus/ava#423]
```
...etc...
# skip undefined
...etc...
```

What more do you need? I briefly looked at the code surrounding this, and it appears that `TapReporter#api.skipCount` is never tracked. I could be wrong. If I get time to take a deeper look into this and submit a fix, I will do so, however don't let that stop anyone from taking a crack at it sooner! :rocket: 

[Probably related](https://github.com/sindresorhus/ava/commit/a5e63c0d43bfc13b820b3d52727830c3c2354793#diff-22844eb86dced527165902d51876b484R56), also [#140](https://github.com/sindresorhus/ava/pull/410/files)

**Comment by therealklanni** [comment]
@sotojuan please confirm

**Comment by sotojuan** [comment]
Hi, sorry for the late reply. Maybe a check if `api.skipCount` is greater than 0 before adding it to the results would fix it?

I added this to `TapReporter.prototype.finish` in `lib/tap.js`, removing from the `output` array when necessary:

```js
	if (this.api.skipCount > 0) {
		output.push('# skip ' + this.api.skipCount);
	}

	output.push('# fail ' + (this.api.failCount + this.api.rejectionCount + this.api.exceptionCount), '');
```

I also wrote a new test without any skipped tests and checked that information about skipped tests was not printer. It passed.

@sindresorhus Let me know if this is a good solution for this problem. Seems to work!

**Comment by sindresorhus** [comment]
@sotojuan What does the [TAP spec](https://testanything.org/tap-version-13-specification.html) say about it? When there are no skipped tests should it not be outputted or outputted with `0`?

**Comment by sotojuan** [comment]
I don't know much about the spec but if that's what it says then that's a simple change (just output 0 instead of nothing).

**Comment by sindresorhus** [comment]
// @vdemedes

**Comment by azhang** [comment]
I think skip may be broken. I have this:
```js
test.skip('validator (password): block hashedPassword and salt', async t => {
  let credential = new Credential({
    provider: 'local',
    hashedPassword: 'asdf',
    salt: 'asdf'
  })

  let error = credential.validateSync()
  console.log(error)
})
```
but in tap output:
```
TAP version 13
# #authenticate
ok 1 - #authenticate
# #toSafeJSON
ok 2 - #toSafeJSON
# validator (email): valid
ok 3 - validator (email): valid
# validator (email): invalid
ok 4 - validator (email): invalid
# validator (email): non-local but email provided
ok 5 - validator (email): non-local but email provided
# validator (password): non-local but password provided
ok 6 - validator (password): non-local but password provided
# validator (password): minlength
ok 7 - validator (password): minlength
# validator (password): no password provided
ok 8 - validator (password): no password provided
# validator (password): non-string password provided
ok 9 - validator (password): non-string password provided
# validator (password): '' password provided, old credentials
ok 10 - validator (password): '' password provided, old credentials
# validator (password): '' password provided
ok 11 - validator (password): '' password provided
# validator (password): block hashedPassword and salt
ok 12 - validator (password): block hashedPassword and salt

1..11
# tests 11
# pass 11
# skip undefined
# fail 0
```

**Comment by sotojuan** [comment]
@azhang Yup, thanks for the example. It's a simple fix and I have it ready, just need to hear back about the TAP spec for skipped tests.

**Comment by therealklanni** [comment]
According to the spec
>If the whole test file succeeds, the count of skipped tests is included in the generated output.
It seems like it should always output. (Also see fail above reports 0 rather than not reporting at all).

Seems legit?

**Comment by vdemedes** [comment]
I observed that TAP parsers used in many reporters don't always follow the spec or there are many interpretations of what TAP output should look like. I'd suggest including `# skip` only if necessary, but quick manual check with always-on `# skip` output won't hurt.

**Comment by vdemedes** [comment]
I'd just check in some of the most popular reporters and see if they have problems with `# skip 0` always present.

**Comment by sotojuan** [comment]
Tape seems to output [only when there are skipped tests](https://github.com/substack/tape/blob/master/lib/results.js#L132).

**Comment by vdemedes** [comment]
@sotojuan If [tap](https://npmjs.com/tap) also follows this rule, let's stick to it then.

**Comment by sotojuan** [comment]
Seems like tap [doesn't output when there are no skipped tests either](http://i.imgur.com/87eiS7Q.png). Going to go ahead and push a PR.

**Comment by therealklanni** [comment]
[Related](https://github.com/tapjs/node-tap/blob/master/lib/test.js#L882)

**Comment by therealklanni** [comment]
FYI that's not raw TAP output, that's formatted, so I don't think that image is a good reference. However, the source line I posted seems to indicate it skips printing skips unless there was more than 0.
