### ISSUE TITLE
SyntaxError in master branch causing tests to fail

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#425]
Travis: https://travis-ci.org/sindresorhus/ava/builds/102330293

<img width="1061" alt="screen shot 2016-01-14 at 1 13 23 pm" src="https://cloud.githubusercontent.com/assets/697676/12324166/1bb26352-bac1-11e5-8748-16c0acc0d0d5.png">

This is really weird, because the last commit is https://github.com/sindresorhus/ava/commit/c060e94c8a4c69c4c57367e91f793d62475233a4 and tests were passing before that.

**Comment by floatdrop** [comment]
Yeah, maybe we should fix `babel-plugin-transform-regenerator` to `6.3.26` version somehow, as suggested in issue about this - https://phabricator.babeljs.io/T2892 ?

**Comment by nexdrew** [comment]
Having this same problem. [Tests pass](https://travis-ci.org/npm/email-templates/jobs/102221573) with `babel-plugin-transform-regenerator@6.3.26`, [tests fail](https://travis-ci.org/npm/email-templates/jobs/102348734) with `babel-plugin-transform-regenerator@6.4.3`.

The workaround described in the babeljs phabricator link works for me: change `const` to `let` within `async` functions.

**Comment by ewnd9** [comment]
Got it [too](https://travis-ci.org/ewnd9/dictionary-cli/builds/102116475). It also reproduces on local system after clean `npm install`

**Comment by sindresorhus** [comment]
Applied the workaround and released 0.9.2.
