### ISSUE TITLE
TAP support is already here, right?

### ISSUE THREAD

**Issue by zeke** [sindresorhus/ava#426]
The following line is in [one of the FAQs](https://github.com/sindresorhus/ava#why-not-mocha-tape-node-tap):

> It comes with a default simple reporter and will in the future support TAP through a reporter.

But it looks like TAP output is already supported: https://github.com/sindresorhus/ava#optional-tap-output

Should that line be removed/updated?

**Comment by vdemedes** [comment]
Good catch, it should be updated. Thanks!
