### ISSUE TITLE
Improve default reporter on CI.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#435]
The default reporter doesn't look great if the terminal is not a `tty` or doesn't obey ansi cursor position codes: 

`node-tap` automatically defaults to the `tap` reporter for non-tty setups. That might make sense for us.

Travis does provide claim a `tty`, but it doesn't honor ansi cursor position codes. [See here](https://travis-ci.org/jamestalmage/option-chain/jobs/102683773#L758). It's not terrible, but the verbose reporter would look better.

**Comment by sindresorhus** [comment]
How about defaulting to the verbose reporter?

**Comment by vdemedes** [comment]
If we're gonna make verbose reporter a default one, we can also remove mini reporter. It will not fit into our no-custom-reporters strategy and might as well be transformed into a TAP reporter.

**Comment by jamestalmage** [comment]
I would prefer to have to install extra stuff / pipe to get the mini reporter.

**Comment by sindresorhus** [comment]
@vdemedes I meant defaulting to the verbose reporter **on a CI**, not normally. I love the mini reporter as default in my own terminal.

**Comment by vdemedes** [comment]
@sindresorhus Oh, in that case - ;)

**Comment by jamestalmage** [comment]
Yeah, that is what I was thinking, but how should we make that decision?

- `process.stdout.isTTY` will work for AppVeyor, but not Travis.
- [`is-ci`](https://github.com/watson/is-ci) seems more universal. But do we still want to detect `isTTY`?

I was thinking:

- if `not-a-tty` - default to tap
- else if `is-ci` - default to verbose
- default to mini

Pros:

- Defaults to mini on your own machine.
- You don't need to specify the tap reporter when piping. It just works.
- Travis looks good with the verbose reporter.

Cons:

- It's a little complicated. People might get confused. (However, tap does basically the same thing and it doesn't seem to be a problem).
- Runs on AppVeyor (and probably quite a few other CI's) would default to tap.

**Comment by vdemedes** [comment]
I think we should simplify our lives and just use `is-ci`.

**Comment by jamestalmage** [comment]
My only gripe with that would be tap support:

`ava --tap | spec` 
 vs
`ava | spec`

Not really a big deal (I think I will prefer our reporters in most cases).

**Comment by sindresorhus** [comment]
Tap output should IMHO be an explicit choice through `--tap`. I'd prefer `isCI ? verbose : mini`. TAP is a bonus.

> ava --tap | spec 

Let's add some short-flags then at least: `ava -t | spec` ;)

**Comment by jamestalmage** [comment]
works for me.

**Comment by sindresorhus** [comment]
> I think I will prefer our reporters in most cases

Ditto. And if there's something you don't like about the built-in reporters, you're in a very good position to do something about it ;)

**Comment by vdemedes** [comment]
We should also remember to always prioritize `--tap` over `isCI` check. So that users who enabled TAP output won't end up with verbose reporter on CI.

**Comment by jamestalmage** [comment]
> always prioritize --tap over isCI check

:+1:
