### ISSUE TITLE
Add shortflags to the CLI

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#437]
https://github.com/sindresorhus/ava/issues/435#issuecomment-172090337

- `-t` => `--tap`
- `-v` => `--verbose`
- `-r` => `--require`
- `-s` => `--serial`

Example, something like `alias: { s: 'str' }` should be added below here https://github.com/sindresorhus/ava/blob/ced24c5090ad5d08eb5a2961dc0bb94d00eee445/cli.js#L72 with the shortflag mapping.

**Comment by jamestalmage** [comment]
`--fail-fast`

Not sure if I like `-f`, since that is so widely used as `force` (though I'm not sure what people would think that means in the context of a test runner, so maybe not so confusing).

`-b` for bail-out, but we don't use that term.

**Comment by sindresorhus** [comment]
Yeah, that's exactly why I left out `--fail-fast`. I think it's better written out than a shortflag tbh.

**Comment by sotojuan** [comment]
Does this consist of anything more than doing this?

```js
	default: conf,
	{
		alias: {
		  t: 'tap',
		  v: 'verbose',
		  r: 'require',
		  s: 'serial'
		}
	}
```

Also, would you guys want tests for these? I'm not sure there should because that's `meow` stuff.

**Comment by sindresorhus** [comment]
Should be:

```js
default: conf,
alias: {
  t: 'tap',
  v: 'verbose',
  r: 'require',
  s: 'serial'
}
```

No tests needed. Need to update help output and the help output in the readme though.

**Comment by vdemedes** [comment]
Landed in master.
