### ISSUE TITLE
core-js promises do not offer long stack traces.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#439]
Which is a bummer, since `stack-utils` now [makes them look real nice](https://github.com/tapjs/stack-utils/issues/2).

I'm not sure what the best option is here. 

One solution would be a PR adding long stack traces to core-js. I'm not sure that's a great one, because my understanding is `core-js` wants to be lean and implement the bare minimum spec. I also don't think it's a trivial undertaking (i.e. maybe not the best use of our time). 

I know `bluebird`'s long stack trace support is really efficient, with only minimal slowdown. (My recollection is that Q is slowed down like 5x by long stack traces - another indication that it's probably not that easy to do). Exposing `bluebird` is not great however, since you are exposing a larger API (and potentially masking errors when people use that API thinking it will be available outside of the test environment).

It would be great if `bluebird` had a means of exposing a bare-minimum Promise implementation that was still super-fast and supported debug-ability (like maybe a superclass of `bluebird`).

**Comment by sindresorhus** [comment]
If a user uses Bluebird with long stack traces in their app code and something there throws in a test would we get long stack traces from that or does the whole chain need to use Bluebird to get the long stack traces? Long stack traces for the test themselves aren't that useful, but from the app code it definitely is.

> It would be great if bluebird had a means of exposing a bare-minimum Promise implementation that was still super-fast and supported debug-ability (like maybe a superclass of bluebird).

Indeed, but if you read the Bluebird source you'll see how coupled everything is, probably in the name of optimal performance. Wonder if we somehow could hide the Bluebird specific methods to the user.

**Comment by jamestalmage** [comment]
> Wonder if we somehow could hide the Bluebird specific methods to the user.

I had that thought. Just a wrapper. Not sure what the performance impact would be. But worth looking into.

> ... or does the whole chain need to use Bluebird to get the long stack traces

That I don't know. Worth testing.

> Long stack traces for the test themselves aren't that useful

That's probably true. I noticed while incorporating `stack-utils`. In that case I was writing a fixture that created an entire long stack trace inside the test file. So my experience there may differ.

**Comment by novemberborn** [comment]
IMO the user should pick a promise library if they want more features than come with the ES2015 built-in (or core-js fallback implementation). This probably has to be consistent across their source and test code, meaning we can't replace the `Promise` references in the test files with Bluebird.

I don't think there's anything actionable for us here so closing for now.
