### ISSUE TITLE
Async function support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#45]
Too early to add just yet, but we can at least discuss it.

```js
test(async t => {
  const ret = await foo();
  t.is(ret, 'unicorn');
});
```

Hot!

I think what would be required is to add support for accepting a promise in the `test` function and enabling the experimental [`es7.asyncFunctions`](https://babeljs.io/docs/advanced/transformers/) Babel transformer. [Spec.](https://github.com/lukehoban/ecmascript-asyncawait)

**Comment by vdemedes** [comment]
Oh yes, this is awesome. I don't think this feature would have any disadvantages.

**Comment by mdibaiee** [comment]
This is great, I used async functions in my last project and it feels super!

From my experience, you have to enable `asyncToGenerator`, too. I don't remember why but I couldn't get it to work with `es7.asyncFunctions` alone.

**Comment by sindresorhus** [comment]
Since we're already depending on Bluebird, I guess we could use the [`bluebirdCoroutines`](http://babeljs.io/docs/advanced/transformers/other/bluebird-coroutines/) transformer.

**Comment by vdemedes** [comment]
In that case, we need to support generators (#37). I can work on this!
