### ISSUE TITLE
Make tests return a promise

### ISSUE THREAD

**Issue by davej** [sindresorhus/ava#452]
Apologies if this a dupe, I did my best to search existing issues.

I realise that test.serial() is available but this could be a nice alternative because it makes test dependencies more explicit:

```js
import test from 'ava';
import fn from './';

test('title', t =>
  fn('foo').then(data => t.ok(data))
).then(() =>
  test('title2', t =>
    fn('bar').then(data => t.ok(data))
  )
);
```

**Comment by ariporad** [comment]
@sindresorhus: Thoughts?

**Comment by sindresorhus** [comment]
:-1: I don't see how this is any improvement. It's both harder to read and more code.

And incorrect. It would have to be:

```js
import test from 'ava';
import fn from './';

test('title', t =>
  return fn('foo').then(data => t.ok(data))
).then(() =>
  return test('title2', t =>
    return fn('bar').then(data => t.ok(data))
  )
);
```

I think the serial tests are already plenty explicit about their dependencies. They're named serial tests and run serially in the order you specify them.

**Comment by davej** [comment]
> And incorrect.

Do you mean the `return`? Arrow expressions automatically return so `return` is not needed.

> I think the serial tests are already plenty explicit about their dependencies. They're named serial tests and run serially in the order you specify them.

Perhaps I didn't explain well, the major benefit is that the you can have tests that rely on other tests while still being run in parallel. For example:

```js
import test from 'ava';
import fn from './';

test('title', t =>
  fn('foo').then(data => t.ok(data))
).then(() =>
  test('title2', t =>
    fn('bar').then(data => t.ok(data))
  )
);

test('title3', t =>
  fn('fez').then(data => t.ok(data))
).then(() =>
  test('title4', t =>
    fn('baz').then(data => t.ok(data))
  )
);
```

In this example `title1` and `title3` are run at the same time. I'm not sure this is possible with serial tests? It's not really for performance reasons that I'm suggesting this change though. To me it's clearer which tests rely on other tests and makes more sense than a long string of serial tests which aren't necessarily connected.

**Comment by sindresorhus** [comment]
> Do you mean the lack of a return? Arrow expressions automatically return, so return is not needed.

Ah, didn't notice that, but doing braceless arrow function for anything non-inline isn't very readable.

> To me it's clearer which tests rely on other tests and makes more sense than a long string of serial tests which aren't necessarily connected.

Ideally your tests should be atomic and not have a dependency on other tests. `test.serial` is mostly there to fill a small niche when you *have to* modify some global state or something can't handle the concurrency.

I would help if you presented a realistic scenario where your proposal would be useful.

**Comment by davej** [comment]
> Ideally your tests should be atomic and not have a dependency on other tests. test.serial is mostly there to fill a small niche when you have to modify some global state or something can't handle the concurrency.

Sometimes your lib has side-effects (e.g. writing to the file-system) and you want to test how your lib behaves after the side-effects because it's often a prime spot for edge-case bugs. It's perfectly possible to do it with `test.serial` (although you would lose concurrency), it's just that I find it's clearer to explicitly express the dependency.

Here's a real-world example form a module I just started to work on:

```js
test('tag folders', t =>
  fn(__dirname).then(tagged => {
    console.log(tagged);
    t.ok(tagged.dependencies);
    t.ok(tagged.devDependencies);
    t.is(tagged.dependencies[0].tag, 'blue');
    t.is(tagged.devDependencies[0].tag, 'yellow');
  })
).then(() =>
  test('remove tags from folders', t =>
    fn(__dirname, {clear: true}).then(tagged => {
      t.ok(tagged.dependencies);
      t.ok(tagged.devDependencies);
      t.is(tagged.dependencies[0].tag, 'clear');
      t.is(tagged.devDependencies[0].tag, 'clear');
    })
  )
);
```

**Comment by vdemedes** [comment]
I'm not a fan of this change, tbh. And as a "bonus", it would break things in AVA core, like reporting number of tests beforehand. Serial tests already solve this issue, so this would also result in a duplicate functionality too.

**Comment by jamestalmage** [comment]
I'm :-1: as well, for all the reasons discussed above.

**Comment by masaeedu** [comment]
The bad thing about serial tests is *implicit* dependencies, not the fact of having dependencies at all. If you're doing slow integration tests and you can save time by reusing work from another test, it's a good idea to do that.

I'm not a fan of doing a promise based thing like this, but declaring named dependencies between testcases and expecting the test runner to traverse the graph in dependency order is not unreasonable.

**Comment by novemberborn** [comment]
@masaeedu I think that's something that could be built on top of AVA though.
