### ISSUE TITLE
Suggestions on testing image based output

### ISSUE THREAD

**Issue by photonstorm** [sindresorhus/ava#457]
I'm happily using ava to test all of my core math and utility functions, but I'd really like to find a way to use it to check rendering as well. By this I mean comparing the likes of Canvas context output to a batch of stored PNGs (or worst case scenario comparing pngs, output by my test scripts, with saved 'correct' pngs stored locally).

Any thoughts at all on how to accomplish this (if it's even possible) ?

**Comment by vdemedes** [comment]
First of all, love reading this: `I'm happily using ava` :)

I never done this before, so would be great if you pointed out examples tests somewhere else maybe. How others do it, what tools are being used. Hope to be able to help you after that!

**Comment by sindresorhus** [comment]
Would be cool if someone familiar with this could write a recipe (/docs/recipes).

**Comment by kevva** [comment]
Matching them would be pretty easy since you'd just have to check their buffers. Comparing them is another beast.

**Comment by photonstorm** [comment]
Here's a JS Image Diff library which has two Jasmine matchers for unit testing. It uses node-canvas (which in turn uses cairo), so it's pretty 'heavyweight', but definitely works:

https://github.com/HumbleSoftware/js-imagediff

Perhaps it'd be possible to make use of this somehow?

**Comment by novemberborn** [comment]
@photonstorm AVA is merely a test runner. (Though a pretty awesome one, of course!) It can test anything provided you know whether the actual output is acceptable.

Looks like `js-imagediff` has an `equal(a, b, tolerance)` method, which I assume returns a boolean. You could then do `t.ok(imagediff.equal(a, b, tolerance)` in your AVA test and it will pass or fail based on how equivalent the images are.

Going to close this but feel free to reopen if you've got further questions.
