### ISSUE TITLE
broken stack trace if error is not an Error

### ISSUE THREAD

**Issue by jokeyrhyme** [sindresorhus/ava#459]
I used [pify](https://github.com/sindresorhus/pify) on the "fs" built-in, and used the pify'ed [`fs.exists`](https://nodejs.org/dist/latest-v5.x/docs/api/fs.html#fs_fs_exists_path_callback)`()` in an ava test. This is one of those rare Node.js built-ins that invokes its callback like `callback(result)` and _not_ the conventional `callback(err, result)`.

This meant that the pify'ed version returned a rejected Promise, with a boolean value, instead of an Error value. Note: I will follow the recommendations and drop `fs.exists()`, but I'm just describing my context.

Anyhow, the stack trace produced by ava was not helpful in determining the cause here.

You can simulate my issue with the following reduced test code:

```js
const test = require('ava')
test('non-Error error', () => Promise.reject(true))
```

Here is the output that ava produces:

> TypeError: Cannot read property 'split' of null
>     at beautifyStack ([redacted]/node_modules/ava/lib/beautify-stack.js:14:62)
>     at [redacted]/node_modules/ava/lib/reporters/mini.js:107:29
>     at Array.forEach (native)
>     at MiniReporter.finish ([redacted]/node_modules/ava/lib/reporters/mini.js:95:19)
>     at Logger.finish ([redacted]/node_modules/ava/lib/logger.js:45:27)
>     at [redacted]/node_modules/ava/cli.js:112:10
> From previous event:
>     at Object.<anonymous> ([redacted]/node_modules/ava/cli.js:111:3)
>     at Module._compile (module.js:397:26)
>     at Module.replacementCompile ([redacted]/node_modules/append-transform/index.js:53:13)
>     at Module._extensions..js (module.js:404:10)
>     at Object.<anonymous> ([redacted]/node_modules/append-transform/index.js:57:4)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:429:10)
>     at Function.runMain (/Users/ron/.node-spawn-wrap-10240-f3833035c112/node:40:10)
>     at Object.<anonymous> ([redacted]/node_modules/nyc/bin/nyc.js:19:6)
>     at Module._compile (module.js:397:26)
>     at Object.Module._extensions..js (module.js:404:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:429:10)
>     at Object.<anonymous> (/Users/ron/.node-spawn-wrap-10240-f3833035c112/node:140:8)
>     at Module._compile (module.js:397:26)
>     at Object.Module._extensions..js (module.js:404:10)
>     at Module.load (module.js:343:32)

As you can see, because code that interprets the original stack trace is itself broken (in this situation), no useful stack trace information is provided to the developer.

This took me quite a while to debug, because all of the `Promise#reject()`s in my own code were strictly creating Error objects, and I only discovered the problem after manually tracing execution back until all I had left was the pify'ed `fs.exists()`.

Do you think this sort of mistake is common enough to warrant some extra handling? Would you accept a PR that hardens the stack trace beautifying code?

**Comment by tusharmath** [comment]
Same problem.

**Comment by sindresorhus** [comment]
@jamestalmage How do you think we should we handle this? The verbose reporter already checks if there's a `.stack` before beautifying: https://github.com/sindresorhus/ava/blob/3fdb6fc1368b0ce6dc91c9fb408e98f7fbed5d32/lib/reporters/verbose.js#L48, but the mini reporter does not: https://github.com/sindresorhus/ava/blob/3fdb6fc1368b0ce6dc91c9fb408e98f7fbed5d32/lib/reporters/mini.js#L107 Should the reporters really have to do these checks? I kinda feel the API itself should guarantee `err` is always an error.

**Comment by jamestalmage** [comment]
>  I kinda feel the API itself should guarantee err is always an error.

It's supposed to already: https://github.com/sindresorhus/ava/blob/master/lib/test.js#L132-L138

There's a bug somewhere

**Comment by davej** [comment]
Also seeing this stack trace when used with `pify(fs.writeFile)`. The rejected `writeFile` promise is an error (`err instanceof Error === true`), so I'm not quite sure what's going on.
