### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#460]
Re https://twitter.com/sindresorhus/status/689851060303872000

We should set up a benchmark with various types of test suites, like one with sync tests in one file, one with multiple files and async tests. This to make sure we don't regress in performance and ability to compare ourselves to other test runners.

**Comment by kentcdodds** [comment]
Thanks for taking this so seriously! :smile: I'm currently working on a repo to compare mocha and ava with a lot of tests with a lot of files. I'm no benchmark expert, but maybe this will be helpful. Will comment when I've pushed it up. Thanks!

**Comment by jfmengels** [comment]
I have created this repo for the same purpose: https://github.com/jfmengels/mocha-vs-ava-performance
It's pretty small, but it makes it obvious how big the difference is between Mocha's instant feedback in watch mode, and Ava's "watch" with Nodemon, or even single runs.

**Comment by jamestalmage** [comment]
> watch mode

AVA is at an extreme disadvantage in watch mode until we implement our own watch mechanism. That's certainly on the roadmap, but we've been punting on it in favor of other improvements. Not sure if it's time to tackle that yet or not.

**Comment by jamestalmage** [comment]
I have confirmed [this commit](https://github.com/beaugunderson/emoji-aware/commit/e2c3a824ec6e28c2e86e9191fd7123cea8ac1e00) caused a major performance hit. I think I've identified the problem and I am working up a solution.

See twada/empower-core#7

**Comment by twada** [comment]
Just released [empower-core 0.5.0](https://github.com/twada/empower-core/blob/master/CHANGELOG.md#050-2016-01-21) :tada: (Thanks @jamestalmage !!)

**Comment by sindresorhus** [comment]
@jamestalmage did a superb job adding a pretty benchmark in https://github.com/sindresorhus/ava/pull/496. It's easy to add additional things to benchmark, so suggestions welcome.

**Comment by sindresorhus** [comment]
Instructions here: https://github.com/sindresorhus/ava/commit/c22eabd717451dbeaeeff1520f399f5a5fd85764
