### ISSUE TITLE
.only() shouldn't print all tests when verbose is on.

### ISSUE THREAD

**Issue by tomazzaman** [sindresorhus/ava#463]
When one of the tests has `.only()` on them I still get all the rest of the tests marked as passed -even if they would otherwise fail. There are two solutions:
- do not print out those tests at all and just show the one with `.only()`
- print the rest of the tests in the same manner as they would use `.skip()`

Because right now, it's easy to miss that we're performing one test only, which is a UX concern, to say the least.

**Comment by sindresorhus** [comment]
Sounds like a bug. It should only show the `.only()` test.

**Comment by sotojuan** [comment]
I can't seem to replicate this.

I have a file with two failing tests and one passing test with `.only()`... I only get "1 test passed" and a green check next to that test, with verbose. Can you share the code you are using?

**Comment by sotojuan** [comment]
@tomazzaman ping ~

**Comment by novemberborn** [comment]
Sounds like #549. Nice find @tomazzaman, it's being fixed :smile:
