### ISSUE TITLE
TAP: Skip count not reporting properly

### ISSUE THREAD

**Issue by therealklanni** [sindresorhus/ava#470]
Seems that after the skip count fix, AVA does not report the total skip count, even when there are `> 0` skipped tests. Additionally, skipped tests are being printed as passing tests.

We get
```
ok N - this test was skipped
```

Instead of
```
ok N - # skip this test was skipped
```

And therefore other TAP libraries (e.g. faucet) break because they count it as a passing test, not skipped.

Here's an example from one of my own libraries using `ava --tap`:

```
TAP version 13
# json-adapter › read method
ok 1 - json-adapter › read method
# json-adapter › rejects
ok 2 - json-adapter › rejects
# json-adapter › create method
ok 3 - json-adapter › create method
# create › rejects
ok 4 - create › rejects
# create › create pending task
ok 5 - create › create pending task
# create › create completed task
ok 6 - create › create completed task
# create › create waiting task
ok 7 - create › create waiting task
# create › create recurring parent task
ok 8 - create › create recurring parent task
# create › create recurring child task
ok 9 - create › create recurring child task

1..7
# tests 7
# pass 7
# fail 0
```

Test 1 and 2 above were actually skipped—notice no "# skip". Also note no "# skipped N" summary line.

This confuses faucet (and presumably anything else that would interpret the broken TAP output):

```
✓ json-adapter › read method
✓ json-adapter › rejects
✓ json-adapter › create method
✓ create › rejects
✓ create › create pending task
✓ create › create completed task
✓ create › create waiting task
✓ create › create recurring parent task
✓ create › create recurring child task
# tests 7
✓ pass 7
not ok 10 too many asserts
⨯ fail  1
```

Related: #464 

cc @sotojuan if you want to take a look, since you've been contributing in this area and you at least contributed directly to the skipped count summary.

**Comment by sotojuan** [comment]
Does this only happen in the TAP reporter?

**Comment by therealklanni** [comment]
See above. No skip count in the raw TAP output (thereby affecting TAP reporter).

**Comment by sotojuan** [comment]
Hm I see. I'll give it a try tomorrow. @jamestalmage @sindresorhus do you guys have any leads? I have a hunch it might have to do with the API.

**Comment by sotojuan** [comment]
All right, figured this out. Turns out there was no `skipCount` in the API. Seems like I got it [working](http://i.imgur.com/YSzK1cY.png). Gonna clean some things up and send a PR later today.
