### ISSUE TITLE
TAP: Should test.only() contribute to skipped count summary?

### ISSUE THREAD

**Issue by therealklanni** [sindresorhus/ava#471]
I personally think it should, as this would be useful information.

Currently, if you use the `test.only()` method, it doesn't tally any other `test()` calls as skipped and thus they go unreported (as if they don't exist).

Side note: maybe even useful in the normal AVA output?

```
7 passed
2 skipped
```

**Comment by BarryThePenguin** [comment]
Personally I use `test.only()` for debugging. If I use it on a single test, I only care about the result of that test.

In `karma-spec-reporter`there are config values to suppress certain results. I turn report of skipped tests off in local development to stop the output being polluted with skipped test lines. Then I rely on the CI server to give me an accurate report of skipped tests. 

```
specReporter: {
        maxLogLines: 5,         // limit number of lines logged per test 
        suppressErrorSummary: true,  // do not print error summary 
        suppressFailed: false,  // do not print information about failed tests 
        suppressPassed: false,  // do not print information about passed tests 
        suppressSkipped: true  // do not print information about skipped tests 
      },
```

In summary I guess it's the job of the individual tap reporter to handle how to interpret the output. And AVA should be giving an accurate output of test results.

**Comment by therealklanni** [comment]
I agree that it's the job of the reporter to determine how to interpret the output, so yes, I think AVA should give an accurate output (i.e. report all skips).

**Comment by sindresorhus** [comment]
:+1: This also catches the case of forgetting to remove an `.only()`.

@therealklanni Interested in doing a PR?

**Comment by jamestalmage** [comment]
> This also catches the case of forgetting to remove an .only().

I have a really crazy idea. Should the use of `.only()` cause a non-zero exit code? Or the ability to configure it to exit with a non-zero exit code in that case?

We could probably create a linter rule that handled warning about `.only()` usage, but I think it would be so nice if AVA just handled it for you.

**Comment by sindresorhus** [comment]
> Should the use of .only() cause a non-zero exit code? Or the ability to configure it to exit with a non-zero exit code in that case?

I like the idea, but need to think about possible cases where you don't want it to fail. I'm also not very interested if it has to be configurable. Trying to keep config to a minimum.

> We could probably create a linter rule that handled warning about .only() usage

Already planned regardless: https://github.com/sindresorhus/eslint-plugin-ava/issues/5

**Comment by therealklanni** [comment]
@sindresorhus I can possibly take a look at this sometime this week.

If anyone else wants to give it a go before I get to it, feel free!

**Comment by naptowncode** [comment]
Given the discussion around #565, how should the use of `.only()` affect the rest of the tests? Should they be counted in stats as skipped, just as if `.skip()` were used? Or something else altogether?

I'm just asking what the API should do when reporting stats, regardless of what the reporter decides to do with those stats.

**Comment by vdemedes** [comment]
The rest of the tests should not be in the output at all. `.skip()` has nothing to do with `.only()`.

**Comment by naptowncode** [comment]
But some information about the rest of the tests should be sent to the reporter, even if the reporter chooses not to output it to the user.

Skipping those tests would feel consistent with the implementation of `--match` in #477.

**Comment by novemberborn** [comment]
I can see `.only` being an inverse `.skip`, allowing you to home in on a particular failing test. In that case I wouldn't want to see any skipped tests (or todos) in the output, other than for the final summary. Though as @BarryThePenguin mentioned it might make sense to show them on CI servers.

Currently reporters aren't pluggable so we need to figure out what behavior we want from the built-in reporters. Presumably the test events could convey a test is being skipped due to a `.skip` or `.todo` or because there's an `.only` present elsewhere.

**Comment by jamestalmage** [comment]
I've thought about this some more, and I'm against the idea.

If only is used, I *only* want to see output for that test. Reporting all the skipped tests is just going to slow things down with lots of IPC calls communicating test titles I don't care about. Additionally, if I am using the `--verbose` reporter, which test failed gets lost in a sea of "skipped" logs for tests I don't care about.

Basically, this proposal is kinda antithetical to the entire purpose of only. Focusing in on just a few tests for quick feedback while tackling a specific problem.

**Comment by novemberborn** [comment]
@jamestalmage do you think we should output the count even if we don't report the individual tests? Though I suppose that would be illegal under TAP and then things get all weird between the different reporters.

**Comment by jamestalmage** [comment]
I think it's fine for us only to report `.only` tests. I just don't see the value of all those skip reports. It's pretty easy to figure out what happened when your tests suddenly run faster and your count drops to `1`.

It might be interesting to offer a `--disallow-only` flag that could be used on your CI server to ensure `.only` didn't make it into master. Better yet, automatically detect and disallow using `is-ci` (with `--allow-only` to override?).

**Comment by BarryThePenguin** [comment]
As much as I :heart: `is-ci`, that's a little too much magic... I guess the eslint rules would cover this?

**Comment by sindresorhus** [comment]
> It might be interesting to offer a --disallow-only flag that could be used on your CI server to ensure .only didn't make it into master. Better yet, automatically detect and disallow using is-ci (with --allow-only to override?).

:-1: That's better covered by the [`no-only-test`](https://github.com/sindresorhus/eslint-plugin-ava/blob/master/docs/rules/no-only-test.md) ESLint rule.

**Comment by jamestalmage** [comment]
Yeah, I get that (and tend to agree). Not everybody lints their code though. I think we had a similar discussion regarding `t.end` for non-`cb` tests and decided it was a better user experience to build in the error.

I am pushing to silently ignore all tests not marked with `.only`, and that suggestion was mainly offered as possible way to mitigate concerns that might raise.

**Comment by sindresorhus** [comment]
> I think we had a similar discussion regarding t.end for non-cb tests and decided it was a better user experience to build in the error.

The difference is that was 100% predictable and detectable. This will require a flag, which you know I'm very conservative about. Automagically doing it on CI is too magic and people might want to allow `.only` on CI to quickly test something on more machines for example.

**Comment by novemberborn** [comment]
> Basically, this proposal is kinda antithetical to the entire purpose of .only. Focusing in on just a few tests for quick feedback while tackling a specific problem.

:100: 

Closing, unless @sindresorhus or @vdemedes object.
