### ISSUE TITLE
Flag to stop after first test failure

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#48]
From https://github.com/sindresorhus/ava/issues/9#issuecomment-138639602.

Does it makes sense to have this?

`--bail`, `--fail-fast`, other?

-

On that note, any thoughts on failing-fast by default? Any reason you'd want the test to complete before failing? I'm sure there are since test runners usually run to completion. Just useful to have this documented either way.

**Comment by vdemedes** [comment]
Yes, this would be a nice option to have.

I would leave this as an option, because AVA is a tool that `enforces writing atomic tests`. So, one failing test does not mean that all the other ones will fail too. But as an option, it is going to be useful for sure.

**Comment by joakimbeng** [comment]
:+1:

On my own laptop I usually want the tests to fail fast, but in an CI environment I think it's good to run all tests and get a report of what didn't work.

**Comment by sindresorhus** [comment]
What flag name do you prefer? *bikeshedding*

**Comment by joakimbeng** [comment]
I think I prefer `--bail` as it's in line with other test runners.

**Comment by Qix-** [comment]
`fail-fast` means more to me as a programmer. I'd have no idea what `bail` meant.

**Comment by sindresorhus** [comment]
I don't really care what other test runners do. AVA exists because of those. I want something succinct as flag name.

**Comment by joakimbeng** [comment]
> I don't really care what other test runners do

:+1: Then I agree with `--fail-fast` being a better name. Or maybe `--abort-on-fail` but that's too long to be good...

**Comment by arthurvr** [comment]
I like `fail-fast`.

**Comment by kevva** [comment]
I'd also leave it as an option, although I'm usually hitting `ctrl +c` whenever I see a failed test locally if there are time consuming tests (like in pageres). But most of the times, the tests are finished before that.
