### ISSUE TITLE
Don't send unnecessary data from forks

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#485]
```js
import test from '../../';

test(`test`, t => {
	t.plan(1);
	t.pass();
});
```

The single test above generates three events from the child process:

stats event:

```js
{ testCount: 1, file: 'test/fixture/lots-of-plans.js' }
```

test event: 

```js
{ duration: 8, title: 'test', error: {}, type: 'test', skip: false, file: 'test/fixture/lots-of-plans.js' }
```

results event:

```js
{ 
  stats: { 
    failCount: 0, 
    passCount: 1, 
    skipCount: 0, 
    testCount: 1 
  }, 
  tests: [ { duration: 8, title: 'test', error: {}, type: 'test', skip: false } ], 
  file: 'test/fixture/lots-of-plans.js' 
}
```

The results event seems completely unnecessary as it can be built from previous events.

**Comment by sindresorhus** [comment]
Does it have any non-neglibable perf impact? The result event for for convenience.

**Comment by jamestalmage** [comment]
> Does it have any non-neglibable perf impact?

Yes, it does. Though really only when there are lot's of errors (errors generate a lot more data).

> The result event is a nice convenience.

See #497. I rebuild it inside `fork.js`, so it's not gone.

**Comment by sindresorhus** [comment]
Alright. Then I'm :+1:
