### ISSUE TITLE
Output `null` when tests don't have a name

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#487]
I just noticed this by accident when testing [mem-map](https://github.com/SamVerschueren/mem-map) and couldn't find a similar issue.

![screen shot 2016-01-29 at 08 36 36](https://cloud.githubusercontent.com/assets/1913805/12669781/73a40b26-c663-11e5-8c8b-26ac6b61b08c.png)

**AVA version**: v0.11.0

The reason seems to be that I don't have a name for my test.

**Comment by jamestalmage** [comment]
Should be `[anonymous]`

**Comment by jamestalmage** [comment]
Actually - if there's just one test - it should be nothing.

**Comment by sotojuan** [comment]
[This](https://github.com/sindresorhus/ava/blob/master/lib/reporters/verbose.js#L30) is the offending line. Should it just return an empty string?

**Comment by jamestalmage** [comment]
Yep. Empty string
