### ISSUE TITLE
Tests are flaky on Travis with Node 0.10

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#498]
I am not sure what started it, but the Travis build has gone from a little flaky to really flaky on Node 0.10.

**Comment by sindresorhus** [comment]
It's weird, because it always works the second time when restarted.

**Comment by jamestalmage** [comment]
Yep. Except for [here](https://github.com/jamestalmage/ava/commit/03392243448c5d5bbf95c73fdf9fc12059ba7944), where Node 0.10 actually behaves differently (I had to modify the test). I was assuming it was just being flaky again when I opened this. Still, it would be nice to hunt down the problem.
