### ISSUE TITLE
Integration test for `serial` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#499]
We should have an integration test for the public API to make sure we don't break serial test running. It has happened before.

https://github.com/sindresorhus/ava/blob/master/test/api.js

It should ensure tests are not run concurrently.

**Comment by sotojuan** [comment]
Seems like a way to test this would be to make sure the contents of the `api.tests` array are in a specific order right? I've been trying that out with [this fixture](https://github.com/sindresorhus/ava/blob/master/test/fixture/serial.js), but sometimes the results of the array are out of order (once every ten tries, approximately), even with serial on.

**Comment by sindresorhus** [comment]
@sotojuan Yeah. Opened this because @jamestalmage mentioned `serial` might be broken on master.
