### ISSUE TITLE
Babelify only test files

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#50]
I think we should apply `babel` only to test files, e.g `test.js`, `test/test-something.js`.
Currently, if you have this common code:

```js
const test = require('ava');

const mylib = require('./');
```

`mylib` will also be run through `babel` and that is not good, because that way AVA transforms library's source code. This behavior could be fixed by setting a regex for `require('babel/register')` to whitelist only test files.

**Comment by sindresorhus** [comment]
:+1:
