### ISSUE TITLE
Document how to run the benchmarks

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#501]
It could pretty much be copied from the description on #496 and [this comment](https://github.com/sindresorhus/ava/pull/496#issuecomment-177731176).

I wrote the code, so it should probably be me.

**Comment by sindresorhus** [comment]
Already done: https://github.com/sindresorhus/ava/commit/c22eabd717451dbeaeeff1520f399f5a5fd85764 ;)
