### ISSUE TITLE
test-collection needs cleanup

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#504]
Coming back just a few weeks after writing it, I find [this section](https://github.com/sindresorhus/ava/blob/master/lib/test-collection.js#L136-L162) confusing.

Maybe it just needs comments, but I would prefer to refactor into a self explanatory API if possible.

**Comment by novemberborn** [comment]
Looks like this might be covered by #542?

**Comment by vdemedes** [comment]
Yep!
