### ISSUE TITLE
`t.doesNotThrow` → `t.notThrows`

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#507]
When testing if a function throws an error, this can be done with `t.throws`. If you want to test that the method doesn't throw an error, you can use `t.doesNotThrow`. I always tend to use `t.notThrows` instead because it's more in line with the other assertions.

- `ok` ↔ `notOk`
- `same` ↔ `notSame`

So `doesNotThrow` doesn't feel quite right to me.

**Comment by sindresorhus** [comment]
:+1: This has irked me too. `t.doesNotThrow` was initially used to be compatible with Node.js core assert, but we no longer care about that, so I think `t.notThrows` would be a good change. We can keep an undocumented alias to `t.doesNotThrow` for backwards-compatibility.
