### ISSUE TITLE
Async uncaught exception not shown in default reporter and has useless stack

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#511]
With latest master (d51c33147865d0c97798698a18bd6aeb86bc77c7).

```js
import test from 'ava';

test.cb(t => {
	setImmediate(() => {
		throw new Error('foo');
		t.end();
	});
});
```

Default reporter:

```

  ✖ Test results were not received from test.js

```

Verbose reporter:

```
Uncaught Exception: test/stream.js
  Error: foo
    Immediate._onImmediate (stream.js:5:9)
    


  ✖ Test results were not received from test.js
```

It should show the uncaught exception in the default reporter and a more useful stack in both.

**Comment by novemberborn** [comment]
In https://github.com/sindresorhus/ava/pull/502 I change how these "no results received" errors are propagated. They're now treated as uncaught exceptions and, crucially, don't stop the tests from running. It seems to fix this case too!

```
$(npm bin)/ava foo.js

  2 exceptions

  1. Uncaught Exception
  Error: foo
    Immediate._onImmediate (foo.js:5:15)


  ✖ Test results were not received from foo.js
```

```
(npm bin)/ava --verbose foo.js

Uncaught Exception: foo.js
  Error: foo
    Immediate._onImmediate (foo.js:5:15)



  ✖ Test results were not received from foo.js

  0 tests passed
  2 uncaught exceptions
```

**Comment by novemberborn** [comment]
Though I must admit that I haven't rebased on top of `master` yet. Will check again once I've done that.

**Comment by novemberborn** [comment]
Output is the same.

**Comment by sindresorhus** [comment]
@novemberborn I assume this can be closed now then?

**Comment by novemberborn** [comment]
Yea

**Comment by tusharmath** [comment]
I am facing the same problem here  — https://travis-ci.org/tusharmath/Multi-threaded-downloader/builds/117959834

**Comment by novemberborn** [comment]
@tusharmath it doesn't output the uncaught exception though. Maybe you're running into the issue discussed here: https://github.com/sindresorhus/ava/issues/604#issuecomment-199516941

**Comment by tusharmath** [comment]
Tests run fine locally. I'm not sure what the issue is. Could you elaborate
a little more please?

On Wed, Mar 23, 2016, 8:01 PM Mark Wubben <notifications@github.com> wrote:

> @tusharmath <https://github.com/tusharmath> it doesn't output the
> uncaught exception though. Maybe you're running into the issue discussed
> here: #604 (comment)
> <https://github.com/sindresorhus/ava/issues/604#issuecomment-199516941>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/ava/issues/511#issuecomment-200368506>
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by novemberborn** [comment]
#604 discusses an issue where Travis kills the test processes. I suspect you're running into that problem.

The behavior described in this issue is by design.

**Comment by tusharmath** [comment]
@novemberborn Some pointers to mitigate the problem would be a great help. I went thru the discussion but I am unable to co-relate it with my issue.

**Comment by novemberborn** [comment]
@tusharmath try running with the [`--serial` CLI flag](https://github.com/sindresorhus/ava#cli) to work around the issues described in #604.

**Comment by tusharmath** [comment]
That din't work either. Infact I tried creating folders and run them one by one also. Did not work.

**Comment by novemberborn** [comment]
@tusharmath could you open a new issue to discuss this in?
