### ISSUE TITLE
Improve performance of simple sync tests with long stack traces enabled

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#516]
We merged https://github.com/sindresorhus/ava/pull/495, which makes the `lib/sequence.js` code a lot more readable, but with the unfortunate side-effect of [slowing down execution](https://github.com/sindresorhus/ava/pull/495#issuecomment-177342400) of running thousands of simple synchronous tests. This might sound like an edge-case, and it kinda is, but the legitimate usage of something like this are generated tests, where you e.g. programmatically generate a test for each item in a huge list, like with https://github.com/beaugunderson/emoji-aware.

We should look into whether there's any way to improve on this without having to revert the code to be less readable, like before #495.

External suggestions more than welcome.

**Comment by jamestalmage** [comment]
It should be noted that it really doesn't slow things down unless bluebird long stack traces are turned on.

In #495 we discussed merging it on the condition that we would turn off long stack traces, but now we are having second thoughts on that as well.

**Comment by jamestalmage** [comment]
Here is the difference with longStackTraces still on in both:

<img width="1067" alt="screenshot 2016-02-06 02 54 07" src="https://cloud.githubusercontent.com/assets/4082216/12865547/3a50f062-cc7d-11e5-9760-da37adabe7d1.png">

**Comment by jamestalmage** [comment]
Note that most of these benchmarks have 10,000 tests.

**Comment by jamestalmage** [comment]
Turning shortStackTraces off  #495 is generally faster, but not by much.

**Comment by vdemedes** [comment]
I will follow up with another PR in coming days regarding this issue.

**Comment by novemberborn** [comment]
> I will follow up with another PR in coming days regarding this issue.

That's #539 right?

**Comment by vdemedes** [comment]
Yep this is the one ;)
