### ISSUE TITLE
Doesn't seem work with coffeescript

### ISSUE THREAD

**Issue by adius** [sindresorhus/ava#521]
I have following lines in my package file:

```json
  "scripts": {
    "test": "ava --require coffee-script/register --verbose test"
  },
  "devDependencies": {
    "ava": "^0.11.0",
    "coffee-script": "^1.10.0"
  }
```
The test directory contains a `main.coffee` file with ava tests.

When I run `npm test`, however, it always says `Couldn't find any files to test`.

Any ideas?

**Comment by novemberborn** [comment]
@adius currently test files must be JavaScript files, ending in `.js`. Are you trying to use a test file written in Coffeescript?

**Comment by SamVerschueren** [comment]
You could compile it first to JavaScript and then run that file. Just like with [TypeScript](https://github.com/sindresorhus/ava/blob/master/docs/recipes/typescript.md). Although it might be cleaner if AVA could handle `.coffee` files directly.

**Comment by Whoaa512** [comment]
I haven't tried this, but couldn't you change the search pattern for files to include `test/**/*.coffee` either in AVA config in package.json or directly in your test command? Assuming you retain the `--require coffee-script/register`

**Comment by jamestalmage** [comment]
> couldn't you change the search pattern for files to include test/**/*.coffee

Unfortunately, no. We are discussing a similar issue for jsx [here](https://github.com/sindresorhus/ava/issues/631#issuecomment-195122732).

**Comment by novemberborn** [comment]
Closing in favor of #229.
