### ISSUE TITLE
t.notThrows - Should possibly be renamed to t.notThrow - `t.doesNotThrow` → `t.notThrows` → `t.notThrow` #508

### ISSUE THREAD

**Issue by rclanan** [sindresorhus/ava#528]
After looking into removing the deprecation warning that (https://github.com/sindresorhus/ava/pull/508) we are now seeing when we run `npm test`. I dug into tap a little and they are using t.notThrow which the PR changed associated with this added notThrows. If you change the test to t.notThrows it can't find that function because tap doesn't have it. If you use notThrow it works fine. 

From: http://www.node-tap.org/asserts/

t.doesNotThrow(fn, message, extra)

Verify that the provided function does not throw.

If the function has a name, and the message is not provided, then the function name will be used as the message.

If the function is not provided, then this will be treated as a todo test.

Note: if an error is encountered unexpectedly, it's often better to simply throw it. The Test object will handle this as a failure.

Synonyms:** t.notThrow**

**Comment by vdemedes** [comment]
But we are not using node-tap, so we don't have a `t.notThrow` method, but we have `t.notThrows` (from #508).

**Comment by allensb** [comment]
node-tap is in the package.json and I'm seeing the same issue. The t being passed in appears to use node-tap.

"tap": "^5.0.1",

**Comment by rclanan** [comment]
As Allen pointed out, tap is being used. Line reference is here: https://github.com/sindresorhus/ava/blob/master/test/assert.js#L2

`var test = require('tap').test;`

I understand that Ava is different than tap but since it was referenced (not directly) in the original issue (https://github.com/sindresorhus/ava/issues/507) that changed it from doesNotThrow to notThrows; only seemed appropriate to make it align with notThrow instead of notThrows.

**Comment by sindresorhus** [comment]
It would be weird if `t.throws` is plural while the inverse method `t.notThrow` is singular. Compatibility with node-tap is not a concern as we already differ in too many ways. Changing the node-tap usage of `t.doesNotThrow` to `t.notThrow` is just unnecessary code churn.

**Comment by vdemedes** [comment]
Oh my, a lot has changed while I was absent. Sorry for providing out-dated info guys.

**Comment by vdemedes** [comment]
@allensb @rclanan Ok, `tap` is only being used for AVA's tests, not in the AVA itself. So, yes, my comment in the beginning is valid, we are not compliant with `tap` and have a different API.

> we don't have a t.notThrow method, but we have t.notThrows
