### ISSUE TITLE
Prefix test results with filename when running multiple files

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#53]
We should prefix the tests with the filename minus extension and prefix `test-` so [this](https://github.com/sindresorhus/got/pull/104/files#diff-4b237e7473a059a1f82a01d75d69c5f1R26) isn't needed.

`test-url.js` with `test('foo bar')` would be:

```
✔ url - foo bar
```

-

// @floatdrop

**Comment by floatdrop** [comment]
Yeah, this would be sweet :sparkles:

**Comment by scottcorgan** [comment]
Perhaps a way to specify a regex, or something like it, for file naming conventions. I'm not opposed to opinionated libraries, but I know that some people use `_url_test.js` or `url.test.js` or `__test__/url.js`, etc.

Maybe something like a `.avarc` file would be helpful for this (and things like tap output).

**Comment by sindresorhus** [comment]
I'm allergic to options, but I'm happy to make the normalizing smarter. Any other naming patterns you can think of?

**Comment by scottcorgan** [comment]
`test/url.js`, `tests/urls.js` is all I can think of

**Comment by Qix-** [comment]
I personally like dot notation.

With the test name/function being `testQux`:

- `test/test.js` or `test.js` => `testQux`
- `test/foo.js` => `foo.testQux`
- `test/foo/bar.js` => `foo.bar.testQux`

etc.

**Comment by sindresorhus** [comment]
@Qix- That won't look very pretty for test titles with spaces, which most of mine are.

`test('unicorn rainbow cake')` => `foo.bar.unicorn rainbow.cake`

Probably better to use a non-common symbol, so not to be confused when the user has a test like: `test('foo - bar')` too.

How about `foo › bar › unicorn rainbow cake`?

**Comment by Qix-** [comment]
`foo › bar › unicorn rainbow cake` is great; just make sure to substitute the character on windows since it doesn't support unicode. :+1:

**Comment by sindresorhus** [comment]
@Qix- Yup, we can use [`figures.pointerSmall`](https://github.com/sindresorhus/figures/blob/6b8b7482290192d6eeb3e80508f59ad33bc012f7/index.js#L24).
