### ISSUE TITLE
Suggestion: Run affected tests when sources change

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/ava#535]
Currently when sources change all tests are rerun. It should be possible to track which tests depend on which sources. If a source changes, determine which tests depended on that source. Rerunning just those tests should make for a better `--watch` experience.

**Comment by vdemedes** [comment]
There's an issue for it already - #115. Closing this in favor of the original one.

**Comment by novemberborn** [comment]
Here I was thinking I had original ideas…
