### ISSUE TITLE
Crash when running test-worker without AVA CLI

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#540]
Stack trace:

```js
ava/index.js:26
	log.write();
	    ^

TypeError: log.write is not a function
    at Object.<anonymous> (ava/index.js:26:6)
```

Caused by out-dated code: https://github.com/sindresorhus/ava/blob/master/index.js#L26-L27.
Should be updated to use `console.error` with `chalk`, because `Logger` was adapted for reporting tests.

**Comment by sotojuan** [comment]
How should I test this to make sure I fixed it?
