### ISSUE TITLE
afterEach hook does not run after tests that fail

### ISSUE THREAD

**Issue by KevinMarkVI** [sindresorhus/ava#545]
Built in parallelism lends itself beautifully to using cloud based selenium grids such as Sauce Labs. In order for tests to run successfully, it is necessary for the afterEach hook to be executed whether the test passes or fails, mostly to quit the selenium webdriver. Any help would be much appreciated.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/ava/issues/474 for the planned solution. I think @therealklanni is working on it. Any feedback on the referenced issue thread more than welcome :)

**Comment by KevinMarkVI** [comment]
Thank you!

**Comment by therealklanni** [comment]
I haven't started on it yet, FYI. Been busy working on something else. Might be a few more days before I get around to it.

**Comment by KevinMarkVI** [comment]
Thanks. No rush.
