### ISSUE TITLE
Support `.only` concept for all files

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/ava#549]
Right now, if you have multiple files with multiple tests, and you place `.only` on a test in one of the files, you might expect that it only runs that test (this is how jasmine and mocha operate), but what actually happens is all the tests in the other files will run. All that `.only` does right now is prevent tests in that same file from running.

I think it could be really handy (especially during development) to only run a few tests for the specific feature you're working on.

Right now, it's not entirely unreasonable to work around this by pointing AVA directly at the file that you're working in.

As for what it should be called, honestly I think that it should be `.only` and the current `.only` functionality should be renamed to something like `.onlyInFile` or something... I actually don't see a solid use case for the current functionality so perhaps this feature request could simply be renamed to something like: `Change .only to be scoped to the entire test suite`

Thoughts? :thought_balloon:

**Comment by BarryThePenguin** [comment]
I'm in the same boat as Kent.

I wrote a bit about my use case in #471

I'm not aware of a reason for the current behavior or a `.onlyInFile` method.

**Comment by sindresorhus** [comment]
Agreed. This is a bug.

**Comment by naptowncode** [comment]
Looks like this could be done by sending the `hasExclusive` flag along with `testCount` in the `ava-stats` message. Then if `api.run()` gets any messages with `hasExclusive: true` it could send a `runOnlyExclusive: true` flag to the `ava-run` message. Does that sound right?

**Comment by novemberborn** [comment]
This landed in #556.
