### ISSUE TITLE
Thrown errors with no message are ignored

### ISSUE THREAD

**Issue by kittens** [sindresorhus/ava#553]
```
test("error", () => {
  throw new Error;
});
```

is considered a passed test. This doesn't seem like correct behaviour. Using the latest version of ava. More than happy to submit a PR if someone can point me in the right direction, thanks!

**Comment by sindresorhus** [comment]
This is what I get on master:

```js
❯ ava

  1 passed

```

```js
❯ ava --verbose


  1 test failed

```

Exit code 1 on both, so at least it would fail, even if confusingly.

Seems to be two issues here:
- The default reporter reports false passing.
- None outputs that an error was thrown.

This is only a problem with errors without a message.

-

With:

```
test(() => {
  throw new Error('foo');
});
```

```
❯ ava          

  1 failed

  1. [anonymous]
  failed with "foo"
  Error: foo
    Test.fn (test.js:4:9)
```

**Comment by sindresorhus** [comment]
Honestly not exactly sure where to look without taking a deeper look. It looks like the the error is correctly handled, but doesn't reach the reporters somehow:

```
❯ DEBUG=ava ava

  ava ipc stats:
{ testCount: 1, file: 'test.js' } +0ms
  ava ipc test:
{ duration: 0, title: '[anonymous]', error: { name: 'Error', stack: 'Error\n    Test.fn (test.js:4:9)\n    Test._run (/Users/sindresorhus/dev/ava/lib/test.js:96:14)\n    Test.run (/Users/sindresorhus/dev/ava/lib/test.js:135:17)\n    Sequence._run (/Users/sindresorhus/dev/ava/lib/sequence.js:40:30)\n    Sequence.run (/Users/sindresorhus/dev/ava/lib/sequence.js:23:14)\n    Concurrent.run (/Users/sindresorhus/dev/ava/lib/concurrent.js:42:25)\n    Sequence._run (/Users/sindresorhus/dev/ava/lib/sequence.js:40:30)\n    Sequence.run (/Users/sindresorhus/dev/ava/lib/sequence.js:23:14)\n    Sequence._run (/Users/sindresorhus/dev/ava/lib/sequence.js:40:30)\n    Sequence.run (/Users/sindresorhus/dev/ava/lib/sequence.js:23:14)\n    Runner.run (/Users/sindresorhus/dev/ava/lib/runner.js:99:81)\n    process.<anonymous> (/Users/sindresorhus/dev/ava/index.js:84:10)\n    emitOne (events.js:77:13)\n    process.emit (events.js:169:7)\n    process.<anonymous> (/Users/sindresorhus/dev/ava/lib/test-worker.js:113:10)\n    emitTwo (events.js:87:13)\n    process.emit (events.js:172:7)\n    handleMessage (internal/child_process.js:689:10)\n    Pipe.chan  [anonymous]

  1 passed
  ava ipc results:

```

Notice how the `result` event is empty.

Wild guess, around here somewhere: https://github.com/sindresorhus/ava/blob/e28e24ceb8ca2647c38f3e53d9880a5ea32dacde/api.js#L214

-

@novemberborn @vdemedes Thoughts?

**Comment by novemberborn** [comment]
@sindresorhus it's this line: https://github.com/sindresorhus/ava/blob/e28e24ceb8ca2647c38f3e53d9880a5ea32dacde/api.js#L117

Without a message `isError` is false, and then it unsets it here: https://github.com/sindresorhus/ava/blob/e28e24ceb8ca2647c38f3e53d9880a5ea32dacde/api.js#L136

Will make a PR.

**Comment by novemberborn** [comment]
#555 should fix this.
