### ISSUE TITLE
t.todo(), like t.skip() but without a function

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/ava#563]
I'll often use `test.skip` to notify me and others that there are more tests we could write. I'd like to be able to do this without having to specify a function. Something like:

```javascript
test.skip('adds two numbers together')
test.skip('throws an error when the first argument is a 🐮') // that's for you Sindre :-)
```

Thoughts? :thought_balloon:

**Comment by sindresorhus** [comment]
:+1: Would you like trying to do a pull request?

**Comment by kentcdodds** [comment]
Was going to, but @BarryThePenguin beat me to it :+1:

**Comment by novemberborn** [comment]
More bikeshedding took place in #565. We're going for `t.todo("title")` instead, where a function is not allowed. `t.skip()` will continue requiring a function. Stay tuned all :smile:
