### ISSUE TITLE
feature request: specify electron as test runner instead of node

### ISSUE THREAD

**Issue by talexand** [sindresorhus/ava#572]
It would be a huge benefit to allow ava tests to be run in an electron environment.

Example with tape: http://webuild.envato.com/blog/running-headless-javascript-testing-with-electron-on-any-ci-server/

Mocha runner: https://github.com/jprichardson/electron-mocha

There are lots of frontend things that won't work without a healthy document or window object, so this is a pretty big one.

**Comment by talexand** [comment]
Sadly, browser-run can't seem to fit ava through its pipe and into electron.

test file (test-test.js:

```
import test from 'ava';

test('testing works', t => {
  t.ok(true);
})
```

`browserify test-test.js - t [babelify --presets [es2015 react ]] | browser-run` hangs on that file, despite browserify and babelify in the global namespace.

**Comment by vdemedes** [comment]
Unfortunately, AVA is not yet supported in browsers, see #24. We hope to get there around 1.0.0, which shouldn't be that far away :)

**Comment by mciparelli** [comment]
Ah, how curious, I was just trying to do the same thing. Thanks for the update.

**Comment by alnour-altegani** [comment]
any news about this feature ?

**Comment by bokuweb** [comment]
@alnour-altegany I've implemented avaron https://github.com/bokuweb/avaron. Please try it,  If you'd like.
