### ISSUE TITLE
AVA hangs when `test` is used incorrectly

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/ava#574]
Did some preliminary testing and would seem that code like this causes AVA to hang:

```js
import test from 'ava'

test()
```

Incorrect invocations like these should have better user feedback too.

**Comment by sotojuan** [comment]
I'd like to work on this—would this just require a check on `test()`'s arguments and an appropriate error message?

**Comment by vdemedes** [comment]
@sotojuan Seems like, try and see :)

**Comment by novemberborn** [comment]
> I'd like to work on this

@sotojuan yes that'd be great!

> would this just require a check on test()'s arguments and an appropriate error message?

Yea I think so. It's pretty weird right now, using the mini reporter it just hung, and using `--verbose` it got stuck in a loop complaining about the `test()` call causing an error to be thrown. Besides adding some assertions around required usage and communicating that back to the user I'm rather curious why it got stuck.

**Comment by sotojuan** [comment]
All right, I'll take a look at it later today or Monday. I have an algorithms exam to study for!

**Comment by novemberborn** [comment]
@sotojuan good luck with your exam!

Also note that https://github.com/sindresorhus/ava/pull/565 is already adding some of these messages.
