### ISSUE TITLE
Unnecessary `counted` variable in Api

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/ava#584]
These lines are unnecessary because `counted` is never changed from `false` to `true`.

* https://github.com/sindresorhus/ava/blob/58e1c561296a409a9557ceb1c7684685404c4278/api.js#L184
* https://github.com/sindresorhus/ava/blob/58e1c561296a409a9557ceb1c7684685404c4278/api.js#L187:L189

I'd remove them myself but there's some other stuff to get to. Writing it down here so I don't forget, but if anybody else wants to chime in please do :star2:

**Comment by avivr** [comment]
I'd like to give a try

**Comment by novemberborn** [comment]
@avivr cool!
