### ISSUE TITLE
Default reporter should show a busy indicator

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#598]
Some people have been confused and thought AVA froze, just because it was stuck on showing one test title for a while. This can happen when a lot of async tests are run concurrently and it takes some time for them all to finish.

I'm thinking something simple like:

![untitled12](https://cloud.githubusercontent.com/assets/170270/13506293/0c78b614-e1b0-11e5-92d9-fcbb3f45be1f.gif)

Or

![untitled10](https://cloud.githubusercontent.com/assets/170270/13506294/0c83051a-e1b0-11e5-8655-d4420ab32648.gif)

From: https://github.com/sindresorhus/cli-spinners/blob/master/spinners.json

**Comment by jamestalmage** [comment]
:+1:

**Comment by kasperlewau** [comment]
:+1:
