### ISSUE TITLE
Our reporter tests don't actually test the chalk colors.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#605]
We have lines like:

```js
t.is(output, '   ' + chalk.green('1 passed'));
```

But it still passes if changed to:

```js
t.is(output, '   1 passed');
```

This is because `process.stdout.isTTY` is false in all tests. This is because `tap` forks the process and does not emulate a tty environment in the child process. That will change when we switch to self testing (AVA **does** emulate a tty in child processes if the parent process was a tty).

We should either drop the `chalk.XXX` statements from the tests or force chalk to enable colors.

**Comment by sindresorhus** [comment]
You can force chalk with `chalk.enabled = true;`.

**Comment by sotojuan** [comment]
When I do `chalk.enabled = true;` on the mini reporter (and others I am guessing), a lot of tests [fail](https://i.imgur.com/irqu9Ab.png).

I'm guessing I need go to back and fix them? What is happening is that the `lib/colors.js` usage in `lib/mini.js` is making the tests fail. If I go back to `lib/mini.js` and change all of those back to `chalk`, the tests pass.

**Comment by jamestalmage** [comment]
```js
var colors = require('../lib/colors');
Object.keys(colors).forEach(function (key) {
  colors[key].enabled = true;
});
```
