### ISSUE TITLE
Importing ES2015 package doesn't work

### ISSUE THREAD

**Issue by adius** [sindresorhus/ava#608]
## Description

Clone the repo at https://gist.github.com/adius/1f2167b01db05f4d09c9 and run `npm test`. I get the error message in `error.txt`, but this should work, shouldn't it?

## Environment

Node.js v5.7.0
darwin 15.3.0

**Comment by sindresorhus** [comment]
> AVA currently only transpiles the tests you ask it to run. It will not transpile modules you import from outside of the test. - https://github.com/sindresorhus/ava#transpiling-imported-modules

This will be possible in the next version as soon as https://github.com/sindresorhus/ava/pull/573 lands ;)

**Comment by adius** [comment]
Oh, sorry. I forgot to update the repo.
I meant the version with `require 'babel-register`, which is not working either.
Please check out the repo again!

**Comment by changbenny** [comment]
I just encountered the similar problem and turned out that I forgot the `.babelrc` file.
Maybe helpful to you.

**Comment by jamestalmage** [comment]
I just checked the repo, adding an appropriate `.babelrc` should fix your issue.

Ping back if it doesn't.
