### ISSUE TITLE
Improve source pattern handling

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/ava#614]
Watch mode lets you configure which source files should be watched. Certain directories are ignored by default, using <https://github.com/novemberborn/ignore-by-default>. Currently if you use a negation pattern in `--source` it stops ignoring those default directories. This is annoying as you'll have to repeat them manually.

It would be good to stop one of those default directories from being ignored. Then we could let you specify a negation pattern without disabling *all* default ignore patterns.

You can find the current logic at <https://github.com/sindresorhus/ava/blob/1868204c1901f45b4f66a520ef6486fdd71fe1d2/lib/watcher.js#L273:L276>.

**Comment by novemberborn** [comment]
Perhaps `!!node_modules/**/*` can be used to disable the `!node_modules/**/*` pattern. Then we change the aforementioned logic to include the remaining patterns.

**Comment by sindresorhus** [comment]
@novemberborn I don't think we should invent our own glob patterns.

> Currently if you use a negation pattern in --source it stops ignoring those default directories.

Why?

-

I'm failing to see the problem here. Maybe provide an example?

**Comment by novemberborn** [comment]
Hmm. The problem may be different actually. We should be able to merge the ignore patterns. However it should be possible to override a pattern.

For example you might want to treat a dependency as a source so you can more easily debug that dependency and it's impact on your own project. I'll need to verify whether adding `node_modules/somedependency/**/*.js` works or whether `!node_modules/**/*` overrides it. Will update the issue.

**Comment by novemberborn** [comment]
#730 ensures that:

* You can specify negated patterns without having to declare the default exclusion patterns
* You can override the default exclusion patterns. E.g. specifying `node_modules/some_dir/**/*` will select that directory as a source, while the default exclusion pattern `node_modules/**/*` remains in effect
