### ISSUE TITLE
t.same is not deepEqual

### ISSUE THREAD

**Issue by iamstarkov** [sindresorhus/ava#617]
I'm trying to use ava to test my upcoming Promise-based module. I faced a problem
that `t.same` behaves not the same way as `assert.deepEqual`.

My [tests][tests] are:
```js
import test from 'ava';
import saveToDeps from './index';
import { deepEqual } from 'assert';

test('basic t.same', t => saveToDeps({}, ['a@1.0.0'])
  .then(res => {
    t.same(res, { a: '1.0.0' });
  }));

test('basic assert.deepEqual', () => saveToDeps({}, ['a@^1.0.0'])
  .then(res => {
    deepEqual(res, { a: '^1.0.0' });
  }));

test('sorted t.same', t => saveToDeps({}, ['b@1.0.0', 'a@1.0.0'])
  .then(res => {
    t.same(res, { a: '1.0.0', b: '1.0.0' });
  }));

test('sorted assert.deepEqual', () => saveToDeps({}, ['b@1.0.0', 'a@1.0.0'])
  .then(res => {
    deepEqual(res, { a: '1.0.0', b: '1.0.0' });
  }));
```

and the [log][log] is:

```
  ✖ basic t.same   

  t.same(res, { a: '1.0.0' })

         |                   

         Object{a:"1.0.0"}   

  

  ✔ basic assert.deepEqual

  ✖ sorted t.same   

  t.same(res, { a: '1.0.0', b: '1.0.0' })

         |                               

         Object{a:"1.0.0",b:"1.0.0"}     

  

  ✔ sorted assert.deepEqual

  2 tests failed

  1. basic t.same

  AssertionError: { a: '1.0.0' } === { a: '1.0.0' }

    test.js:7:7

    

  2. sorted t.same

  AssertionError: { a: '1.0.0', b: '1.0.0' } === { a: '1.0.0', b: '1.0.0' }

    test.js:17:7
```

[tests]: https://github.com/iamstarkov/save-to-deps/blob/ava/bug-demo/test.js
[log]: https://travis-ci.org/iamstarkov/save-to-deps/jobs/114487096

Steps to reproduce:
```
git clone git@github.com:iamstarkov/save-to-deps.git
cd save-to-deps
git checkout ava/bug-demo
npm install
npm test
```

## Environment

```
Node.js v5.7.0
darwin 15.3.0
```

**Comment by sindresorhus** [comment]
> t.same behaves not the same way as assert.deepEqual

It's not the same as `assert.deepEqual`. It's [`assert.deepStrictEqual`](https://github.com/sindresorhus/deep-strict-equal).

**Comment by iamstarkov** [comment]
then i got it wrong from the [`.same` docs](https://github.com/sindresorhus/ava#samevalue-expected-message), sorry.

`deep-strict-equal` [doesn't have problems](https://tonicdev.com/56aa3c3f3c22eb0d00bb361c/56deca7f1363500c00352280) with same object values though:

```js
var eq = require("deep-strict-equal");
//   AssertionError: { a: '1.0.0' } === { a: '1.0.0' }
eq({ a: '1.0.0' }, { a: '1.0.0' }); // true
```

Am I doing something wrong?

**Comment by iamstarkov** [comment]
So, its because of [`sorted-object`](https://github.com/domenic/sorted-object/blob/master/test/tests.js#L19) which im using returns [Object with `null` in prototype](https://github.com/domenic/sorted-object/blob/master/test/tests.js#L19)

**Comment by sindresorhus** [comment]
Try https://github.com/sindresorhus/sort-keys instead ;)

**Comment by iamstarkov** [comment]
@sindresorhus i will in next projects, but current one is tightly coupled with npm dependencies and `sorted-object` is the package which npm is using for sorting dependencies.
