### ISSUE TITLE
Nested tests?

### ISSUE THREAD

**Issue by matthewmueller** [sindresorhus/ava#62]
One thing that's nice about nested tests is being able to support different before, after, beforeEach, and afterEach functions.

Would probably be a pretty large refactor, but I could see API looking like this:

```js
test('a model', function(t, test) {
  test('should do this', function (t) {
      // do test
  }) 
})
```

**Comment by Qix-** [comment]
With the nature of AVA as I understand, I can't imagine this taking much work.

**Comment by sindresorhus** [comment]
Shouldn't be very hard. Not sure we want this, though. I've honestly never needed it. You could achieve the same thing with multiple files (which would also be beneficial for parallelism). Do you have a real scenario you could link to where this was useful?

**Comment by Qix-** [comment]
:+1: for multiple files anyway. I think it's intended to be synonymous with Mocha's `describe()`, which would definitely be better with multiple files IMO.

**Comment by matthewmueller** [comment]
not a big deal either way. files usually correspond 1:1 with what file they're testing. it's often useful when testing say, a user model, to have different bootstrapping functions. 

alternatively, this could also be achieved with something along the lines of:

```js
test('a model', function (t) {
  t.before(function() { ... })
})

test('a model', function (t) {
  t.after(function() { ... })
})
```

which would work without nesting.

**Comment by ahdinosaur** [comment]
hey. :cat: it's worth mentioning that [`tape`](https://www.npmjs.com/package/tape) supports [nested tests with `t.test`](https://github.com/substack/tape#ttestname-cb), e.g.

```
test('a test', function(t) {
  t.test('a sub-test', function (t) {
    // do test
  }) 
})
```

personally, i think this would be awesome for `ava`, especially if `t.test` included all the other methods of `test`, e.g. `.before` and `.after` methods:

```
test('a test', function(t) {
  t.test.before(function (t) {
    // setup
  })

  t.test.after(function (t) {
    // teardown
  })

  t.test('a sub-test', function (t) {
    // do test
  }) 
})
```

**Comment by dbkaplun** [comment]
+1, would you accept a PR for this?

**Comment by sindresorhus** [comment]
I still feel it's an anti-pattern and nobody has convinced me otherwise. Having tests in separate files instead of nesting has the benefit of cleaner test files and [parallelism](https://github.com/sindresorhus/ava/#isolated-environment).

@vdemedes @kevva Thoughts?

**Comment by vdemedes** [comment]
Honestly, I don't think it's a good idea. It does not look good, it will cause bugs and it does not make much sense to use `test` as an alternative to `describe` in mocha.

**Comment by matthewmueller** [comment]
closing since there doesn't seem to be much interest by the authors.

**Comment by whitecolor** [comment]
The only good case I see use to have nested is too include (using `.only`) or exclude `(.skip`) bunch of tests.

**Comment by jamestalmage** [comment]
Locking in favor of duplicate #222.

Please move all discussion there.
