### ISSUE TITLE
test.todo() doesn't work

### ISSUE THREAD

**Issue by zweicoder** [sindresorhus/ava#620]
```
$ ./node_modules/.bin/ava --version
0.12.0

$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v4.2.2
linux 3.19.0-51-generic
```

I'm trying to do:
 `test.todo('Router#postValidate after finishing feature');` 
but I'm getting:
  `TypeError: _ava2.default.todo is not a function`

**Comment by zweicoder** [comment]
`test.skip` also seems to be stuck in some loop continually failing tests. I'll open a new issue if needed.

**Comment by novemberborn** [comment]
`test.todo` is new and not in 0.12. See <https://github.com/sindresorhus/ava/compare/v0.12.0...master> for the full set of changes. We'll probably release a new version in the next few days.

In the meantime you could use `npm install sindresorhus/ava` to get access to the new features.
