### ISSUE TITLE
Mini reporter goes mad when the terminal width is smaller than the test title

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#629]
To reproduce, make your terminal width narrow and try running the [`got`](https://github.com/sindresorhus/got) tests.

![untitled12](https://cloud.githubusercontent.com/assets/170270/13673220/acf59e18-e70a-11e5-863a-08c975bf8d9e.gif)

**Comment by jamestalmage** [comment]
What is the best way to fix? 

Truncate the title or try to account for the wrapping when deleting?

The first is probably easier than the second, but both should be doable.

**Comment by sindresorhus** [comment]
I was going to say wrapping, but it looks very ugly, so let's go with truncation. Can use `…` character to indicate it's truncated.
