### ISSUE TITLE
Test silently ignored

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/ava#63]
Found here - https://github.com/kevva/download/pull/77#issuecomment-141836144

Consider this test file: 

```js
var test = require('ava');

test('no asserts', function (t) {
    // still passes
});
```

`ava` will exit silently without `no asserts` test in output.

**Comment by floatdrop** [comment]
Even if `t.plan` is specified in test - same result.

```js
var test = require('ava');

test('no asserts', function (t) {
    t.plan(4);
    // ignored and ava exit's fine
});
```

**Comment by shinnn** [comment]
Yeah, ava should exit with non-zero code in this case.

**Comment by Qix-** [comment]
Doesn't Ava have a timeout?

**Comment by sindresorhus** [comment]
Probably related to https://github.com/sindresorhus/ava/issues/15.

**Comment by floatdrop** [comment]
@sindresorhus yes, tracking pending assertions will cover this case also.
