### ISSUE TITLE
Improve reporter output when watch mode runs test files without exclusive tests

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/ava#635]
`.only` is sticky in watch mode. If the watcher detects it in one file, and then needs to run tests from another, it only runs exclusive tests from that second file. If the second file does not contain any exclusive tests *no tests are run*. With the mini reporter the output in this case is simply "0 tests passed". This may be confusing to users.

Instead the reporters (mini, verbose and tap) should detect this scenario and output something like "no exclusive tests found".

**Comment by jamestalmage** [comment]
I kinda think if there are `.only` tests we should abandon the whole smart rerun thing and just run all files with a `.only` whenever any change is detected (regardless of dependency graph). It is understood that `.only` is a temporary way of focusing on just a few tests. If a user has specified `.only` on two tests in separate files at the same time, we should trust that they know what they want and always rerun both.

**Comment by novemberborn** [comment]
I think we'd have to rerun all tests, in case you add a `.only` in another file. Of course if you then remove the `.only` it would run the full suite. May not be too much of a problem though.

**Comment by jamestalmage** [comment]
> I think we'd have to rerun all tests, in case you add a `.only` in another file

Unchanged files that did not have `.only` before will not need to be run again.

**Comment by novemberborn** [comment]
> Unchanged files that did not have .only before will not need to be run again.

Oh good point!

We could simplify the implementation then:

* Still track which files contain exclusive tests
* When running specific test files, *also* run the files containing exclusive tests

We'll no longer need to pass options to `Api#run()`.
