### ISSUE TITLE
Add test type, eg., `required` that runs before serial, acts as serial, but bails on error

### ISSUE THREAD

**Issue by thomaslindstrom** [sindresorhus/ava#641]
## Description

I know `bail` can be set as a test option, but that's an option for *all* tests. There should be a, eg., `.required` test type that:
- ... is ran first (before serial tests)
- ... acts as serial tests, because all `required` tests should be prerequisites for the latter
- ... on error, causes the test to `bail`

I guess you could compare the functionality to `before`, but `before` is strictly for test *setup*, not tests per se.

## Test

I wrote a test to explain what I'm trying to achieve:

``` 
test('run required tests first, and if one fails, stop testing', function (t) {
	var runner = new Runner();
	var arr = [];

	runner.test(function (a) {
		arr.push('a');
		a.end();
	});

	runner.required(function () {
		arr.push('b');
		throw new Error(); // bail here and display results for tests that already ran
	});

	runner.serial(function (c) {
		arr.push('c');
		c.end();
	});

	runner.required(function (d) {
		arr.push('d');
		d.end();
	});

	runner.run({}).then(function () {
		console.log(arr);

		t.same(arr, ['b']);
		t.end();
	});
});
```

**Comment by novemberborn** [comment]
You could use `before` to set up prerequisites.

Could you give an example where you require certain tests to pass before even attempting others?

**Comment by thomaslindstrom** [comment]
As pointed out:
> I guess you could compare the functionality to `before`, but `before` is strictly for test setup, not tests per se.

`before` should be used to prepare data used in the test, not *to test*.

One example I can think of is creating a user – which on its own is a test, but that also is a prerequisite for latter tests where the user created is the one tested against. In that case, those tests will always fail, and there's no point in running them.

**Comment by vdemedes** [comment]
I don't think it fits AVA's atomic tests philosophy. One failed test should not stop or cause all the other ones to fail.

As for your example use case, I think it can and probably should be treated as a set up step.

**Comment by jamestalmage** [comment]
> I don't think it fits AVA's atomic tests philosophy. 

:+1: agreed

**Comment by sindresorhus** [comment]
> I don't think it fits AVA's atomic tests philosophy.

:+1: 

-

Sorry @thomaslindstrom. More than happy to consider other proposals :)

**Comment by thomaslindstrom** [comment]
This would *actually* be more than syntax sugar, as it doesn't really do more than what's in already. 

But alright, guys! Thanks for considering. 🐙
