### ISSUE TITLE
Readme question - how is it possible to use async/await in nodejs?

### ISSUE THREAD

**Issue by idchlife** [sindresorhus/ava#649]
I did not get through readme here, how do you use async () => {} await etc., when it's if I'm not mistaken impossible to write yet in node?

**Comment by vdemedes** [comment]
AVA has Babel built-in, which allows writing tests using latest JS language features without any configuration on your side. In other words, you just create a `test.js` (for example), write tests in ES6/7 and simply `$ ava test.js`. Try it on practice, it's easier to understand it that way ;)
