### ISSUE TITLE
why your node support import

### ISSUE THREAD

**Issue by awesomes-cn** [sindresorhus/ava#668]
My environment is 
```
Node.js v5.8.0
linux 3.13.0-32-generic
```
when I run your demo 
```
import test from 'ava';

test(t => {
    t.same([1, 2], [1, 2]);
});
```
I got the error 
```
import test from 'ava';
^^^^^^

SyntaxError: Unexpected token export

```
This is because my node environment didn't support the `import` syntax.

So,why your node support this?

**Comment by sindresorhus** [comment]
It's clearly explained in the documentation: https://github.com/sindresorhus/ava#es2015-support

(Translation: https://github.com/sindresorhus/ava-docs/pull/17/files#diff-ffcaea08d53883913f740e672af4c9daR539)

AVA comes with Babel bundled which transpiles your test files down to ES5, including `import` into `require` calls.
