### ISSUE TITLE
Disable --tap in --watch mode

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#672]
You can't really do `--watch --tap`, the output stream never ends, so you only get a report for the first run, then just raw TAP output:

```
$ ava --watch --tap | mocha-tap-reporter spec


  ✓ test › create must be a function
  ✓ test › maxSize must be number
  ✓ test › it will create up to maxSize handlers as needed
  ✓ test › a new handler will not be created if one is already returned to the stack
  ✓ test › pending requests will be executed as handlers are returned
  ✓ test › it will pass through the args
ok 7 - test › create must be a function
ok 8 - test › maxSize must be number
ok 9 - test › it will create up to maxSize handlers as needed
ok 10 - test › a new handler will not be created if one is already returned to the stack
ok 11 - test › pending requests will be executed as handlers are returned
ok 12 - test › it will pass through the args
1..6
ok 13 - test › create must be a function
ok 14 - test › maxSize must be number
ok 15 - test › it will create up to maxSize handlers as needed
ok 16 - test › a new handler will not be created if one is already returned to the stack
ok 17 - test › pending requests will be executed as handlers are returned
ok 18 - test › it will pass through the args
1..6
```

---

It's probably not possible to fix this and continue to just use the bash pipe operator to pass our output to the reporter. Since our stream never ends, I don't think the reporter will ever print it's summary, nor will it know to reset itself (I could be wrong - it seems the reporters could figure this out from the `plan` line, but that is likely pretty brittle).

One option would be to incorporate `tap-mocha-reporter` as an (optional?) dependency and allow a `--tap-reporter` flag. We could then handle creating separate streams for each test run, piping them to a new reporter instance each time, and correctly ending the stream.

The final option would be "Sorry, no TAP output in watch mode". Personally, I am totally fine with this option, since I prefer our own reporters. I think the real value of TAP is realized on CI servers (where you could use it to create automated reports, etc).

---

Also note that the tap reporter doesn't reset the test id on subsequent runs (that is a bug unless we choose the "sorry" option).

**Comment by sindresorhus** [comment]
> I could be wrong - it seems the reporters could figure this out from the plan line, but that is likely pretty brittle

It's possible with [`tap-finished`](https://github.com/substack/tap-finished), but every TAP reporter would have to support this, which is not realistic.

> The final option would be "Sorry, no TAP output in watch mode". Personally, I am totally fine with this option, since I prefer our own reporters.

:+1: Let's just ignore the `--tap` flag in watch mode and document the behavior. Using our reporters, we can optimize the output in watch mode, like for example adding timestamps. TAP is for normal test runs.

**Comment by novemberborn** [comment]
+1 to ignore the `--tap` flag in watch mode.

Was thinking maybe to not even start watch mode but that's annoying if you specify the tap option in the config. Maybe print a warning?

**Comment by jamestalmage** [comment]
> Was thinking maybe to not even start watch mode 

:-1: I agree with you, that would be annoying.

> if you specify the tap option in the config. Maybe print a warning?

:+1: Ignore `tap:true` in the config if they use `--watch`.

If they specify both `--watch --tap` on the command line maybe it should just throw and bail. I could see someone trying that when they are trying to figure out why they aren't getting tap in watch mode.

**Comment by sindresorhus** [comment]
:+1: Sounds good.

**Comment by cameronroe** [comment]
Any chance that this could be added in a future release? This would be really great to have!

**Comment by MaffooBristol** [comment]
I was looking into https://github.com/axross/tap-notify, which is rather cool. But not being able to do it on watch kinda defeats the point. There has to be some way of getting them working together.

Or what about even having desktop notifications built into ava?

**Comment by schickm** [comment]
@MaffooBristol better late than never...

If you want something that behaves like having watch mode enabled, but also can do tap reporting then you're going to need to use some other tooling to make that happen.  Here's my one liner (which requires having `fswatch` and `xargs` available:

```
fswatch -o src |  xargs -I{} sh -c 'yarn ava --tap | yarn dlx tap-notify'
```

fswatch pipes an event to xargs everytime a file in changed in src/.  Xargs then executes the specified shell script.  It bears noting that if I had a package.json script defined I could just execute that and drop the `sh -c '...'` business:

```
fswatch -o src |  xargs -I{} yarn some-script
```
