### ISSUE TITLE
Equality assertions are broken on objects from... different places?

### ISSUE THREAD

**Issue by cryptoquick** [sindresorhus/ava#677]
## Description

I'm guessing it's due to the work that's been going on related to #640 because I have an object literal that comes from one place, then I assert it is the same as an object that's defined in the test with `.same` / `.is` assertions. I'm being told of an assertion error. However, if I stringify my objects and then compare them, there's no difference.

## Environment

```
ava 0.13.0
Node.js v5.6.0
darwin 15.3.0
```

**Comment by sindresorhus** [comment]
Yes, this is fixed in master. We'll do a release soon. For now you can do `$ npm i -S sindresorhus/ava#f2c0709` to get latest master.

**Comment by cryptoquick** [comment]
Strange... I ran your command, and received:
`Error: ENOENT: no such file or directory, open '/Users/hunter/GitHub/SlackPass/node_modules/.cache/ava/53092e4a64bb20eef9a4d3d19e78ec18.js.map'`
I subsequently nuked the node_modules folder, had npm pour me another, and tried my tests again... No dice.

![Assertion Error](http://i.imgur.com/ltHL4Jf.png)

**Comment by cryptoquick** [comment]
Also, before I nuked my `node_modules`, I ran your command with `--save-dev`. It's in my `package.json` as:
```  "devDependencies": {    "ava": "github:sindresorhus/ava#f2c0709", ...```

**Comment by cryptoquick** [comment]
Oh, that's weird... `country:null`

**Comment by cryptoquick** [comment]
Bam! We're good on this one, bud. :+1: 

![Awesome!](http://i.imgur.com/rdaIFVy.png)
