### ISSUE TITLE
Should t.same use assert.deepStrictEqual?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#68]
Hi

The `t.same` method uses `assert.deepEqual`. This is also true when primitives do not have the same type. When using `assert.deepStrictEqual`, this is not the case.

```
assert.deepEqual({foo: 5}, {foo: '5'});
// true

assert.deepStrictEqual({foo: 5}, {foo: '5'});
// false
```

Same for `t.notSame`.

If for some reason, the implementation should be kept this way, new assertions can be added? `t.strictSame` and `t.notStrictSame` or something like that.

**Comment by vdemedes** [comment]
Good point, I think we should switch. @sindresorhus what do you think?

**Comment by SamVerschueren** [comment]
Not sure when the strict variants where introduced though. They do not exist in 0.12 so maybe we should use a ponyfill for older versions?
