### ISSUE TITLE
Change default depth of power-assert rendering to 3

### ISSUE THREAD

**Issue by josdejong** [sindresorhus/ava#681]
**Moderator UPDATE:** We've decided to change the default depth to 3. PR Welcome!

--

I'm using ava since some time, it works like a charm! Thanks.

One issue I regularly encounter is that I'm having unit tests which compare arrays containing objects. When a test fails, the nested contents of these arrays is not displayed, making it very hard to compare (I have to manually insert console.logs to output actual and expected arrays). The `power-assert` library has options like `maxDepth` (1 by default), which I would like to configure with a higher value in order to see the nested contents of my arrays.

Is there a way to pass configuration to `power-assert` via `ava`? If not, it would be great if support for this could be implemented.

**Comment by sindresorhus** [comment]
I would honestly prefer we handled most cases nicely by default. Adding options is last resort.

Can you link to the power-assert options docs?

-

@twada Any way we could handle this case nicely automatically?

**Comment by josdejong** [comment]
Sure, the options of `power-assert-formatter` are described here:

https://github.com/power-assert-js/power-assert-formatter#var-formatter--createformatteroptions

The constructor `createFormatter(options)` is used here in `ava`:

https://github.com/sindresorhus/ava/blob/master/lib/enhance-assert.js#L43-L53

```js
function formatter() {
	var powerAssertFormatter = require('power-assert-formatter');
	var powerAssertRenderers = require('power-assert-renderers');

	return powerAssertFormatter({
		renderers: [
			powerAssertRenderers.AssertionRenderer,
			powerAssertRenderers.SuccinctRenderer
		]
	});
}
```

So as a workaround I changed this to the following in my local installation of ava:
```js
function formatter() {
	var powerAssertFormatter = require('power-assert-formatter');
	var powerAssertRenderers = require('power-assert-renderers');

	return powerAssertFormatter({
		maxDepth: 5,
		renderers: [
			powerAssertRenderers.AssertionRenderer,
			powerAssertRenderers.SuccinctRenderer
		]
	});
}
```
(but that breaks with every update of my dependencies so it's not really practical)

Personally I think the best default value for `maxDepth` would be a *large* value, it's better to output the whole data structure then to hide part of it.

**Comment by twada** [comment]
@josdejong Right, and you can dump everything if you set `maxDepth: 0`

However when you dump everything, you also find that some objects are really huge (e.g. DOM) and your terminal will be overwhelmed with such dumps. Therefore I decided to set default depth to shallow enough (yes, `1`. But sometimes I also feel it's too shallow)

I've found that `formatter` is used at [ava/api.js](https://github.com/sindresorhus/ava/blob/master/api.js#L20), near enough to the options. However, 

> Adding options is last resort.

@sindresorhus Agreed.

>  Any way we could handle this case nicely automatically?

@sindresorhus Not yet. But it's worth trying.

**Comment by josdejong** [comment]
Thanks @twada , I didn't know about the `maxDepth: 0`. 

You will always need to *some* limitation to prevent too large outputs like `maxDepth` does. But there are also always cases where you need to see more then the configured limit. 

It would indeed be nicest not to introduce new options. Just thinking aloud, can we reuse the existing option `--verbose` to output objects without limit?

**Comment by novemberborn** [comment]
> Just thinking aloud, can we reuse the existing option --verbose to output objects without limit?

Currently `--verbose` selects a more verbose reporter which shows all test titles. I'm not sure it should impact `power-assert` depth, that feels like another level of verbosity.

**Comment by jamestalmage** [comment]
What @novemberborn said.

**Comment by Qix-** [comment]
Yeah, this is an issue for me.

I have a simple object that is two levels deep and I'm seeing

```
Object{model:"rgb",value:#Array#}
```

which doesn't help me _at all_.

**Comment by novemberborn** [comment]
I'm :+1: for changing the default depth to `3`.

**Comment by twada** [comment]
I'm :+1: on changing the default depth to `3`, however would you wait for landing of #703 ?

**Comment by jamestalmage** [comment]
> however would you wait for landing of #703 ?

I don't think increasing to 3 would make things any worse. I believe the whole object get's serialized anyways. It is just the renderer that changes depth.

**Comment by novemberborn** [comment]
Yea, we can do this regardless of #703.

**Comment by twada** [comment]
Okay, let's go ahead :wink:

**Comment by josdejong** [comment]
Thanks for picking this up!

**Comment by Qix-** [comment]
thanks everyone!!
