### ISSUE TITLE
Custom babel configuration

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/ava#685]
## Description

I have this in my package.json (tried the `inherit` way as well). But when I run `ava` (version 0.13.0) I get a `SyntaxError: Unexpected token import`.

```
  "ava": {
    "babel": {
      "presets": [
        "es2015",
        "stage-0"
      ]
    }
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ]
  },
```

In the test file itself, the import seems to work fine `import server from '../index';`, because the error is being reported from within the `../index.js` file, so it's strange.

## Environment

```
Node.js v5.5.0
linux 4.4.1-2-ARCH
```

**Comment by jamestalmage** [comment]
@rightaway, add `"require": ["babel-register"]` to your AVA config:

```
  "ava": {
    "babel": {
      "presets": [
        "es2015",
        "stage-0"
      ]
    },
    "require": ["babel-register"]
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ]
  },
```

AVA currently only supports transpiling your test files for you. Not your source files. This is why you need to use `babel-register`. Note that we do intend to add the source transpilation feature at some point, so be sure to watch release notes when upgrading versions.

**Comment by rightaway** [comment]
Now it looks like this and has resolved that problem. But I'm getting `ReferenceError: regeneratorRuntime is not defined`. Seems like I need `babel-polyfill` to solve this? But where should I define this in package.json or elsewhere?

```
  "ava": {
    "babel": "inherit",
    "require": ["babel-register"]
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ]
  },
```

**Comment by jamestalmage** [comment]
Hmm. That's weird. Try `npm install babel-runtime`

**Comment by rightaway** [comment]
Have just tried it but I get the same error. Any other ideas?

**Comment by jamestalmage** [comment]
Can you create a project with a minimal reproduction and upload to github? It will be easier for us to troubleshoot that way.

**Comment by spudly** [comment]
Just require babel-polyfill also:

```js
  "ava": {
    "babel": "inherit",
    "require": ["babel-register", "babel-polyfill"]
  },
```

**Comment by rightaway** [comment]
@spudly works, thank you. Just out of curiosity, it seems like babel-register and babel-polyfill were already in my node_modules folder (probably as dependencies of other babel stuff). Is it good practice to explicitly declare both of these under devDependencies in package.json, or should I just leave it as is?

**Comment by spudly** [comment]
@rightaway, I would definitely add it as an explicit dev dependency.
