### ISSUE TITLE
Add strict mode in `enhanced-assert.js`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#687]
I tried to add `'use strict';` to https://github.com/sindresorhus/ava/blob/master/lib/enhance-assert.js, but got:

```
not ok TypeError: Cannot assign to read only property 'AssertionError' of #<Object>
    at:
      line: 9
      column: 1147
      file: lib/enhance-assert.js
      function: enhanceAssert
    stack: |
      enhanceAssert (lib/enhance-assert.js:9:1147)
      Object.<anonymous> (lib/test.js:9:14955)
      Module.replacementCompile (node_modules/append-transform/index.js:58:13)
      module.exports (node_modules/default-require-extensions/js.js:8:9)
      Object.<anonymous> (node_modules/append-transform/index.js:62:4)
      Object.<anonymous> (test/test.js:6:12)
      Module.replacementCompile (node_modules/append-transform/index.js:58:13)
      module.exports (node_modules/default-require-extensions/js.js:8:9)
      Object.<anonymous> (node_modules/append-transform/index.js:62:4)
    test: TAP
    message: "TypeError: Cannot assign to read only property 'AssertionError' of #<Object>"
```

Seems https://github.com/sindresorhus/ava/blob/e6b60bf3e9f1014391950af26716d59f9e22c51d/lib/enhance-assert.js#L38 is read-only.

-

// @twada @jamestalmage

**Comment by twada** [comment]
@sindresorhus 

Because `assert.AssertionError` is defined as read-only here?
https://github.com/sindresorhus/ava/blob/e6b60bf3e9f1014391950af26716d59f9e22c51d/lib/assert.js#L10

**Comment by twada** [comment]
The line (https://github.com/sindresorhus/ava/blob/e6b60bf3e9f1014391950af26716d59f9e22c51d/lib/enhance-assert.js#L38) could be deleted safely. @jamestalmage What do you think?

**Comment by sindresorhus** [comment]
Oh, right, duh. I thought the enhancement caused it...

**Comment by novemberborn** [comment]
Yea looks like the line could just be deleted, and then `use strict` can be added.
