### ISSUE TITLE
[Coveralls]  SOURCE NOT AVAILABLE

### ISSUE THREAD

**Issue by paulohp** [sindresorhus/ava#690]
I'm trying to look at coveralls.io to help on improving the code coverage #161 and I'm getting this message:

```
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.
```

https://coveralls.io/builds/5567425/source?filename=cli.js

**Comment by sindresorhus** [comment]
No idea what went wrong there, but it's available in the latest commit, so probably just a glitch.

https://coveralls.io/builds/5643290/source?filename=cli.js

**Comment by paulohp** [comment]
Solid. Thanks.

**Comment by achecopar** [comment]
I am trying to access the links and get an error message, was it moved somewhere else?

WE CAN'T FIND THAT PAGE.
You may have mistyped the address or the page may have moved - head back to the homepage Comradel!
