### ISSUE TITLE
Watch mode should remember failures from tests it does not rerun.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#699]
## Issue

`failing-test.js`:

```js
import test from 'ava';

test(t => t.fail('oh no!'));
```

`passing-test.j2`:

```js
import test from 'ava';

test(t => t.pass('yeah!'));

// add more tests here
```

Given the above tests in watch mode, if you continue to edit `passing-test.js` (or any file that does not cause `failing-test.js` to be rerun), you will not be reminded that there are previously failing tests which were not rerun.

## Solution

I think we should track previous failures and show a message like:

```
3 passed
2 failing
2 previously failing tests were not rerun
```

The above shows 3 passing and 2 failing tests that were rerun. It also mentions 2 tests that were not rerun because the watch algorithm did not detect any changes.

## Alternate solution

Always rerun files that had failing tests regardless.

**Comment by novemberborn** [comment]
> Always rerun files that had failing tests regardless.

I'd like to avoid that overhead.

If we tackle #672 then it should be fairly straightforward to inform the reporter of the previously failed tests. Shouldn't be too hard to track them in the watcher either.

**Comment by andykais** [comment]
Is it possible to disable this message now? I realize it can be useful, but most of the time its just noise. I really care about the test I am currently iterating on. When I want to know if all tests pass, I will run the whole test suite. Also, consider this use case:

```
ava --watch
```

```javascript
// a.test.js
test('sometest', t => {
  t.is(1, 1)
  t.is(1, 2)
})
```
now I edit `a.test.js`
```javascript
// a.test.js
test('sometest', t => {
  t.is(1, 1)
})
```
and I am stuck with the message 
>   1 previous failure in test files that were not rerun
until I stop and start the test runner.

**Comment by novemberborn** [comment]
> Is it possible to disable this message now?

I don't think this is something we need to have an option for.
