### ISSUE TITLE
Watch support

### ISSUE THREAD

**Issue by rwu823** [sindresorhus/ava#70]
$ ava --watch

Is this a plan?

**Comment by scottcorgan** [comment]
You could probably just use the [onchange](https://github.com/Qard/onchange) module.

```json
{
  "scripts": {
    "test": "onchange 'test/*.js' -- ava test/*.js"
  }
}
```

**Comment by Whoaa512** [comment]
or nodemon
```
{
  "scripts": {
    "test": "nodemon test/*.js --exec ava"
  }
}
```

**Comment by floatdrop** [comment]
In fact I would be cool, if ava could run only changed test in a file, not a whole file with tests.

**Comment by schnittstabil** [comment]
I think the common use case is watching the source directory and the test directory (not only the current existing files). And I suppose that the sources change far more often than the test.

**Comment by asbjornenge** [comment]
There is also the [watch](https://en.wikipedia.org/wiki/Watch_(Unix)) unix command. 

But none of these can be compared to ava supporting filewatching internally. I love the **fast feedback loop** `mocha -w` gives me, and would :heart: to see `ava` have this feature.

**Comment by sindresorhus** [comment]
This is now PR welcome. Should use https://github.com/paulmillr/chokidar.

@tomazzaman has indicated in #458 that he's interested in working on this.

**Comment by vdemedes** [comment]
@sindresorhus Are you sure AVA is ready for this feature? We have lots of perf/babel issues on the table to solve. Watch feature is not that important like providing great experience (especially first experience) to the users.

**Comment by sindresorhus** [comment]
@vdemedes I'm afraid of that too, but I'm thinking we add it undocumented, dogfood it, and only document it when we feel it's stable enough and we're ready to take on the addition support burden. And many people have told me `watch` is a big reason for them to stay with Mocha, which makes me think `watch` is part of providing a great experience.

**Comment by vdemedes** [comment]
@sindresorhus Ok, sounds like a plan ;)

**Comment by tomazzaman** [comment]
I too come from Mocha-world and this was by far bigger selling point than speed. I want continuous feedback loop more than speed.

**Comment by sindresorhus** [comment]
@tomazzaman Thanks. The more usage feedback we get on issues, the easier it is for us to make informed choices :) Feel free to comment opinions on any other issue. You might also like https://github.com/sindresorhus/ava/issues/115.

**Comment by tomazzaman** [comment]
Ha! Indeed I like it, but not sure whether my JS skills are there yet. I've written a few watchers for my own projects (so I know a thing or two about it), but nothing as complex as #115. Maybe I'm just needlessly intimidated though :)

**Comment by sindresorhus** [comment]
@tomazzaman I didn't mean you should do it. Just that you might find the idea interesting ;)

**Comment by novemberborn** [comment]
I'd be happy to take this on. I've used watchers extensively when building dev stacks.

**Comment by tomazzaman** [comment]
@novemberborn @sindresorhus I've created a PR #465 , just a basic watcher for now, but works. I'd be more than happy to hear your feedback to learn whether I'm on the right track

**Comment by sindresorhus** [comment]
This needs to be taken into account: https://github.com/babel/babel/pull/3307
