### ISSUE TITLE
flag/config for not ignoring node_modules

### ISSUE THREAD

**Issue by scottnath** [sindresorhus/ava#711]
## Description

Hi Ava team...I have some tests which are common to a lot of separate node modules I'm building. I would like to put those tests with some other utilities for said node modules in a common utilities node module (which has other stand-alone functionality as well.)
I see that last November a change was implemented to always ignore the `node_modules` directory. [issue #226 / pull request #260).

q: Would the Ava team be open to the addition of a flag/config setting which would allow triggering tests from within the node_modules directory?
-or-
q: Is there a workaround already available to allow triggering tests from within the node_modules directory?

thank you,
Scott

**Comment by jamestalmage** [comment]
@scottnath - Scanning `node_modules` has all sorts of nasty implications, and it's really not where you want to be storing your tests (you shouldn't be packaging your tests when you deploy anyways).

Now, If you really have some test helper functionality that you want to reuse across modules, that's great. Just make them a utility you can require.

You could do something like this:

```js
import test from 'ava';
import commonTests from 'my-common-tests';
import moduleUnderTest from '../';

commonTests(test, moduleUnderTest);
```

`my-common-tests.index`:

```js
module.exports = function (test, moduleUnderTest) {
  test('it does this thing', function (t) {
     t.ok(...);
  });

  test('it does this other thing', function (t) {
     t.ok(...);
  });

  // ...
};
```

**Comment by scottnath** [comment]
@jamestalmage that is excellent! Exactly the brain jog I needed. Closing this ticket...thank you for your help.
