### ISSUE TITLE
Add better error message when `--require` fails

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/ava#712]
If (for example) you misspell the filename for the `--require` option, the error message you get isn't very helpful:

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: missing path
    at Module.require (module.js:351:3)
    at require (internal/module.js:12:17)
    at Array.forEach (native)
...
```

I'll bet we could do something to first check whether the file being `--require`ed exists, and throw a helpful error if it does not. Thoughts? :thought_balloon:

**Comment by jamestalmage** [comment]
How about this: https://github.com/sindresorhus/ava/commit/c78e7367d07ea1a27158a35972184de266d04230

:stuck_out_tongue_winking_eye:

**Comment by kentcdodds** [comment]
Lol! I promised I searched issues first! Thanks! :-D
