### ISSUE TITLE
Add stdev to benchmark results

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#724]
Reference: https://twitter.com/trevnorris/status/712355178939199488

https://www.mathsisfun.com/data/standard-deviation-formulas.html

**Comment by 7373Lacym** [comment]
I would like to give this a shot.

**Comment by sindresorhus** [comment]
@7373Lacym Go ahead :)

Let us know if you have any questions. We're also in https://gitter.im/sindresorhus/ava

**Comment by sotojuan** [comment]
Fixed by #744.
