### ISSUE TITLE
throws assertion does not work with await/async

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#73]
When using `await`/`async`, the throws() assertion doesn't work.

```js
test('throws error', async t => {
    t.throws(await fn(), Error);
});
```

**Comment by vdemedes** [comment]
`throws()` expects a function you are executing to throw. This will not work here, because `async/await` is converted to generator functions, thanks to `asyncToGenerator` babel transform. So, your example is transformed to this:

```js
test('throws error', function * (t) {
  t.throws(yield fn(), Error);
});
```

For `t.throws()` to catch your error, it needs to check if promise rejects and that's not supported at the moment.

**Comment by sindresorhus** [comment]
> For t.throws() to catch your error, it needs to check if promise rejects and that's not supported at the moment.

Could be useful though. Let's leave this as a feature request?

**Comment by SamVerschueren** [comment]
It would make testing for an error really nice and clean.

**Comment by vdemedes** [comment]
@sindresorhus Yep, let's!

**Comment by silvenon** [comment]
I tried the provided solution, but it doesn't work for me:

```js
test(function * (t) {
  t.throws(yield Promise.reject(new Error()), Error);
});
```

It doesn't output the test. Am I doing something wrong?

**Comment by floatdrop** [comment]
@SamVerschueren why not try-catch?

```js
test('throws error', async t => {
    try { await fn(); } catch (err) { /* ... */ }
});
```

**Comment by silvenon** [comment]
@floatdrop that works, thanks :+1:

**Comment by SamVerschueren** [comment]
@floatdrop Yes I know that's possible, and I already do that at the moment. But I think it would be a very nice addition that the `throws` assertion method can handle rejected promises. This would make some tests methods a lot cleaner.

```js
test('throws error', async t => {
    t.throws(await fn(), Error);
});

test('throws error 2', async t => {
    try {
        await fn();
        t.fail();
    } catch (err) {
        t.ok(err);
    }
});
```

**Comment by sindresorhus** [comment]
In `got`, we have to [repeat `t.fail('Exception is not thrown');`](https://github.com/sindresorhus/got/commit/f7500d474e4f54003682c998d81a3aa9ce61612c#diff-bbc23533bfd4986af19324ccf2e7c4baR27) in a lot of tests, which is pretty sub-optimal.

**Comment by sindresorhus** [comment]
Anyone wanna try implementing this?

**Comment by vdemedes** [comment]
Submitting a PR in a minute ;)

**Comment by f0rr0** [comment]
When using `try/catch` with `async/await` like:
```js
test('some test', async t => {
  try {
    await someFn();
  } catch (err) {
    t.pass();
  }
});
```
`someFn` always rejects and although the test passes, I get ` 1 unhandled rejection` in the console. Is this expected?
