### ISSUE TITLE
Babel for helper files

### ISSUE THREAD

**Issue by calebmer** [sindresorhus/ava#738]
Currently `ava` does not use babel with helper files, is there a way to change this functionality? I have a file named `helpers/index.js` which I import from my ES6 tests which `ava` automatically compiles with Babel. When I try using `import … from …` syntax in my helper files it fails.

Is it possible for `ava` to run helper files using Babel either now or in the future?

## Environment

```
ava 0.13.0
Node.js 5.0.0
darwin 15.2.0
```

**Comment by jamestalmage** [comment]
Not without using `babel-register`. This is definitely on the list of future enhancements though.

If you really need it now check out the Babel config recipes in the docs, and use `--require babel-register`

**Comment by novemberborn** [comment]
> This is definitely on the list of future enhancements though.

See #720.
