### ISSUE TITLE
`.ifError()` name is misleading

### ISSUE THREAD

**Issue by alebelcor** [sindresorhus/ava#74]
I would expect `.ifError(err)` to check that the passed-in argument is, in fact, an error.

Instead what it does is check if `err` is falsy.

How is this different than doing `.notOk(err)`?
Should it be instead renamed to `.ifNotError(err)`?
Or better yet, change it to check if the argument is an error.

Thoughts?
Thank you!

**Comment by sindresorhus** [comment]
This is just inherited from the Node.js [`assert` module](https://nodejs.org/api/assert.html#assert_assert_iferror_value).
Can you bring this up on the Node.js [issue tracker](https://github.com/nodejs/node/issues) first?

-

That assert method is pretty irrelvant with promises though.

**Comment by alebelcor** [comment]
I see, but looking at the `assert` documentation it states that `ifError` "throws value if value is truthy"

If I got that right I think AVA's `ifError` is inverted. It throws the value if it's falsy.

**Comment by Qix-** [comment]
Can you write a quick test case @alebelcor?

**Comment by floatdrop** [comment]
@Qix- ava have [test case](https://github.com/sindresorhus/ava/blob/master/test/assert.js#L201) for this.

@alebelcor judging by test case `ifError` behaves correctly (throws, if `value` is truthy - [double](https://github.com/sindresorhus/ava/blob/master/lib/assert.js#L92) [negative](https://github.com/sindresorhus/ava/blob/master/lib/assert.js#L18) is always tough, thou).

**Comment by alebelcor** [comment]
OK, then (unless I'm mistaken) this just means that the `readme.md` is inaccurate.

`.ifError(error, [message])` asserts that error is falsy.

**Comment by floatdrop** [comment]
Well, no.

> Asserts that error is truthy.

It [asserts](http://dictionary.reference.com/browse/assert) that error is falsy. It throws if error is truthy.

**Comment by sindresorhus** [comment]
@alebelcor If you have any good suggestions for a better name we might consider adding an alias, but I don't really care much tbh, as the future is promises and async functions which makes this assert method moot.

**Comment by sindresorhus** [comment]
Related: https://github.com/nodejs/node/issues/3398
