### ISSUE TITLE
Throwing in callback-test is not reported and causes test to never end

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#748]
```js
import test from 'ava';

test.cb(t => {
	throw new Error('unicorn');
	t.pass();
	t.end();
});
```

Reproduced with AVA 0.14.0 and latest [master](https://github.com/sindresorhus/ava/commit/3201b1b4ff80ff75f0e1c288ca7da22f92c9b814) with all reporters.

**Comment by cwhenderson20** [comment]
I was going to comment on a similar issue, but I found this issue, exactly matching my problem. I'll leave the comment anyway in case it it helps anyone else looking for a solution:

---

My tests are all asynchronous (using the `test.cb` style) and it seems to be that in these tests, thrown errors cause the test to hang indefinitely.

Here's some example code:

This works, as an error is returned (as expected): 

```js
test.cb("does not allow extending message visibility past 12 hours", (t) => {
  const sqs = new SQS({ params: { QueueUrl, ReceiptHandle: "fake", VisibilityTimeout: 43201 }});

  sqs.changeMessageVisibility((err) => {
    t.truthy(err);
    t.is(err.code, new InvalidParameterValueError().code);
    t.end();
  });
});
```

This, however, causes the suite to hang:

```js
test.cb("extends a message's visibility and returns an empty object", (t) => {
  const sqs = new SQS({ params: { QueueUrl, ReceiptHandle: "fake", VisibilityTimeout: 43201 } });

  sqs.changeMessageVisibility((err, data) => {
    t.falsy(err);
    t.is(Object.keys(data).length, 0);
    t.end();
  });
});
```

I believe the reason for this is that, in the second example, `data` is `undefined`, which causes the `Object.keys(data)` method to throw a `TypeError`. Clearly this is a contrived example as I know that an error will be returned and am asserting that it should not exist, but it left me confused for a while as 1) AVA doesn't report that an error was thrown (even in verbose mode), and 2) the only way to get the suite to run again (if in watch mode) is to kill and restart the process.

**Comment by shinzui** [comment]
I am still experiencing this behavior with ava 0.18.1

**Comment by sindresorhus** [comment]
@shinzui I doubt it's the exact same issue as we have unit tests proving it's working. Go ask in our https://gitter.im/avajs/ava and share some code ;)
