### ISSUE TITLE
`t.plan` not working in async functions

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ava#75]
`t.plan` isn't working when using `async`/`await`.

```js
test('generate screenshots', async t => {
    t.plan(2);

    const streams = await new Pageres()
        .src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'])
        .src('todomvc.com', ['1280x1024', '1920x1080'])
        .run();

    t.is(streams.length, 5);
    streams[0].once('data', data => t.true(data.length > 1000));
});
```

This will throw an error `Assertion count does not match planned`. When using `t.plan(1)` it works correctly but off course doesn't test the length of the data.

This was pointed out here https://github.com/sindresorhus/pageres/issues/213#issuecomment-147634374.

**Comment by vdemedes** [comment]
I think it's worth explaining why it does not work. When using promises in AVA, it is advertised that `t.plan()` is not needed, because test finishes when promise resolves/rejects. So that's exactly what happens here, async functions are converted into promises by babel. So when a promise resolves, the test is done here and it does not wait for `data` event.

**Comment by mralexgray** [comment]
Here's a another simple example of `t.plan()`'s epic fail, along with the working snippet from the `README`...

```
test 'bar', (t) ->
	t.plan 2
	setTimeout ->
		t.is 'bar', 'bar'
		t.same ['a', 'b'], ['a', 'b']
	, 100

test 'simple async', (t) ->
	t.plan 1
	setTimeout ->
		async.start
			success: ->
				t.pass()
  		fail: (err) ->
				console.log "errrored #{err}"
	, 500

 ✖ simple async Assertion count does not match planned
 ✔ bar (107ms)
```

Any chance this will be fixed anytime soon?   Seems like a pretty basic/necessary part of any "asynchronous" testing framework, no?

Can I help?  How?

**Comment by sindresorhus** [comment]
@mralexgray This is completely irrelevant to the issue, which is concerning ES2016 `async` functions, not async in general. Please don't use unproductive words like "epic fail". We have a [passing test](https://github.com/sindresorhus/ava/blob/1d9ea46236e06bb1542d4438dc2b450cf6084fe6/test/test.js#L224-L235) for `t.plan` with an async assertion. It, however, seems like your `success` function is never called. Happy to be proven wrong with a failing test, though.

**Comment by mralexgray** [comment]
Huh, you're right.

In my original code (which I swear I had tried before posting)...
```coffee
test 'async', (t) ->
  t.plan 1 
  setTimeout ->
    async.start
      success: ->
        t.pass()
      fail: (err) ->
        t.fail()
  , 500
````

Maybe I had mistakenly put `t.plan 2` ... or also had a `t.end()` in one of my callbacks?  Regardless, it's working now!  Sorry for the tongue-in-cheek dramatics.  Was just being cheeky 😇

**Comment by mralexgray** [comment]
@sindresorhus BTW, in your example of the passing test, are you using 'bluebird' promises?  If so, it may be worth mentioning in the `README`'s "promises" section that that is what YOU guys are using, and is an option for test-writers, as well. :-)

**Comment by sindresorhus** [comment]
We're using Bluebird, yes, but that's an implementation that shouldn't be dependent upon.
