### ISSUE TITLE
Document which patterns are excluded

### ISSUE THREAD

**Issue by marvinhagemeister** [sindresorhus/ava#750]
At work we have one project where some test files were placed inside a `helpers` folder. It took me way too long to figure out that ava ignores some folders by default (my first guess was directory permissions).

Although the testfile is explicitly given as an argument, ava exits with the following error:

```bash
$ ava helpers/mytest.js

Couldn't find any files to test
```

**Comment by jfmengels** [comment]
Under https://github.com/sindresorhus/ava#cli, you already have this documented.
`Directories are recursed, with all *.js files being treated as test files. Directories named fixtures, helpers and node_modules are always ignored. So are files starting with _ which allows you to place helpers in the same directory as your test files.`

**Comment by marvinhagemeister** [comment]
Thanks, don't know how I could've missed that!

**Comment by ulfryk** [comment]
So how to tests files that are in `helpers` directory ? Is there possibility to suppress this ignore ?

**Comment by grvcoelho** [comment]
As @ulfryk, pointed: is there a way to supress this ignore? I need to test files inside a `helpers` folder.

**Comment by novemberborn** [comment]
@grvcoelho not at this moment. We have open issues around this, e.g. #909.
