### ISSUE TITLE
Add options to choose the output format

### ISSUE THREAD

**Issue by Spy-Seth** [sindresorhus/ava#751]
AVA automaticly try to detect the output capabalities to choose the right output formater. 

But sometimes it failed to choose the good one. For example here on one of my travis build:

<img width="916" alt="screenshot 2016-04-12 09 17 29" src="https://cloud.githubusercontent.com/assets/95120/14464345/c0c71e7a-00ce-11e6-813f-e37e2020fa0d.png">

Could you had options to choose the formater?

**Comment by sindresorhus** [comment]
What command did you use to run AVA?

Instead of adding an option we'll just fix the auto-detection.

**Comment by Spy-Seth** [comment]
My command to run the test is simple: `NODE_ENV='test' ava --require babel-register --require babel-polyfill --require ./tests/helpers/world.js tests/units/**/*`

The difficulties is that I execute is in a docker container: `docker exec -it test-runner npm test`

**Comment by novemberborn** [comment]
@Spy-Seth AVA checks environment variables to auto-detect your CI. You'll have to forward it to your docker container:

```
docker exec -it -e CI test-runner npm test
```

(Like 80% sure on the `-e` shorthand)

Alternatively you can force verbose output:

```
docker exec -it -test-runner 'npm test -- --verbose'
```

**Comment by Spy-Seth** [comment]
Adding `-e CI=true` works. 

Thanks for your help !

**Comment by novemberborn** [comment]
@Spy-Seth no worries. It's something that should be documented (#404).
