### ISSUE TITLE
t.truthy() does not seem to work correctly

### ISSUE THREAD

**Issue by omnidan** [sindresorhus/ava#752]
## Description

I have the following code for testing a response (with supertest):

```js
      t.truthy(res.user)
      t.is(res.user.email, 'test@user.com')
```

I checked and `res.user` seems to be `undefined`, but ava still continues on testing the next assertion, which throws an exception because `res.user.email` doesn't work if `res.user` is not defined:

```
TypeError: Cannot read property 'email' of undefined
```

Any idea why `t.truthy` does not seem to be working correctly (`undefined` is not truthy)?

## Environment

```
Node.js v5.7.0
darwin 15.3.0
ava 0.14.0
```

**Comment by jamestalmage** [comment]
Throwing a `TypeError` is expected (our assertions are modeled after `nod-tap`s, and don't throw).

However, the failure message should print the result of the first failed assertion it sees.

I just tested the following:

```js
import test from 'ava';

test(t => {
	t.truthy({}.undef);
	t.undef.uhoh;
});
```

And I got the expected result (both `0.14.0`, and `master`):

```
 ./cli.js test/fixture/sync-throw.js

   1 failed

  1. [anonymous]
    
  t.truthy({}.undef)
              |     
              null  
  
      Test.fn (synch-throw.js:4:4)
```

**Comment by omnidan** [comment]
I just checked again, this is the full code:

```js
test.cb('/register with valid POST data should create and login user', t => {
  supertest
    .post('/register')
    .field('email', 'test@user2.com')
    .field('password', 'test123') // not a good password ;)
    .expect(200)
    .end((err, res) => {
      console.log(res.body) // { error: 'Registration failed' }
      console.log(res.body.user) // undefined
      t.truthy(res.body.user, 'this should be the error message')
      t.is(res.body.user.email, 'test@user.com')
    })
})
```

But this results in:

```
  1. Uncaught Exception
  TypeError: Cannot read property 'email' of undefined
```

I also tried running your code (also in the `end` handler/callback function):

```
  1. Uncaught Exception
  TypeError: Cannot read property 'uhoh' of undefined
```

Seems to be an issue related to `test.cb` or `supertest`, then.

**Comment by omnidan** [comment]
I also tried with 0.13 (and `ok`/`notOk`) and it causes the same issue.

Although it does seem to fail at the first assertion when I make sure an exception isn't thrown later, e.g. by doing `t.is(res.body.user && res.body.user.email, 'test@user.com')`:

```
  t.falsy(res.body.error)
                   |
                   "Registration failed: "
```

**Comment by novemberborn** [comment]
@omnidan IIRC assertion failures don't throw within the test body, AVA just reports the first failure after the test has finished. This works as expected:

```js
test('sync', t => {
  const obj = {}
  t.truthy(obj.undef)
  t.is(obj.undef.nope, 'whah?!')
})
```

Doing the same with `test.cb` causes the test to hang, that seems like a bug:

```js
test.cb('async', t => {
  const obj = {}
  t.truthy(obj.undef)
  t.is(obj.undef.nope, 'whah?!')
  t.end()
})
```

However your test doesn't hang, it results in an uncaught exception. I suspect `supertest` is rethrowing any exceptions from its `.end()` callback in a new turn. This causes the uncaught exception, which fails your entire test file and masks the previous assertion failure.

Try wrapping `supertest` in a promise, like this:

```js
test('/register with valid POST data should create and login user', async t => {
  const res = await new Promise((resolve, reject) => {
    supertest
      .post('/register')
      .field('email', 'test@user2.com')
      .field('password', 'test123') // not a good password ;)
      .expect(200)
      .end((err, res) => err ? reject(err) : resolve(res))
  })
  t.falsy(res.body.error) // shouldn't this fail already???
  console.log(res.body) // { error: 'Registration failed' }
  console.log(res.body.user) // undefined
  t.truthy(res.body.user, 'this should be the error message')
  t.is(res.body.user.email, 'test@user.com')
})
```

This stops supertest from rethrowing any errors, and works around what looks like a `.cb` bug.

**Comment by omnidan** [comment]
@novemberborn thanks for the workaround, I only have ES6 features enabled (no `async/await`), so I tried the following:

```js
test('/register with valid POST data should create and login user', t => {
  (new Promise((resolve, reject) => {
    supertest
      .post('/register')
      .field('email', 'test@user2.com')
      .field('password', 'test123') // not a good password ;)
      .expect(200)
      .end((err, res) => err ? reject(err) : resolve(res))
  })).then(res => {
    t.falsy(res.body.error) // shouldn't this fail already???
    console.log(res.body) // { error: 'Registration failed' }
    console.log(res.body.user) // undefined
    t.truthy(res.body.user, 'this should be the error message')
    t.is(res.body.user.email, 'test@user.com')
  })
})
```

It results in:

```
  2. Unhandled Rejection
  TypeError: Cannot read property 'email' of undefined
```

I'll just wait until `test.cb` gets fixed as I already got the test to pass anyway :grin:

**Comment by novemberborn** [comment]
@omnidan if you return the promise it'll work correctly.

**Comment by novemberborn** [comment]
Looks like the callback bug was already tracked in #748. Will close this now.
