### ISSUE TITLE
Does it make sense to add support for harmony flags?

### ISSUE THREAD

**Issue by bencooling** [sindresorhus/ava#753]
For example I want destructuring in my source code, which should be supported natively in a few weeks with the release of Node v6 so transpiring my source with Babel is more inconvenient than simply running `node --harmony_destructuring` 

My hack/workaround at the moment is to edit the first line of the `node_modules/ava/cli.js`:
```
#!/usr/bin/env node --harmony_destructuring
```

**Comment by sindresorhus** [comment]
I guess we could pass all flags after a [double-dash](http://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash) to `node`, like `$ ava -- --harmony_destructuring`.

**Comment by novemberborn** [comment]
This should also work, and is more explicit: `node --harmony_destructuring node_modules/.bin/ava`.

**Comment by vdemedes** [comment]
What happens with the following set up in that case?

package.json:

```js
{
  "scripts": {
    "test": "ava -- --harmony_destructuring"
}
```

terminal:

```
$ npm test -- specific-test.js
```

**Comment by novemberborn** [comment]
@vdemedes I'm pretty sure the argument would go to `node`, not AVA.

**Comment by vdemedes** [comment]
That's not something we want though. Although this case should not occur often, so we might just roll with it.

**Comment by novemberborn** [comment]
I'd prefer users do `node --harmony_destructuring node_modules/.bin/ava`.

**Comment by LinusU** [comment]
@bencooling Wont ava still transpile using babel though?

Also, Node.js 6 will be released on the 26th and then there won't be a need to run node with flags anymore...

**Comment by sindresorhus** [comment]
> Also, Node.js 6 will be released on the 26th and then there won't be a need to run node with flags anymore...

No. There will always be new features behind flags.

**Comment by bencooling** [comment]
@LinusU I believe Ava runs your tests through Babel not your source code.

**Comment by LinusU** [comment]
I'm quite sure that all code (except node_modules) is run thru babel

**Comment by novemberborn** [comment]
@LinusU by default only test files are run through Babel.

**Comment by LinusU** [comment]
I stand corrected, sorry about that

**Comment by jamestalmage** [comment]
I agree with @novemberborn 

```
node --harmony-flag node_modules/.bin/ava
```

Node already provides a working solution, no reason to create our own.

Closing. If someone feels that's premature, feel free to reopen.

**Comment by zhaoyao91** [comment]
`node --harmony node_modules/.bin/ava` does not work on windows 10

**Comment by seangenabe** [comment]
Try `node --harmony node_modules/ava/cli.js` -- the contents of the .bin directory are shell scripts and shouldn't be runnable by node.
