### ISSUE TITLE
Deprecate hooks at top level

### ISSUE THREAD

**Issue by sheerun** [sindresorhus/ava#762]
Hooks at top level don't feel right.. I suggest to deprecate them and require to create groups.

```js
test.group('something', test => {
  test.beforeEach(t => {
    t.context = 'foo'
  });

  test('is awesome', t => {
    t.is(t.context, 'awesome');
  });

  test('is not fabulous', t => {
    t.not(t.context, 'fabulous');
  });
});
```

Now you can concatenate two test files without concatenating their hooks, and you can create multiple test groups with different hooks per file. This also solves #222 and allows for bdd-like testing.

**Comment by sheerun** [comment]
Another approach is to make 1-level grouping obligatory:

```js
ava('optional group name', test => {
  test.beforeEach(t => {
    t.context = 'foo'
  });

  test('is awesome', t => {
    t.is(t.context, 'awesome');
  });

  test('is not fabulous', t => {
    t.not(t.context, 'fabulous');
  });
});
```

**Comment by sindresorhus** [comment]
> Hooks at top level don't feel right..

Why?

**Comment by sheerun** [comment]
Because you invoke them on global `test` object instead of group of test they should modify.

It's the sae issue you tried to get rid of with ava:

> Mocha requires you to use implicit globals like `describe` and `it` with the default interface

The same way you need to use `t.is` for test, you should use `test.beforeEach` where `test` is a group.

**Comment by novemberborn** [comment]
Because each test file is executed in its own process the hooks implicitly cover the group of tests in the file. We're tracking support for test groups in #222.

Also, the top-level `t.before()` is nice when your setup code is asynchronous. For simple/synchronous test setup you don't even need to use a hook.

**Comment by sheerun** [comment]
I get it, but my point still holds. Plus I like to write all my tests in one file and only after that extract them to another one. With implicit hooks it's impossible to apply hooks only to *some* tests in one file.

**Comment by novemberborn** [comment]
Sure. Sounds like you want group support. Please subscribe to #222 for updates regarding that.

I'll close this now.
