### ISSUE TITLE
mini-reporter: align numbers in summary and error output: 

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#780]
This looks a little goofy to me:

<img width="276" alt="screenshot 2016-04-24 02 41 15 copy" src="https://cloud.githubusercontent.com/assets/4082216/14765950/777ce7ee-09c6-11e6-9de9-e76bc290b21d.png">

Should they be aligned?

**Comment by sindresorhus** [comment]
Yes. I've noticed this too. Just hadn't gotten around to reporting it yet.

**Comment by sotojuan** [comment]
Hm this seems to be working for me in latest master already, can someone confirm?

**Comment by stefanlegg** [comment]
Looks to be aligned correctly in master, but not in the 0.14.0 release

**Comment by novemberborn** [comment]
Yea I made changes here in #737 which landed after 0.14.0 was cut.
