### ISSUE TITLE
NODE_ENV not used for babel when inherit is set

### ISSUE THREAD

**Issue by calebmer** [sindresorhus/ava#783]
## Description

I want to use JSX in my tests so I set the ava configuration to use my `.babelrc` config. I'm also using webpack 2 so the preset I'm using is `babel-preset-es2015-native-modules`. Because ava needs ES modules transpiled into CommonJS, I conditionally include the `babel-plugin-transform-es2015-modules-commonjs` plugin depending on the environment (`test` in this case).

It appears that ava is not using the `NODE_ENV` or `BABEL_ENV` environment variables when transpiling test files.

Here is my `.babelrc`:

```json
{
  "presets": ["es2015-native-modules", "stage-1"],
  "plugins": [
    "syntax-jsx",
    "transform-react-jsx"
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    }
  }
}
```

And I'm running ava like so:

```bash
$ NODE_ENV=test ava
```

## Environment

```
Node.js v5.0.0
darwin 15.2.0
```

**Comment by jamestalmage** [comment]
What does the `ava` section of your `package.json` look like.

**Comment by calebmer** [comment]
`{ "babel": "inherit" }

**Comment by jamestalmage** [comment]
> It appears that ava is not using the NODE_ENV or BABEL_ENV environment variables when transpiling test files.

How are you coming to that conclusion?

Is `transform-es2015-modules-commonjs` supposed to override

**Comment by novemberborn** [comment]
@calebmer Would be great if you could post a sample project with your setup, including how you configure the environment variables when running tests.

**Comment by calebmer** [comment]
@novemberborn this, combined with a couple of other factors (including interop with webpack/webpack loaders and install size) led me to use another test runner so I don't have a sample project anymore 😐

I'd really like to see the story for React/Webpack improve in the future.
