### ISSUE TITLE
Use Babels Compact Mode

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#790]
See babel/babel#3475.

Should we set {compact: true; comments: false} in our Babel usage? 

Seems it could improve the speed a bit.

**Comment by sotojuan** [comment]
Just tried this out and tests pass—is there a way to measure performance?

**Comment by jfmengels** [comment]
I'll take a stab at it :)

**Comment by jamestalmage** [comment]
@jfmengels is assigned!

**Comment by sotojuan** [comment]
Are we good to close based on the PR results?

**Comment by sindresorhus** [comment]
Yup
