### ISSUE TITLE
v8 depreciation warning using the watch flag with Node v6.0.0

### ISSUE THREAD

**Issue by bencooling** [sindresorhus/ava#793]
Using the watch flag on Node v6.0.0 displays warnings and a stack trace in the terminal

```
node node_modules/.bin/ava --verbose --watch

(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x1e3d5b4c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x328d7de52204] (this=0x20bb46efb931 <an Object with map 0x24ef30617be1>#1#,module=0x3dbe390f2a99 <a Module with map 0x24ef306181b9>#2#,filename=0x3dbe390f2a61 <String[129]
...
```

**Comment by sindresorhus** [comment]
See: https://github.com/strongloop/fsevents/pull/128

We're using `chokidar` for file watching, which uses the native dependency `fsevents` for more consistent behavior and better performance.

**Comment by jamestalmage** [comment]
strongloop/fsevents#128 is merged and released as a patch release.

I'm closing. Users still experiencing this should `rm -rf node_modules && npm install`
