### ISSUE TITLE
Test with assertion involving "complex" object hangs

### ISSUE THREAD

**Issue by nfcampos** [sindresorhus/ava#799]
## Description

The following test hangs.
```js
import test from 'ava'

import server from './server' // it's a hapi server

test('a test', t => {
  return server.inject({
    url: '/blah'
  }).then(reply => {
    // t.is(reply.statusCode, 200) // this one doesn't hang because it passes
    t.is(reply.statusCode, 201) // this one hangs because it fails
    // const statusCode = reply.statusCode
    // t.is(statusCode, 201) // this one doesn't hang (because power-assert doesn't have to process `reply`?)
  })
})
```
clone https://github.com/nfcampos/ava-hapi-issue to reproduce the issue

my guess is it hangs because `power-assert` can't process the `reply` object.

## Environment
```
Node.js v5.9.0
darwin 15.5.0
```

**Comment by jamestalmage** [comment]
> my guess is it hangs because power-assert can't process the reply object.

Yes, you are almost certainly correct. This is a known, issue and we are tracking it in #703.

**Comment by nfcampos** [comment]
oops sorry for the duplicate issue. Is there any workaround for now, other than destructuring?

**Comment by jamestalmage** [comment]
No worries!

Unfortunately, destructuring is the only way for now.

**Comment by jsonmaur** [comment]
I also came across this, and found a workaround by simply putting in `delete reply.request` in the resolved promise. I narrowed it down, the problems seem to be coming from `reply.request.route` and `reply.request.response` from the Hapi response. Hoping to see a fix soon :)
