### ISSUE TITLE
Report on unhandled promises

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#80]
Promises are silent by default and it's easy to forget handling a promise somewhere down the chain or forget to return the promise in the test. Using [`loud-rejection`](https://github.com/sindresorhus/loud-rejection), we can throw in those cases so the user know they did something wrong.

Need to wait on https://github.com/sindresorhus/loud-rejection/issues/1.

-

Note to self: Document this in the readme too.

**Comment by LinusU** [comment]
You are actually already using this, which funnily enough breaks the tests that I'm trying to write for loud-rejection :laughing: 

Ava is built with `meow` which includes loud-rejection.

Man was it annoying to track down as well,

```javascript
const org = process.on;
process.on = function () {
	console.trace(arguments);
	org.apply(this, arguments);
}

const fn = require('./');
const test = require('ava');
fn();

function fire() {
	return new Promise(function (resolve, reject) {
		setImmediate(function () {
			const org = console.error
			console.error = function () {
				console.error = org
				console.trace(arguments) // <------ Finally manage to find it with this
			}
			reject(new Error('unicorn'));
		});
	});
}
```

**Comment by LinusU** [comment]
Another fun fact, calling `console.trace` recursively will run out of memory before hitting max recursion. Found this out the hard way...

```text
<--- Last few GCs --->

    5200 ms: Mark-sweep 1391.4 (1505.2) -> 1172.0 (1220.2) MB, 35.6 / 0 ms [allocation failure] [GC in old space requested].
    5218 ms: Mark-sweep 1172.0 (1220.2) -> 1172.0 (1212.2) MB, 18.1 / 0 ms [allocation failure] [GC in old space requested].
    5238 ms: Mark-sweep 1172.0 (1212.2) -> 1171.7 (1211.2) MB, 19.8 / 0 ms [last resort gc].
    5252 ms: Mark-sweep 1171.7 (1211.2) -> 1171.7 (1211.2) MB, 13.7 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3ec84df37399 <JS Object>
    1: replace(aka replace) [native string.js:~146] [pc=0x230e9b6af485] (this=0x23a9be604101 <Very long string[151036881]>,N=0x3ec84dfb84b1 <JS RegExp>,O=0x3b956bc4e539 <String[2]: \'>)
    2: 0x53c78d8eaf9 <Symbol: 224142380 <String[14]: Symbol.replace>> [/Users/linus/coding/loud-rejection/node_modules/ava/node_modules/babel-core/node_modules/core-js/modules/$.fix-re-wks.js:~15] [pc=0x230e9ae9...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    6026 abort      node_modules/.bin/ava
```

**Comment by sindresorhus** [comment]
Oh, damn... Although, in the next version of AVA we're spawing each test file in it's own process, so we'll have to explicitly include it then. Try using AVA master as dependency for now. Example: https://github.com/sindresorhus/got/blob/f4cf6c7b44d047d505ed1fdf3a4e361b743bdfc2/package.json#L64

**Comment by LinusU** [comment]
Hmm, for some reason using master stopped my `process.on('exit', ...)` handler from ever firing... Any idea why?

**Comment by LinusU** [comment]
Also, I can't get `rejectionHandled` to fire :( tearing my hair out...

**Comment by sindresorhus** [comment]
@LinusU Maybe just use [`tape`](https://github.com/substack/tape) for testing that module then.

**Comment by LinusU** [comment]
I think I got everything working, except for the `rejectionHandled`... Let's continue the discussion in that repo

**Comment by jamestalmage** [comment]
Closed via: https://github.com/sindresorhus/ava/commit/c5d02f1f3c8ba7dabbdb53fdc9710f0cd117a9d3
