### ISSUE TITLE
after won't run when uncaught exception thrown

### ISSUE THREAD

**Issue by cgcgbcbc** [sindresorhus/ava#805]
## Description

```
import test from 'ava';

test.after(t => {
  console.log('after');
});

test(t => {
  throw 'error';
});

```
after hook won't execute in this situation, if database need to be clean in after hook, then it will not be cleaned and future test will fail due to unclean database.

## Environment

node version v5.5.0, gulp-ava version 0.11.0, ava version latest

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/ava/issues/474
