### ISSUE TITLE
Performance: --require

### ISSUE THREAD

**Issue by vjancik** [sindresorhus/ava#808]
Does preloading a module using `--require` improve the startup speed of the tests? E.g. does the loaded instance get distributed to the workers?

If not, what good is it, other than `babel-register`?

**Comment by spudly** [comment]
Unfortunately, using `--require` actually slows it down, because it get's required in each fork (not in the main process). In my experience, requiring `--babel-register` actually makes it twice as slow.

**Comment by forresst** [comment]
See [Recipe babelrc, section Transpiling Sources](https://github.com/sindresorhus/ava/blob/master/docs/recipes/babelrc.md#transpiling-sources) :

>Note that loading babel-register in every forked process has a non-trivial performance cost. If you have lots of test files, you may want to consider using a build step to transpile your sources before running your tests. This isn't ideal, since it complicates using AVA's watch mode, so we recommend using babel-register until the performance penalty becomes too great. Setting up a precompilation step is out of scope for this document, but we recommend you check out one of the many build systems that support Babel. There is an open issue discussing ways we could make this experience better.

**Comment by jamestalmage** [comment]
> If not, what good is it, other than `babel-register`

It could be used for other things besides `babel-register`. 

Registering, your desired Observable implementation via [`any-observable`](https://github.com/sindresorhus/any-observable#registration-shortcuts) for instance.

It has nothing to do with performance (though using it can have performance side effects, as @spudly mentioned). Use `npm@3` to minimize those, and know we are working on ways to improve the performance.
