### ISSUE TITLE
Performance: tests take extra 20 seconds on test file change.

### ISSUE THREAD

**Issue by vjancik** [sindresorhus/ava#809]
## Description

My tests take roughly 5 seconds. But on some runs through Ava (at random) they take extra 20 seconds. After my code gets loaded and initialized, but before the tests start running.

Anybody else experience this?

## Environment

```
Node.js v4.4.3
darwin 15.4.0
```

**Comment by sindresorhus** [comment]
I've not experienced this personally. You say "at random", but approximately how often? Can you try `npm cache clean && rm -rf node_modules && npm install && npm test`? Babel just released a new version which improves require performance considerably. Could you also try to see if you can reproduce with Node.js 6? That would help us track it down. Thanks :)

**Comment by vjancik** [comment]
It seems the extra 20 seconds happen when I change the contents of the test files. So I suspect the culprit is Babel. Is it possible it's transpiling something it shouldn't? What `.babelrc` do you normally use with Ava?

**Comment by sindresorhus** [comment]
Yeah, most of our perf problems are Babel related. Ok, changing the test invalidates the cache for that file, but it should never take this long to recompile. Does indeed sound like it's trying to transpile the whole `node_modules` directory by mistake or something. Would you be able to share a demo repo with the issue? If not at least the AVA and Babel (if there) config in package.json?

**Comment by vjancik** [comment]
Well, I have a single test file with a single async test function. Atop of that, I'm requiring 2 helper function code files written in ES5.

In `package.json` I have just this:
```
"ava": {
    "serial": true,
    "files": [
      "test/**/*.test.js"
    ]
  },
```

**Comment by vjancik** [comment]
Well, it seems `rm -rf node_modules; npm install` helped ... Not sure what was the problem but it's gone. Thank you for your help!
