### ISSUE TITLE
Observable that does not complete is not unsubscribed on failure

### ISSUE THREAD

**Issue by calebmer** [sindresorhus/ava#818]
## Description

I have a test with an observable that never emits a value (admittedly that's a bug in my program I'm trying to catch) so I added a timeout to fail the test if the observable didn’t complete in a certain time. Here’s some example code:

```js
import test from 'ava'
import { Observable } from 'rxjs'

test('observable that never completes', t => {
  setTimeout(() => t.fail('Test timed out'), 1000)
  return Observable.never()
})
```

`ava` reports the error from `t.fail`, but the process doesn’t end. This is bad for CI because the test build will not finish.

## Environment

```
Node.js v5.0.0
darwin 15.2.0
```

**Comment by novemberborn** [comment]
@calebmer you should use the [`--timeout`](https://github.com/sindresorhus/ava#global-timeout) option to make AVA exit if a timeout is reached.

**Comment by calebmer** [comment]
The documentation on the timeout option is not clear and when I've tried using it every test file fails even if the timeout was met.

**Comment by novemberborn** [comment]
What additional information would you like to see? Could you elaborate on "when I've tried using it every test file fails even if the timeout was met"?
