### ISSUE TITLE
beautifyStack error when jsdom is imported

### ISSUE THREAD

**Issue by nfcampos** [sindresorhus/ava#822]
## Description

The following test file
```js
import test from 'ava'

import {jsdom} from 'jsdom'
global.document = jsdom('')
global.window = document.defaultView
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property]
  }
})

test('yay', t => {
  t.is(true, false)
})
```
results in an error when processing the test failure
<img width="533" alt="screen shot 2016-05-10 at 11 13 10" src="https://cloud.githubusercontent.com/assets/56902/15143157/38cbd8c0-16a0-11e6-8a2f-c49ee9732d75.png">
It's somehow related to that `Object.keys().forEach()` which copies properties from `window` to `global`. (if I comment it out it doesn't happen)
That snippet is what we suggest users do to use `enzyme` with `jsdom` https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md
I don't see anything wrong with it, since it doesn't replace any global properties that already existed.
So I'm not sure whether this is a bug with `ava` or not, but it at least looks like the error message wasn't printed in its entirety. 

## Environment

```
Node.js v6.0.0
darwin 15.4.0
```

**Comment by nfcampos** [comment]
I especially don't see how assigning stuff to `global` could result in a `SyntaxError` appearing where there was none.

**Comment by vdemedes** [comment]
For an unknown reason, the cause of this weird bug is assigning `XMLHttpRequest` to `global`. Test code to confirm:

```js
import test from 'ava'

import {jsdom} from 'jsdom'
global.document = jsdom('')
global.window = document.defaultView

Object
	.keys(document.defaultView)
	.filter(property => typeof global[property] === 'undefined')
	.filter(property => property !== 'XMLHttpRequest')
	.forEach(property => global[property] = document.defaultView[property]);

test('hey', t => {
	t.is(true, false);
});
```

<img width="289" alt="screenshot 2016-05-11 10 44 22" src="https://cloud.githubusercontent.com/assets/697676/15173554/597bf0da-1765-11e6-8fac-31ffe02ea084.png">

**Comment by vdemedes** [comment]
More information: error occurs only inside `test()` block. Code to confirm:

```js
import test from 'ava';

import {jsdom} from 'jsdom';
global.document = jsdom('');
global.window = document.defaultView;

console.log(new TypeError().stack);

Object
	.keys(document.defaultView)
	.filter(property => typeof global[property] === 'undefined')
	// .filter(property => property !== 'XMLHttpRequest')
	.forEach(property => global[property] = document.defaultView[property]);

console.log(new TypeError().stack);

test('hey', t => {
	console.log(new TypeError().stack);
});
```

**Comment by vdemedes** [comment]
Traced it down to `option-chain` module. I replaced it with a fake `test()` function and the error is gone. Investigating further.

**Comment by vdemedes** [comment]
Traced it down to this failing test case:

```js
import test from 'ava';

import {jsdom} from 'jsdom';
global.document = jsdom('');
global.window = document.defaultView;
global.XMLHttpRequest = document.defaultView.XMLHttpRequest;

test('hey', t => {
	t.is(false, true);
});
```

<img width="491" alt="screenshot 2016-05-11 11 46 22" src="https://cloud.githubusercontent.com/assets/697676/15175231/008d5ff0-176e-11e6-9586-43f9fdb39c85.png">


If you uncomment `global.window`, it works fine:

```js
import test from 'ava';

import {jsdom} from 'jsdom';
global.document = jsdom('');
// global.window = document.defaultView;
global.XMLHttpRequest = document.defaultView.XMLHttpRequest;

test('hey', t => {
	t.is(false, true);
});
```

<img width="295" alt="screenshot 2016-05-11 11 46 54" src="https://cloud.githubusercontent.com/assets/697676/15175244/131d6138-176e-11e6-9014-56fa6e9de572.png">

**Comment by nfcampos** [comment]
@vdemedes Thanks a lot for you investigation of this! based on your findings I think I've traced it the `source-map-support` module, where they use `(typeof window !== 'undefined') && (typeof XMLHttpRequest === 'function')` to check whether it's a browser environment. That's why it doesn't fail if you comment either of the two. What I'm not sure is exactly how that plays with `ava` to produce this weird bug

**Comment by vdemedes** [comment]
@nfcampos Thank you so much for your work as well! I spent half a morning and couldn't trace it down to the cause, this is a big help!

**Comment by novemberborn** [comment]
We use `source-map-support` to readjust stack traces:

> The module will by default assume a browser environment if XMLHttpRequest and window are defined. If either of these do not exist it will instead assume a node environment. In some rare cases, e.g. when running a browser emulation and where both variables are also set, you can explictly specify the environment to be either 'browser' or 'node'.

https://github.com/evanw/node-source-map-support#options

So we'd need to set that option.

**Comment by nfcampos** [comment]
do you guys want a PR adding that option?

**Comment by novemberborn** [comment]
@nfcampos that'd be great!

**Comment by nfcampos** [comment]
cool, I'll take care of that today or tomorrow

**Comment by nfcampos** [comment]
I've opened the PR! #829
