### ISSUE TITLE
system lock to prevent runner invoked twice

### ISSUE THREAD

**Issue by ORESoftware** [sindresorhus/ava#825]
Perhaps a good idea to include some locking mechanism at the system level to prevent the runner from being invoked before another run has completed. the default setting would have the lock be set to true, users could disable it.

**Comment by novemberborn** [comment]
What problem are you running into that prompted this suggestion?

**Comment by ORESoftware** [comment]
Well, it seems that AVA could have a central log file that could be written to by any project. Locking would mean that the central file could only be written to by one particular run at a time. Having a "central" file, as opposed to a log file in each individual project, would take some burden off the developer because they would not need to have separate terminal windows open for each log file, just the central one.

**Comment by vdemedes** [comment]
I'm not sure we still understand the problem you are suggesting to solve. Could you explain the issue you are running to explicitly?

**Comment by ORESoftware** [comment]
I don't currently have a problem, but considering that it can be resource intensive to run AVA with > 50 child_processes, perhaps it would be quite prudent on your part to provide a locking mechanism? It was just an idea :)

**Comment by jamestalmage** [comment]
Sorry, we don't add features unless they solve an existing pain point for our users. I am closing, but if you run into a specific problem, please share the details so we can discuss how to solve it.

**Comment by ORESoftware** [comment]
I think the most likely use case is this: 10 devs work on their Macs, and they have access to a shared linux box for development/testing. It's quite possible that different devs will logged into that linux box and attempt to run separate AVA runs in tandem which could cause problems. This is more likely than a developer running AVA runs in tandem on a single machine.

**Comment by jamestalmage** [comment]
If that starts happening to you in real life, let us know, and we can discuss from there.
