### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#83]
So other tools can use it without having to spawn. Right now I [spawn](https://github.com/sindresorhus/gulp-ava/blob/68dab5150299c7954492421b115889036f20b538/index.js#L20) in `gulp-ava`.

This would also help us have a better separation between the CLI and the API.

The API should be high-level and do whatever the CLI does now, like forking, etc. The CLI would just be a super-thin wrapper calling the API.

```js
const Ava = require('ava').Ava;

const instance = new Ava({
  files: ['foo.js', 'test/**'],
  failFast: true
});

instance.run();

instance.log().pipe(process.stdout);
```

The above is just a quick example. I hope it will end up looking better than that.

**Comment by kevva** [comment]
I'll try work on this tomorrow. Definitely needed.
