### ISSUE TITLE
programmatically call AVA tests

### ISSUE THREAD

**Issue by ORESoftware** [sindresorhus/ava#830]
In the case that a developer wants to pass data to a test file programmatically (not at the command line)

with Mocha, seemingly the only way to do this would be:

```js
function wrapTheMochaSuiteWithThisFn(data){


  describe('root suite', function(){

      describe('child suite', function(){

       data.forEach( item => {
             it('stubbed test case');
        });
      
     });

  });

}

if(require.main === module){
   wrapTheMochaSuiteWithThisFn([]);  // if test file is executing directly, run it
}

module.exports = wrapTheMochaSuiteWithThisFn;
```

will we have to do the same thing with AVA if we want to pass data / inject data into tests?

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/ava/issues/695

**Comment by jamestalmage** [comment]
Currently you have to do it the same way you do it in mocha. We are discussing an alternate solution in #695

**Comment by ORESoftware** [comment]
ah thanks
