### ISSUE TITLE
Support Observable

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#84]
Re https://github.com/mochajs/mocha/issues/1898

-

https://github.com/zenparsing/es-observable

@thejameskyle What do we need to do to support it?

I would guess calling `.forEach()` on the observable as that returns a promise.

**Comment by thejameskyle** [comment]
https://github.com/phated/async-done

This is the library used to resolve several different async types in gulp 4.0 (streams, promises, observables). You might want to make use of it.

cc @blesh

**Comment by blesh** [comment]
I don't think that `async-done` library supports RxJS 5 observables yet. The better path is to look for `Symbol.observable` on any incoming object, then call it and call `subscribe` on whatever object you get back. This will make it work with Kefir, Most and Bacon now as well I think.

**Comment by sindresorhus** [comment]
@blesh Can you open an issue/PR on `async-done`?

**Comment by blesh** [comment]
> @blesh Can you open an issue/PR on async-done?

Sorry, this got lost in my GitHub inbox... Does this still need to happen? I'm not sure i have time to do the PR anytime soon, unfortunately.

**Comment by sindresorhus** [comment]
@blesh Not really. We just went with adding support for it directly in AVA.
