### ISSUE TITLE
assert.throws and promises which resolve to error objects

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/ava#85]
[Currently](https://github.com/sindresorhus/ava/blob/d14c6e37fa4c9666599e78256cc0c9ccc39d45e5/lib/assert.js#L76-L87), the following test passes:
```js
test('resolve error value', t => {
	t.plan(1);
	t.throws(Promise.resolve(new Error('abc'))); // pass (false negative)
});
```

**Comment by blakeembrey** [comment]
Was just looking at trying out Ava and I'm actually surprised if something like this has support. Why would a resolved promise fail? You should be using `Promise.reject`.

**Comment by schnittstabil** [comment]
> You're saying that it shouldn't be failing, great :+1:

@blakeembrey Mhm, "it shouldn't be failing"? Well, the situation is a bit confusing :wink: 

I expect the following:

1. `Promise.resolve(new Error('abc'))` evaluates to a resolved Promise, and not to a rejected one
2. `t.throws(…)` asserts that its Promise argument will become rejected
3. the test *fails* (which it does not)

**Comment by blakeembrey** [comment]
@schnittstabil Yes, we're in agreement. For some reason I wrote all my comments in the context of the `resolve`, not the `throws`.
