### ISSUE TITLE
assert.throws, promises and regex

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/ava#86]
[Currently](https://github.com/sindresorhus/ava/blob/d14c6e37fa4c9666599e78256cc0c9ccc39d45e5/lib/assert.js#L76-L87), the last test fails:

```js
test('throw Error and regex', t => {
	t.plan(1);
	t.throws(() => { throw new Error('abc'); }, /b/); // pass (as expected)
});

test('reject error', t => {
	t.plan(1);
	t.throws(Promise.reject(new Error('abc'))); // pass (as expected)
});

test('reject error and regex', t => {
	t.plan(1);
	t.throws(Promise.reject(new Error('abc')), /b/); // fails (false positive)
});
```

**Comment by vdemedes** [comment]
You shouldn't pass regex as a second argument to t.throws(), second arg is error class.

**Comment by schnittstabil** [comment]
@vdemedes Not according to `readme.md`:
> .throws(function, error, [message])
> …
> error can be a constructor, **regex** or validation function.

**Comment by vdemedes** [comment]
Oh, my bad then, never mind. I will look into this issue.
