### ISSUE TITLE
Allow non-test files to take advantage of babel compilation

### ISSUE THREAD

**Issue by Whoaa512** [sindresorhus/ava#87]
I'm using AVA to write test some ES2015 source code but I get an error every time I try to do so.

I believe the offending line is in [lib/babel.js](https://github.com/sindresorhus/ava/blob/e9b3e5019de71e00725fa77b4f705c64e86e99c3/lib/babel.js#L8)

Not sure what the appropriate way to expose this should be, other then simply removing that line.

**Comment by sindresorhus** [comment]
You should explicitly depend on Babel in your own code. The AVA Babel thing is just for tests.

**Comment by Whoaa512** [comment]
I don't think I should have to add `require('babel/register')` at the top of every one of my source files. Especially if I already have a separate build process in place.

The use case here is that I would like to test my source files written in ES2015 simply by requiring them in the test file because unit testing should not require the involvement of my build system.

Perhaps exposing a flag in the AVA cli to disable of the `only` option within the call to babel/register.

**Comment by Qix-** [comment]
You shouldn't have to. You should only have to do `require('babel/register')` at the top of your entry point script.

**Comment by Whoaa512** [comment]
There is no single entry point since I'm individually unit testing each file.
