### ISSUE TITLE
Order of after() and afterEach()

### ISSUE THREAD

**Issue by paazmaya** [sindresorhus/ava#89]
I have this kind of a setup:

```js
test.afterEach('Refresh page', function (t) {
  nightmare.refresh();
  t.end();
});
test.after('End Nightmare', function (t) {
  nightmare.end();
  t.end();
});
```

I was assuming that `after()` would run after all tests, including the `afterEach()` which is running after each individual test cases.
However the final two output lines are:

``` 
  ✔ pages ›  End Nightmare
  ✔ pages ›  Refresh page
```

I would just like to confirm that is this expected behaviour?

**Comment by kevva** [comment]
Yeah, it seems like we're running `afterEach` after every `after` too. I don't know if that's intended @sindresorhus @vdemedes or should we change it?

**Comment by sindresorhus** [comment]
Sounds like a bug.

**Comment by kevva** [comment]
FWIW, these are the lines causing it https://github.com/sindresorhus/ava/blob/master/lib/runner.js#L87-L89. Not sure what's the nicest way to solve this. I guess we could pass on option to `_runTest` or something.

**Comment by vdemedes** [comment]
@paazmaya Thanks for reporting this!

**Comment by paazmaya** [comment]
@vdemedes thank you for fixing this! :grapes:
