### ISSUE TITLE
async/await fixture tests are unbreakable (or being ignored)

### ISSUE THREAD

**Issue by dylang** [sindresorhus/ava#92]
https://github.com/sindresorhus/ava/blob/master/test/test.js#L760-L766

I've changed the fixtures and the tests to try to make them break and I can't seem to break them. 

For example:

```js
// This still passes
test('async/await support', function (t) {
	t.plan(113);

	throw new Error('blah');

	execCli('fixture/async-await.js', function (err) {
		t.ifError(err);
	});
});
```

**Comment by dylang** [comment]
In addition, if I use the fixture as `execCli` is doing, it will pass if the test is in `/fixtures`, but fails if the test file is in the root directory of the repo:

<img width="1067" alt="screen shot 2015-10-23 at 7 27 42 am" src="https://cloud.githubusercontent.com/assets/51505/10691607/5fbdd73e-7958-11e5-9a37-02e5907065b0.png">

**Comment by sindresorhus** [comment]
That gives me:

```
  ...................................................................................................../Users/sindresorhus/dev/ava/test/test.js:763
	throw new Error('blah');
	^

Error: blah
    at Test.<anonymous> (/Users/sindresorhus/dev/ava/test/test.js:763:8)
    at Test.bound [as _cb] (/Users/sindresorhus/dev/ava/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Users/sindresorhus/dev/ava/node_modules/tape/lib/test.js:77:10)
    at Test.bound [as run] (/Users/sindresorhus/dev/ava/node_modules/tape/lib/test.js:61:32)
    at Immediate.next [as _onImmediate] (/Users/sindresorhus/dev/ava/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

I'm honestly not sure what you're trying to prove with that, though. As we're using `tape` to test AVA. So that has nothing to do with AVA.

-

As for the second comment, that's probably because we limit where Babel would compile.

-

I'm still unsure what the point of this issue is?

**Comment by dylang** [comment]
Okay, I thought the test wasn't working, but it must be user error. Closing, thanks!
