### ISSUE TITLE
No coverage

### ISSUE THREAD

**Issue by lagden** [sindresorhus/ava#94]
I was using `mocha` + `istanbul`!! Everything was fine, but I tried to switch to AVA because @sindresorhus is awesome!

I took a look in the [GOT](https://github.com/sindresorhus/got)

But my coverage still returns empty! :sob: 

<img width="643" alt="coverage" src="https://cloud.githubusercontent.com/assets/130963/10703044/0bc7e922-79ac-11e5-9d10-d5e27363fd35.png">

**Comment by sindresorhus** [comment]
You have to use [nyc](https://github.com/bcoe/nyc) as AVA spawns the test files.

> a code coverage tool built on istanbul that works for applications that spawn subprocesses. - nyc

-

I've been meaning to document this, but I wanted to ensure it works correctly with `nyc` before doing so.

**Comment by sindresorhus** [comment]
Oh, I just noticed you *are* using `nyc`. Do note that `got` is using master: https://github.com/sindresorhus/got/blob/f4cf6c7b44d047d505ed1fdf3a4e361b743bdfc2/package.json#L64 Try that.

We plan on doing another release in a few days.

**Comment by lagden** [comment]
I've tried that before open this issue, but ran using `ES6` code. :bug: 
And now, I run with `transpiled files` and works almost fine!! :smile: 

The coverage file is created apparently right in output folder, but the report appears empty when I run the test. Like the image above in the first post.

Well, I will waiting the new release.

Thanks for reply!

<img width="687" alt="out" src="https://cloud.githubusercontent.com/assets/130963/10704730/898a18a2-79b7-11e5-9f5f-b50b9932027b.png">

**Comment by sindresorhus** [comment]
Keeping this open so I don't forget to document it after the new release.

**Comment by lagden** [comment]
Fine!
Just a small feedback! In Travis, the report output worked!

![travis](https://cloud.githubusercontent.com/assets/130963/10705104/3f462be8-79ba-11e5-94a6-7c219c4e63b2.png)

**Comment by davidchase** [comment]
I seem to be still having the issue... im currently using `ava@0.3.0` with `nyc` and my coverage is blank...

Is the `ava@0.3.0` you the release that was suppose to happen? i also tried with `ava` from the gihub master branch and same results

**Comment by sindresorhus** [comment]
@davidchase Can you share something I can test?

**Comment by davidchase** [comment]
It seems like it was an issue how my nyc config was setup sorry about the previous comment... @sindresorhus do you know how fine tuned we can instrument excludes in nyc?

the setup below seems to include a lot more files than i need covered... maybe this is a better question for the `nyc` repo sorry to bug

```json
"config": {
    "nyc": {
      "exclude": [
        "node_modules/utils"
      ]
    }
  }
```

**Comment by sindresorhus** [comment]
@davidchase `nyc` supports the Istanbul config. Like: https://github.com/vesln/todo/blob/master/.istanbul.yml (I couldn't find the actual docs for that).

**Comment by davidchase** [comment]
hmm it seems like that `.istanbul.yml` does not work for me as i get no coverage and using the above json config i get too much :disappointed: cant find that happy medium...

**Comment by sindresorhus** [comment]
@davidchase Open an issue on `nyc`. I'm sure they'll happy to receive feedback on what needs improving ;)

**Comment by Qix-** [comment]
```
"node_modules/utils"
```

Why are you excluding just `node_modules/utils`? Usually you exclude all of `node_modules`.

**Comment by davidchase** [comment]
@Qix- so i have some files that live the `node_modules/utils` folder and i understood from [excluding-files](https://github.com/bcoe/nyc#excluding-files) setting up just the following config:

```json
"config": {
    "nyc": {
      "exclude": [
        "node_modules"
      ]
    }
  }
```
results in empty coverage ...

however specifying the exact folder `node_modules/utils` produces too many results... seemingly pull from other npm packages that live in `node_modules`

**Comment by Qix-** [comment]
Then yes, this is a bug within `nyc`.
