### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by lagden** [sindresorhus/ava#95]
Hi everyone!

I've got a false positive.

The AVA must have an option in `package.json` to disable `Babel` or possibility to config.

What happened!
I had written an library in ES6, but I decide change to current javascript and in the middle of recoding I forgot to remove:

```javascript
function consulta(cep, timeout = 10000) {
  //...
}
```
I ran the test and everything is ok.
So, I used the library in other app and :bug:

**Comment by sindresorhus** [comment]
Sorry about that. This was fixed in AVA 0.3.0. It now only transpiles the test file and not required dependencies.

**Comment by lagden** [comment]
Don't worry...
We are here to try help and make the AVA even better. :metal:
