### ISSUE TITLE
`power-assert` feedback

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#96]
Opening this just to gather some feedback about the new `power-assert` feature.

**Comment by sindresorhus** [comment]
```
test(t => {
	const foo = 'foo';
	t.ok(foo.indexOf('bar') !== -1);
	t.end();
});
````

```
t.ok(foo.indexOf('bar') !== -1)
           |
           -1
```

@twada Any way we could show the value of `foo` here too? I think that could be useful. @vdemedes What do you think?

**Comment by Qix-** [comment]
This is badass. This might actually make me switch to Ava. :dancer:

**Comment by sindresorhus** [comment]
@twada 

Currently this:

```
test(t => {
	const b = 'bar';
	const c = 'baz';
	t.is(b, c);
	t.end();
});
```

Outputs:

```
t.is(b, c)
       |  | 
       |  "baz"
       "bar"
```

Is there any way to have it output the old simple output when using direct inputs? Meaning no expressions.

Old simple output:

```
'bar' === 'baz'
```

That output is faster to look at.

**Comment by sindresorhus** [comment]
@twada @uiureo I've documented the enhanced asserts. Would appriciate your review. Happy to change anything. https://github.com/sindresorhus/ava/commit/89219ce6d64e1b4117c94a712dc96e8e8a37e661?short_path=0730bb7#diff-0730bb7c2e8f9ea2438b52e419dd86c9 :)

**Comment by vdemedes** [comment]
This is fucking amazing.

@sindresorhus, agree on the simple output, looks way better!

**Comment by twada** [comment]
First, as an author of [power-assert](https://github.com/power-assert-js/power-assert), I'm so glad to see this happen! :smile: 
Thank you @sindresorhus !

> @twada @uiureo I've documented the enhanced asserts. Would appriciate your review. Happy to change anything. 89219ce?short_path=0730bb7#diff-0730bb7c2e8f9ea2438b52e419dd86c9 :)

I think it's well written.

**Comment by twada** [comment]
@sindresorhus 

```
t.ok(foo.indexOf('bar') !== -1)
         |
         -1
```

> @twada Any way we could show the value of foo here too? I think that could be useful.

AVA's power-assert output is configured at [ava/enhance-assert.js](https://github.com/sindresorhus/ava/blob/c96622d6d8785719d16aa83d129cb5ffccbf9add/lib/enhance-assert.js#L22-L25) (see `renderers` section)

If you change `powerAssertRenderers.SuccinctRenderer` to `powerAssertRenderers.DiagramRenderer` like below,
```js
	empower(assert,
		powerAssertFormatter({
			renderers: [
				powerAssertRenderers.AssertionRenderer,
				powerAssertRenderers.DiagramRenderer
			]
		}),
		{
			destructive: true,
			modifyMessageOnRethrow: true,
			saveContextOnRethrow: false,
			patterns: module.exports.PATTERNS
		}
	);
```

You'll get verbose output like
```
t.ok(foo.indexOf('bar') !== -1)
     |   |              |
     |   |              |
     |   -1             false
     ["toto", "tata", "titi"]
```

It seems nice to have verbosity configuration options in AVA, and change power-assert renderers according to the option value.

**Comment by sindresorhus** [comment]
I know I'm asking a lot, but I would like the following not to use `power-assert`, since it's just direct input.

```js
test(t => {
    const b = 'bar';
    const c = 'baz';
    t.is(b, c);
    t.end();
});
```

But this should use `power-assert` since it's an expression and could benefit from the `power-assert` output.

```js
test(t => {
    const b = 'bar';
    const c = 'baz';
    const d = 'faz';
    t.is(b + d, c);
    t.end();
});
```

**Comment by twada** [comment]
@sindresorhus 

> Is there any way to have it output the old simple output when using direct inputs? Meaning no expressions.

Currently, `t.is` is [configured to be enhanced by power-assert](https://github.com/sindresorhus/ava/blob/c96622d6d8785719d16aa83d129cb5ffccbf9add/lib/enhance-assert.js#L3-L13) and power-assert cannot toggle output on and off by captured value for now.

What you mean here is that if two arguments are both in form of Identifier or Literal, and its values are simple primitives, AVA's power-assert feature should be turned off automatically. It is not possible now but worth challenging.

**Comment by twada** [comment]
@sindresorhus 

Oh I missed your next question!

> But this should use power-assert since it's an expression and could benefit from the power-assert output.

```js
test(t => {
    const b = 'bar';
    const c = 'baz';
    const d = 'faz';
    t.is(b + d, c);
    t.end();
});
```

Thank you for your clear example!
My answer is the same as former one --- It's not possible now, but I'll try to make it happen.

**Comment by sindresorhus** [comment]
It wouldn't nessecarily have to be turned off, could maybe just change the renderer to not show diagrams when `Identifier` or `Literal` is passed. This is just a nitpick/nicetohave, though.

**Comment by twada** [comment]
@sindresorhus Thanks, it's getting a bit easier.

**Comment by vdemedes** [comment]
@twada is `babel-plugin-espower` compatible with babel 6?

**Comment by twada** [comment]
@vdemedes Not yet. I'm [wrestling with Babel6 now](https://github.com/power-assert-js/babel-plugin-espower/pull/5).
Almost done but still doesn't work with `preset`s.

**Comment by SamVerschueren** [comment]
Not sure if I should create a new issue for this, but when using promises (await statements), `power-assert` does not show the correct value.

```
t.same(await fn(fixture1), {})
             |
             Object{}
```

The result of the promise is not empty, that's for sure :).

**Comment by twada** [comment]
@SamVerschueren Thank you for reporting!
Currently, power-assert only supports ES6/ES2015 expressions. So `AwaitExpression` is not supported yet and to be supported in next version. BTW, I'll take a look about this behavior.

**Comment by SamVerschueren** [comment]
Thanks for the feedback!

**Comment by sindresorhus** [comment]
@SamVerschueren Looks like https://github.com/sindresorhus/ava/issues/113.

**Comment by SamVerschueren** [comment]
Sorry, should have looked in the issue list first.

**Comment by twada** [comment]
@SamVerschueren No problem!

**Comment by jamestalmage** [comment]
@SamVerschueren - async/await fix is in master.

**Comment by SamVerschueren** [comment]
Awesome! :+1:

**Comment by novemberborn** [comment]
@sindresorhus is there any more feedback you're looking to collect in this issue, or shall we close it?

**Comment by sindresorhus** [comment]
Yup, can be closed in favor of https://github.com/twada/power-assert-renderers/issues/3.
