### ISSUE TITLE
Remove support for running the test file directly with node

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#97]
It's nice in theory to be able to `node test.js`, but the reality is that it complicates the code a lot and by using it that way you miss out on the best features of AVA. It also create diverging code paths that just becomes harder to maintain.

This would also fix #52.

@vdemedes I guess we can remove https://github.com/sindresorhus/ava/blob/c96622d6d8785719d16aa83d129cb5ffccbf9add/index.js#L75-L86 now. Anything else that can be removed/simplified because of this?

**Comment by schnittstabil** [comment]
With #83, removing does not have to be a real "either-or decision". It would be up to the user:

```js
// test.js
import test from 'ava';

test(t => {
    t.pass();
    t.end();
});

test.runAndExit(); // or a similar one-liner
```

**Comment by sindresorhus** [comment]
@schnittstabil The programmatic API is meant for running the tests, not be used in the test file itself.

**Comment by timoxley** [comment]
Would be good to reverse this decision… the ability to run tests without the `ava` process simplifies things as it removes any complications and potentially subtle bugs created by having different versions of AVA installed globally and in `node_modules/.bin`, even if it required additional hoops such as loading a bootstrap file first e.g. via the `node --require` flag.

**Comment by sindresorhus** [comment]
@timoxley Yes, we intend too, but shouldn't be default as it will (and did) cause subtle bugs.

Follow: https://github.com/sindresorhus/ava/issues/111

**Comment by timoxley** [comment]
@sindresorhus ty.
